In [1]:
import pandas as pd
import numpy as np
import os
pd.set_option('display.max_columns',None)

In [2]:
os.chdir(r"C:\Users\mohammadali1.vc\Desktop\Python data\Large Check File")
dift=pd.read_csv("FDP_17 Jul.csv")
dift1=pd.read_csv("FDP_02 June.csv")
dif=pd.concat([dift,dift1])
dif=dif.drop_duplicates(subset='tracking_id')
dif.dropna(subset=["ph_in_time", "dh_receive_time","ph_in_date_final"], how="all", inplace=True)
dif

C:\Users\mohammadali1.vc\AppData\Local\Temp\ipykernel_32248\3176644227.py:2: DtypeWarning: Columns (0: order_id, 1: global_tracking_id, 2: product_id, 3: is_forward, 4: upstream_rto_flag, 5: global_merchant_reference_id, 6: first_rvp_pickup_time, 7: last_rvp_pickup_time, 8: actual_rvp_pickup_time) have mixed types. Specify dtype option on import or set low_memory=False.
  dift=pd.read_csv("FDP_17 Jul.csv")
C:\Users\mohammadali1.vc\AppData\Local\Temp\ipykernel_32248\3176644227.py:3: DtypeWarning: Columns (0: order_id, 1: global_tracking_id, 2: product_id, 3: is_forward, 4: upstream_rto_flag, 5: global_merchant_reference_id, 6: first_rvp_pickup_time, 7: last_rvp_pickup_time, 8: actual_rvp_pickup_time, 9: checks, 10: ismandatory_list, 11: fe_result_list, 12: checks_failed) have mixed types. Specify dtype option on import or set low_memory=False.
  dift1=pd.read_csv("FDP_02 June.csv")

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,first_ph_in_post_rto_hub_name,first_ph_in_post_rto_datetime
0,TFC001512055,NaN,AMAP0000000577,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-06-15T14:44:54.000+05:30,ShipmentDelivered,110086.0,Delhi,DELHI,560068.0,BANGALORE,KARNATAKA,2026-06-10T10:29:29.000+05:30,1.0,2026-06-10T10:27:23.000+05:30,2026-06-10,2026-06-10T14:53:05.000+05:30,2026-06-15T05:01:43.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T14:44:54.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5510.25,0.0,19000.0,METRO,False,NaN,2026-06-15T03:15:00+0530,PICKUPHUB_RPBAGHFM,BulkHub_BLR,2026-06-15,2026-06-10,SPS,120.0,25.0,19000.0,25.0,BulkHub_BLR,BulkHub_BLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN
1,TFC001512213,NaN,AMAP0000000819,FSD_LARGE,AMA,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-07-05T18:00:57.000+05:30,ShipmentDelivered,110086.0,Delhi,DELHI,580023.0,DHARWAD,KARNATAKA,2026-06-30T11:09:07.000+05:30,1.0,2026-06-30T11:08:46.000+05:30,2026-06-30,2026-06-30T17:18:09.000+05:30,2026-07-05T05:25:29.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T18:00:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5628.75,0.0,13000.0,ROI,False,NaN,2026-07-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_FKHBLA,2026-07-05,2026-06-30,SPS,110.0,20.0,13000.0,20.0,SATELLITEHUB_FKHBLA,SATELLITEHUB_FKHBLA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN
2,940069,NaN,ARLP0000003366,FSD_LARGE,ARL,SINGER COOKMATE 5L,SINGER COOKMATE 5L,ext_sps,ARL,ARL : ARL_THA_01,ARL_448c561fc19f951b85377ebb5382e9af,Forward,SHIPMENT,PP,N,True,2026-06-12T18:26:13.000+05:30,ShipmentDelivered,401105.0,Thane,MAHARASHTRA,800007.0,PATNA,BIHAR,2026-06-03T17:31:02.000+05:30,1.0,2026-06-03T17:30:54.000+05:30,2026-06-04,2026-06-04T16:51:05.000+05:30,2026-06-12T05:01:52.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T18:26:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2784.00,0.0,2600.0,ROI,False,NaN,2026-06-13T03:15:00+0530,Pickuphub_FKMIB,SatelliteHub_PAT,2026-06-13,2026-06-04,SPS,45.0,20.0,2600.0,25.0,SatelliteHub_PAT,SatelliteHub_PAT,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN
3,ORD-SO-813176,NaN,AWPC0000077622,FSD_LARGE,AWP,Hymatic Single Battery 12X8 16 Ltr Battery Ope...,ATE3A59AE91CK26A71A05,ext_sps,AWP,AWP : Patna WH,AWP_06690e9940963d92d58bcb3a6563d29c,Forward,SHIPMENT,COD,Z,True,2026-07-11T22:05:14.000+05:30,ShipmentDelivered,803201.0,Patna,BIHAR,851213.0,KHAGARIA,BIHAR,2026-07-08T11:39:50.000+05:30,1.0,2026-07-08T11:39:46.000+05:30,2026-07-08,2026-07-08T19:14:25.000+05:30,2026-07-11T07:45:01.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T22:05:14.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4874.00,3874.0,24450.0,ZONAL,False,NaN,2026-07-14T03:15:00+0530,PickupHub_PAT,SATELLITEHUB_KGG,2026-07-14,2026-07-08,SPS,64.0,49.0,24450.0,39.0,SATELLITEHUB_KGG,SATELLITEHUB_KGG,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN
4,ORD-SO-796826,NaN,AWPC0000078604,FSD_LARGE,AWP,BALWAAN DOUBLE BATTERY-DOUBLE MOTOR BS-22D 12X...,ATE3A59AB38GD97A63A05,ext_sps,AWP,AWP : Rohit Bajaj,AWP_85296f55bcc56dc187a14f2f9c6e8299,Forward,SHIPMENT,COD,Z,True,2026-07-08T22:24:37.000+05:30,ShipmentDelivered,711302.0,Howrah,WEST BENGAL,848201.0,BEGUSARAI,BIHAR,2026-07-01T10:03:55.000+05:30,4.0,2026-07-01T10:03:33.000+05:30,2026-07-04,2026-07-04T20:05:00.000+05:30,2026-07-08T06:33:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T22:24:37.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,7370.00,6870.0,29172.0,ZONAL,False,NaN,2026-07-11T03:15:00+0530,PickupHub_FKHWH,Satellitehub_FKBEGU,2026-07-11,2026-07-04,SPS,64.0,53.0,29172.0,43.0,Satellitehub_FKBEGU,Satellitehub_FKBEGU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777294,WRA4GXJSXQAYP51X,NaN,UNCP0000312158,FSD_LARGE,UNC,IIT JEE 4.0 NOTES,IIT JEE 4.0 NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-03-30T19:02:34.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,131001.0,SONIPAT,HARYANA,2026-03-23T15:37:34.000+05:30,3.0,2026-03-23T15:37:13.000+05:30,2026-03-25,2026-03-25T17:36:19.000+05:30,2026-03-30T07:21:26.000+05:30,2026-03-30T10:33:48.000+05:30,2026-03-30T14:04:08.000+05:30,2026-03-30T19:02:34.000+05:30,Attempted,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,8970.0,ROI,False,NaN,2026-03-30T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_SONIPAT,2026-03-30,2026-03-25,SPS,22.0,22.0,8970.0,29.0,SATELLITEHUB_SONIPAT,SATELLITEHUB_SONIPAT,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN
777295,1KPVKX484B6TLPZM,NaN,UNCP0000312280,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-01T18:04:23.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,143505.0,GURDASPUR,PUNJAB,2026-03-23T15:37:33.000+05:30,4.0,2026-03-23T15:37:13.000+05:30,2026-03-26,2026-03-26T18:09:13.000+05:30,2026-04-01T00:50:52.000+05:30,2026-04-01T09:50:26.000+05:30,2026-04-01T09:50:26.000+05:30,2026-04-01T18:04:23.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-01T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_BATALA,2026-04-01,2026-03-26,SPS,20.0,19.0,6640.0,26.0,SATELLITEHUB_BATALA,SATELLITEHUB_BATALA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN
777296,RGF4XP1KL9,NaN,UNCP0000312643,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-02T21:51:05.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,824111.0,BANKA,BIHAR,2026-03-23T15:37:15.000+05:30,4.0,2026-03-23T15:37:09.000+05:30,2026-03-26,2026-03-26T18:09:14.000+05:30,2026-04-02T00:39:21.000+05:30,2026-04-02T07:56:21.000+05:30,2026-04-02T07:56:21.000+05:30,2026-04-02T21:51:05.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-04T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_ABD,2026-04-04,2026-03-26,SPS,20.0,19.0,6640.0,26.0,Satellitehub_ABD,Satellitehub_ABD,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN
777297,5XYZFK5V3Y0NOT0N,NaN,UNCP0000314002,FSD_LARGE,UNC,GATE ELECTRICAL,GATE ELECTRICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18T23:10:07.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,382330.0,AHMEDABAD,GUJARAT,2026-04-10T14:36:23.000+05:30,4.0,2026-04-10T14:36:17.000+05:30,2026-04-13,2026-04-13T17:10:58.000+05:30,2026-04-18T07:53:46.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T23:10:07.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,5710.0,METRO,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_NAR,2026-04-19,2026-04-13,SPS,19.0,18.0,5710.0,25.0,SatelliteHub_NAR,SatelliteHub_NAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN
777298,WETER7WN993JO9OG,NaN,UNCP0000314142,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-19T18:09:19.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,752001.0,PURI,ODISHA,2026-04-10T14:36:31.000+05:30,4.0,2026-04-10T14:36:18.000+05:30,2026-04-13,2026-04-13T17:10:59.000+05:30,2026-04-19T04:27:51.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T18:09:19.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-20T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_FKPUR,2026-04-20,2026-04-13,SPS,30.0,8.0,3480.0,21.0,Satellitehub_FKPUR,Satellitehub_FKPUR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN

In [3]:
dif["dispatch_month"] = pd.to_datetime(dif["dispatch_date"], format='mixed').dt.month
d9=dif[~dif['dispatch_month'].isin([10,11,12,1,2,3])]
d9.dispatch_month.value_counts()

dispatch_month
6    267246
4    259322
5    238473
7    156723
Name: count, dtype: int64

In [4]:
d9.dispatch_date.isnull().sum()

np.int64(0)

In [5]:
#d9["dispatch_month"] =  pd.to_datetime(d9["dispatch_date"],format="%Y-%m-%d %H:%M:%S").dt.month
#d9["dispatch_month"] = pd.to_datetime(d9["dispatch_date"],format="%Y-%m-%d").dt.month
d9["dispatch_month"] = pd.to_datetime(d9["dispatch_date"], format='mixed').dt.month
#d9["created_month"] = pd.to_datetime(d9["created_at"], format="%Y-%m-%d %H:%M:%S", errors='coerce').dt.month
#d9["ph_in_month"] = pd.to_datetime(d9["ph_in_time"], format="%Y-%m-%d %H:%M:%S", errors='coerce').dt.month

#d9["created_month"] =  pd.to_datetime(d9["created_at"],format="%Y-%m-%d %H:%M:%S").dt.month
#d9["ph_in_month"] =  pd.to_datetime(d9["ph_in_time"],format="%Y-%m-%d %H:%M:%S").dt.month
#d9

In [6]:
d91=d9[~d9['current_status'].isin(['PickupCancelled','OutForPickupEvent','PickupRescheduledEvent'])]
d91

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,first_ph_in_post_rto_hub_name,first_ph_in_post_rto_datetime,dispatch_month
0,TFC001512055,NaN,AMAP0000000577,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-06-15T14:44:54.000+05:30,ShipmentDelivered,110086.0,Delhi,DELHI,560068.0,BANGALORE,KARNATAKA,2026-06-10T10:29:29.000+05:30,1.0,2026-06-10T10:27:23.000+05:30,2026-06-10,2026-06-10T14:53:05.000+05:30,2026-06-15T05:01:43.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T14:44:54.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5510.25,0.0,19000.0,METRO,False,NaN,2026-06-15T03:15:00+0530,PICKUPHUB_RPBAGHFM,BulkHub_BLR,2026-06-15,2026-06-10,SPS,120.0,25.0,19000.0,25.0,BulkHub_BLR,BulkHub_BLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6
1,TFC001512213,NaN,AMAP0000000819,FSD_LARGE,AMA,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-07-05T18:00:57.000+05:30,ShipmentDelivered,110086.0,Delhi,DELHI,580023.0,DHARWAD,KARNATAKA,2026-06-30T11:09:07.000+05:30,1.0,2026-06-30T11:08:46.000+05:30,2026-06-30,2026-06-30T17:18:09.000+05:30,2026-07-05T05:25:29.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T18:00:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5628.75,0.0,13000.0,ROI,False,NaN,2026-07-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_FKHBLA,2026-07-05,2026-06-30,SPS,110.0,20.0,13000.0,20.0,SATELLITEHUB_FKHBLA,SATELLITEHUB_FKHBLA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6
2,940069,NaN,ARLP0000003366,FSD_LARGE,ARL,SINGER COOKMATE 5L,SINGER COOKMATE 5L,ext_sps,ARL,ARL : ARL_THA_01,ARL_448c561fc19f951b85377ebb5382e9af,Forward,SHIPMENT,PP,N,True,2026-06-12T18:26:13.000+05:30,ShipmentDelivered,401105.0,Thane,MAHARASHTRA,800007.0,PATNA,BIHAR,2026-06-03T17:31:02.000+05:30,1.0,2026-06-03T17:30:54.000+05:30,2026-06-04,2026-06-04T16:51:05.000+05:30,2026-06-12T05:01:52.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T18:26:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2784.00,0.0,2600.0,ROI,False,NaN,2026-06-13T03:15:00+0530,Pickuphub_FKMIB,SatelliteHub_PAT,2026-06-13,2026-06-04,SPS,45.0,20.0,2600.0,25.0,SatelliteHub_PAT,SatelliteHub_PAT,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6
3,ORD-SO-813176,NaN,AWPC0000077622,FSD_LARGE,AWP,Hymatic Single Battery 12X8 16 Ltr Battery Ope...,ATE3A59AE91CK26A71A05,ext_sps,AWP,AWP : Patna WH,AWP_06690e9940963d92d58bcb3a6563d29c,Forward,SHIPMENT,COD,Z,True,2026-07-11T22:05:14.000+05:30,ShipmentDelivered,803201.0,Patna,BIHAR,851213.0,KHAGARIA,BIHAR,2026-07-08T11:39:50.000+05:30,1.0,2026-07-08T11:39:46.000+05:30,2026-07-08,2026-07-08T19:14:25.000+05:30,2026-07-11T07:45:01.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T22:05:14.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4874.00,3874.0,24450.0,ZONAL,False,NaN,2026-07-14T03:15:00+0530,PickupHub_PAT,SATELLITEHUB_KGG,2026-07-14,2026-07-08,SPS,64.0,49.0,24450.0,39.0,SATELLITEHUB_KGG,SATELLITEHUB_KGG,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7
4,ORD-SO-796826,NaN,AWPC0000078604,FSD_LARGE,AWP,BALWAAN DOUBLE BATTERY-DOUBLE MOTOR BS-22D 12X...,ATE3A59AB38GD97A63A05,ext_sps,AWP,AWP : Rohit Bajaj,AWP_85296f55bcc56dc187a14f2f9c6e8299,Forward,SHIPMENT,COD,Z,True,2026-07-08T22:24:37.000+05:30,ShipmentDelivered,711302.0,Howrah,WEST BENGAL,848201.0,BEGUSARAI,BIHAR,2026-07-01T10:03:55.000+05:30,4.0,2026-07-01T10:03:33.000+05:30,2026-07-04,2026-07-04T20:05:00.000+05:30,2026-07-08T06:33:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T22:24:37.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,7370.00,6870.0,29172.0,ZONAL,False,NaN,2026-07-11T03:15:00+0530,PickupHub_FKHWH,Satellitehub_FKBEGU,2026-07-11,2026-07-04,SPS,64.0,53.0,29172.0,43.0,Satellitehub_FKBEGU,Satellitehub_FKBEGU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777289,XPYE2ETDDR8JIQTK,NaN,UNCP0000314145,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18T15:45:26.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,302021.0,JAIPUR,RAJASTHAN,2026-04-10T14:36:23.000+05:30,4.0,2026-04-10T14:36:16.000+05:30,2026-04-13,2026-04-13T17:10:51.000+05:30,2026-04-18T02:09:37.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T15:45:26.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JAI,2026-04-19,2026-04-13,SPS,30.0,8.0,3480.0,21.0,SatelliteHub_JAI,SatelliteHub_JAI,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4
777290,CP66PCOX4L,NaN,UNCP0000314813,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-01T21:43:49.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,274301.0,DEORIA,UTTAR PRADESH,2026-04-14T17:45:23.000+05:30,3.0,2026-04-14T17:45:18.000+05:30,2026-04-17,2026-04-17T17:33:07.000+05:30,2026-04-30T23:56:26.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T21:43:49.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-28T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_KUSHINAGAR,2026-04-28,2026-04-17,SPS,20.0,19.0,6640.0,26.0,SATELLITEHUB_KUSHINAGAR,SATELLITEHUB_KUSHINAGAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4
777291,E5VOT73QQV,NaN,UNCP0000314816,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-07T18:25:57.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,805110.0,NAWADA,BIHAR,2026-04-14T17:45:45.000+05:30,3.0,2026-04-14T17:45:24.000+05:30,2026-04-17,2026-04-17T17:33:03.000+05:30,2026-05-07T06:00:49.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T18:25:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-26T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_FKNWD,2026-04-26,2026-04-17,SPS,20.0,19.0,6640.0,26.0,Satellitehub_FKNWD,Satellitehub_FKNWD,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4
777297,5XYZFK5V3Y0NOT0N,NaN,UNCP0000314002,FSD_LARGE,UNC,GATE ELECTRICAL,GATE ELECTRICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18T23:10:07.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,382330.0,AHMEDABAD,GUJARAT,2026-04-10T14:36:23.000+05:30,4.0,2026-04-10T14:36:17.000+05:30,2026-04-13,2026-04-13T17:10:58.000+05:30,2026-04-18T07:53:46.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T23:10:07.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,5710.0,METRO,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_NAR,2026-04-19,2026-04-13,SPS,19.0,18.0,5710.0,25.0,SatelliteHub_NAR,SatelliteHub_NAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4
777298,WETER7WN993JO9OG,NaN,UNCP0000314142,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-19T18:09:19.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,752001.0,PURI,ODISHA,2026-04-10T14:36:31.000+05:30,4.0,2026-04-10T14:36:18.000+05:30,2026-04-13,2026-04-13T17:10:59.000+05:30,2026-04-19T04:27:51.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T18:09:19.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-20T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_FKPUR,2026-04-20,2026-04-13,SPS,30.0,8.0,3480.0,21.0,Satellitehub_FKPUR,Satellitehub_FKPUR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4

In [7]:
#d91['created_at'] = pd.to_datetime(d91['created_at'],format='%Y-%m-%d %H:%M:%S').dt.date
#d91['ph_in_time'] = pd.to_datetime(d91['ph_in_time'],format='%Y-%m-%d %H:%M:%S').dt.date
d91['created_at'] = pd.to_datetime(d91['created_at'],format='mixed').dt.date
d91['ph_in_time'] = pd.to_datetime(d91['ph_in_time'],format='mixed').dt.date

In [8]:
d91['PH_IN_date']=d91['ph_in_time']
#d91['PH_IN_date'] = d91['PH_IN_date'].apply(lambda x: pd.to_datetime(x, format="%Y-%m-%d").date() if isinstance(x, str) else pd.NaT)
d91['PH_IN_date'] = pd.to_datetime(d91['PH_IN_date'],format='mixed').dt.date
d91['last_updated_at'] = pd.to_datetime(d91['last_updated_at'],format='mixed').dt.date
d91.last_updated_at.value_counts()

last_updated_at
2026-07-16    41729
2026-07-15    21727
2026-07-14    14997
2026-07-13    12135
2026-07-08    10867
              ...
2026-07-17     3910
2026-04-05     2786
2026-04-04     1831
2026-04-03      525
2026-04-02       18
Name: count, Length: 107, dtype: int64

In [9]:
d91['FDP_status']=np.where((d91['current_status'] == 'ShipmentDelivered') & (d91['ekl_shipment_type'] == 'Forward'),'delivered',
                    np.where((d91['current_status'] == 'ShipmentRtoCompleted') & (d91['ekl_shipment_type'] == 'RTO'), 'Returned_to_seller','Open'))
d91['FDP_status'] = np.where((d91['FDP_status'] == "Open") & (d91['ekl_shipment_type'] == 'RTO'),"Open-RTO", d91.FDP_status)
d91.FDP_status.value_counts()

FDP_status
delivered             774005
Open                   81091
Returned_to_seller     58342
Open-RTO                8326
Name: count, dtype: int64

In [10]:
d91['end_date'] = d91['last_updated_at']

In [11]:
d91['PH_IN_date'] = pd.to_datetime(d91['PH_IN_date'], format='%Y-%m-%d %H:%M:%S')
d91['end_date'] = pd.to_datetime(d91['end_date'], format='%Y-%m-%d %H:%M:%S')
d91['ageing'] = (d91['end_date'] - d91['PH_IN_date']).dt.days

In [12]:
m1=d91[d91['FDP_status'].isin(['Open','Open-RTO'])]
m1

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,first_ph_in_post_rto_hub_name,first_ph_in_post_rto_datetime,dispatch_month,PH_IN_date,FDP_status,end_date,ageing
13,ORD-SO-731125,NaN,AWPC0000083704,FSD_LARGE,AWP,SUMITOMO TOBLER 500ML,CPB5F14AM94FE32A00B73,ext_sps,AWP,AWP : Naveen Kumar,AWP_07244bb3805e9199e4db17a298d96c62,Forward,SHIPMENT,COD,N,True,2026-07-03,ShipmentUndeliveredAttempted,132001.0,Karnal,HARYANA,854101.0,KATIHAR,BIHAR,2026-05-29,1.0,2026-05-29T14:08:14.000+05:30,2026-05-29,2026-05-29,2026-06-04T07:02:57.000+05:30,2026-06-10T08:27:01.000+05:30,2026-07-03T08:15:41.000+05:30,NaN,Attempted,NaN,4.0,Customer Not Responding,Customer Not Responding,NaN,Customer Not Responding,NaN,NaN,NaN,6768.00,5006.0,12000.0,ROI,False,NaN,2026-06-08T04:15:00+0530,PickupHub_KNL1,Satellitehub_Naugachia,2026-06-08,2026-05-29,SPS,39.0,33.0,12000.0,21.0,Satellitehub_Naugachia,Satellitehub_Naugachia,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,5,2026-05-29,Open,2026-07-03,35.0
29,ORD-SO-825295,AWPN0001075113,AWPC0001075112,FSD_LARGE,AWP,Neptune Manual Plastic NF 02 16 Ltr Manual Spr...,SO-825295,ext_mps,AWP,AWP : Patna WH,AWP_fcfe04c4cd66102f646dfcb64a0af4fa,Forward,SHIPMENT,COD,Z,True,2026-07-15,InScanAtHub,803201.0,Patna,BIHAR,731237.0,SURI,WEST BENGAL,2026-07-14,1.0,2026-07-14T13:24:42.000+05:30,2026-07-14,2026-07-14,NaN,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3701.00,1701.0,26799.0,ZONAL,False,AWPN0001075113,2026-07-19T12:21:05+0530,PickupHub_PAT,CentralHub_L_PAT6,2026-07-19,2026-07-14,MPS,67.0,40.0,26799.0,50.0,NaN,Satellitehub_Rampurhat,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,2026-07-14,Open,2026-07-15,1.0
31,ORD-SO-817892,AWPN0001075749,AWPC0001075748,FSD_LARGE,AWP,CHEMCHURA AGRITECH RIGHT FIT PLUS 600ML,SO-817892,ext_mps,AWP,AWP : Amit Goel,AWP_5e3ad64a3e27a6b7a809e96b3c38c46e,RTO,RTO,COD,Z,True,2026-07-16,ReturnInScanAtHub,110007.0,Delhi,DELHI,224204.0,BIKAPUR,UTTAR PRADESH,2026-07-10,1.0,2026-07-10T14:54:51.000+05:30,2026-07-10,2026-07-10,2026-07-13T05:04:02.000+05:30,2026-07-15T09:04:40.000+05:30,2026-07-15T09:04:40.000+05:30,NaN,Attempted,NaN,1.0,OrderRejectedByCustomer,OrderRejectedByCustomer,NaN,OrderRejectedByCustomer,Rejected_by_Customer,ShipmentUndeliveredAttempted,NaN,20803.00,18572.0,11250.0,ZONAL,False,AWPN0001075749,2026-07-16T11:04:42+0530,PickupHub_SWP,CentralHub_L_LKO3,2026-07-16,2026-07-10,MPS,37.0,30.0,11250.0,25.0,SATELLITEHUB_AYODHYA,PICKUPHUB_MPHUB_SWP,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-10,Open-RTO,2026-07-16,6.0
78,408-9052710-1592308,NaN,BGHP1005524928,FSD_LARGE,BGH,DRYNEST030 SCISSOR AIRER MAHADEV,6215405,ext_sps,BGH,BGH : HAVAI HOME PRODUCTS PRIVATE LIMITED,BGH_9fa4382ac033d839659ace49ab43d6be,RTO,RTO,PP,N,True,2026-07-14,InScanAtHub,400701.0,THANE,MAHARASHTRA,795001.0,IMPHAL,MANIPUR,2026-06-23,5.0,2026-06-23T17:17:23.000+05:30,2026-06-29,2026-06-29,NaN,NaN,NaN,NaN,Not_Attempted,2026-07-08T21:48:08.000+05:30,0.0,NaN,NaN,CentralHub_PBI,NaN,Cancel the shipment,NaN,ManpowerIssue,2690.00,0.0,2000.0,JK_NE,True,NaN,2026-07-11T00:15:00+0530,PickupHub_TURB,CentralHub_L_KOL5,2026-07-11,2026-06-29,SPS,46.0,89.0,2000.0,7.0,NaN,Pickuphub_MPhub_TURB,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,2026-06-29,Open-RTO,2026-07-14,15.0
79,bc7cd6ba-bcda-44b1-bdaf-8,NaN,BGHP1005586632,FSD_LARGE,BGH,ID CARDS RAW MATERIAL,6286944,ext_sps,BGH,BGH : RJR CREATION,BGH_11e168a2db65cf9fc0d5bacaa7093395,Forward,SHIPMENT,PP,N,True,2026-07-16,InscannedAtDH,141001.0,LUDHIANA,PUNJAB,782481.0,HOWRAGHAT,ASSAM,2026-07-09,1.0,2026-07-09T13:18:24.000+05:30,2026-07-10,2026-07-10,2026-07-16T06:32:43.000+05:30,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9600.00,0.0,7720.0,JK_NE,False,NaN,2026-07-23T03:15:00+0530,PickupHub_LUD,SATELLITEHUB_DPU,2026-07-23,2026-07-10,SPS,21.0,15.0,7720.0,27.0,NaN,SATELLITEHUB_DPU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,2026-07-10,Open,2026-07-16,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755626,NYK-344960769-4196499-1,NaN,NKDC0000044690,FSD_LARGE,NKD,Nykaa Black Magic Kajal - Black(0.3gm),NYKAC00000132,ext_sps,NKD,NKD : Nykaa eB2B Warehouse Patna,NKD_ef2707b9c90671f302cc91d92780951a,RTO,RTO,COD,Z,True,2026-04-17,ShipmentUndeliveredAttempted,804451.0,Patna,BIHAR,802158.0,ARRAH,BIHAR,2026-04-13,1.0,2026-04-13T11:29:33.000+05:30,2026-04-13,2026-04-13,2026-04-16T05:37:27.000+05:30,2026-04-16T09:35:36.000+05:30,2026-04-16T09:35:36.000+05:30,NaN,Attempted,2026-04-17T00:02:09.000+05:30,1.0,OrderRejectedByCustomer,OrderRejectedByCustomer,Satellitehub_BhojpurSplit,OrderRejectedByCustomer,ORC_validated with customer,ShipmentUndeliveredAttempted,NaN,2388.00,994.0,500.0,ZONAL,False,NaN,2026-04-17T04:15:00+0530,PickupHub_PAT,Satellitehub_BhojpurSplit,2026-04-17,2026-04-13,SPS,27.0,9.0,500.0,19.0,Satellitehub_BhojpurSplit,Pickuphub_MPhub_PAT,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,4,2026-04-13,Open-RTO,2026-04-17,4.0
756306,CP26643391_1,NaN,PRHP0000152761,FSD_LARGE,PRH,Bank Mahapack Selection Box Hindi Book Kit,19702,ext_sps,PRH,PRH : Metis Eduventures Private Limited,PRH_03cdd8b0b4e9b5df79c34db861cc1e22,RTO,RTO,PP,N,True,2026-06-02,InScanAtHub,201301.0,Noida,UTTAR PRADESH,403802.0,SOUTH GOA,GOA,2026-04-03,1.0,2026-04-03T11:44:53.000+05:30,2026-04-03,2026-04-03,NaN,NaN,NaN,NaN,Not_Attempted,2026-05-04T14:59:13.000+05:30,0.0,NaN,NaN,Motherhub_GGN,NaN,Shipment Delayed,NaN,NaN,3220.31,0.0,2853.0,ROI,True,NaN,2026-04-08T03:15:00+0530,PICKUPHUB_GNOIDAFM,Motherhub_JKS,2026-04-08,2026-04-03,SPS,5.0,5.0,2853.0,5.0,NaN,PickupHub_MPHub_GNOIDAFM,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,2026-04-03,Open-RTO,2026-06-02,60.0
763278,REHP0000027425,NaN,REHP0000027425,FSD_LARGE,REH,Livpure Comforter Pink steel grey Single 56x90...,Livpure Comforter Pink steel grey Single 56x90...,ext_sps,REH,REH : Warehouse,REH_b0a1d8b5d056129d2a6de99d1e691e29,Forward,SHIPMENT,PP,N,True,2026-06-01,InScanAtHub,560058.0,Bangalore,KARNATAKA,110034.0,NEW DELHI,DELHI,2026-05-26,1.0,2026-05-26T13:11:00.000+05:30,2026-05-26,2026-05-26,NaN,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3500.00,0.0,5000.0,METRO,False,NaN,2026-06-02T03:15:00+0530,PickupHub_FKYWP,CentralHub_L_YKBX1,2026-06-02,2026-05-26,SPS,0.0,0.0,5000.0,0.0,NaN,SATELLITEHUB_AZADPUR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,2026-05-26,Open,2026-06-01,6.0
764134,REHP0000027349,NaN,REHP0000027349,FSD_LARGE,REH,Maharaja Ednis Neo Water heater - 10 Litre |,Maharaja Ednis Neo Water heater - 10 Litre |,ext_sps,REH,REH : Warehouse,REH_b0a1d8b5d056129d2a6de99d1e691e29,Forward,SHIPMENT,PP,Z,True,2026-05-25,InScanAtHub,560058.0,Bangalore,KARNATAKA,600048.0,CHENNAI,TAMIL NADU,2026-05-23,1.0,2026-05-23T14:10:08.000+05:30,2026-05-23,2026-05-23,NaN,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7599.00,0.0,5000.0,ZONAL,False,NaN,2026-05-28T03:15:00+0530,PickupHub_FKYWP,CentralHub_L_CHNX7,2026-05-28,2026-05-23,SPS,0.0,0.0,5000.0,0.0,NaN,SatelliteHub_TMB1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,2026-05-23,Open,2026-05-25,2.0
765810,REHP0000011496,NaN,REHP0000011496,FSD_LARGE,REH,Sujata Pedestal Fan SPF09 |,Sujata Pedestal Fan SPF09 |,ext_sps,REH,REH : Warehouse,REH_b0a1d8b5d056129d2a6de99d1e691e29,Forward,SHIPMENT,PP,Z,True,2026-05-30,InScanAtHub,560058.0,Bangalore,KARNATAKA,501102.0,RANGA REDDY,TELANGANA,2026-05-28,1.0,2026-05-28T16:10:08.000+05:30,2026-05-28,2026-05-28,NaN,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4356.00,0.0,5000.0,ZONAL,False,NaN,2026-06-01T03:15:00+0530,PickupHub_FKYWP,CentralHub_L_SGR1,2026-06-01,2026-05-28,SPS,0.0,0.0,5000.0,0.0,NaN,SATELLITEHUB_VKR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,2026-05-28,Open,2026-05-30,2.0

In [13]:
#os.chdir(r"C:\Users\attlakumar.vc\Desktop\Python Data\Large Check File")
m1.to_csv("large_mt_17_Jul.csv",index=False)

In [14]:
import os
import time
import shutil
import glob
from math import ceil
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# ==========================================
# ===             CONFIG                  ===
# ==========================================
csv_path = r"C:\Users\mohammadali1.vc\Desktop\Python data\Large Check File\large_mt_17_Jul.csv"
output_folder = r"C:\Users\mohammadali1.vc\Desktop\Python data\Large Check File\Batch Files"
user_data_dir = r"C:\Users\mohammadali1.vc\Desktop\Python data\Large Check File\SeleniumProfile"
download_dir = r"C:\Users\mohammadali1.vc\Desktop\Python data\Large Check File"
output_dir = r"C:\Users\mohammadali1.vc\Desktop\Python data\Large Check File\Tracking Output"
final_output_path = os.path.join(r"C:\Users\mohammadali1.vc\Desktop\Python data\Large Check File", "Multitrack 17-07-2026.csv")

timeout = 5
BATCH_SIZE = 3000
MIN_FILE_SIZE_KB = 5
MAX_RETRIES = 10

# ==========================================
# === STEP 1: READ AND BATCH TRACKING IDS ===
# ==========================================
print("📦 Initializing data files...")
df = pd.read_csv(csv_path)
tracking_ids = df['tracking_id'].dropna().astype(str).str.strip().tolist()

os.makedirs(output_folder, exist_ok=True)

total_batches = ceil(len(tracking_ids) / BATCH_SIZE)
for i in range(total_batches):
    start = i * BATCH_SIZE
    end = min(start + BATCH_SIZE, len(tracking_ids))
    batch = tracking_ids[start:end]
    batch_df = pd.DataFrame(batch, columns=["tracking_id"])
    batch_filename = f"Batch_{i+1:03}.csv"
    batch_path = os.path.join(output_folder, batch_filename)
    batch_df.to_csv(batch_path, index=False)
    print(f"✅ Saved {batch_filename} with {len(batch)} IDs")

# ==========================================
# ===      STEP 2: SETUP WEBDRIVER       ===
# ==========================================
os.makedirs(output_dir, exist_ok=True)
options = Options()

# Window environment normalization configurations
options.add_argument(f"--user-data-dir={user_data_dir}")
options.add_argument("--profile-directory=Default")
options.add_argument("--start-maximized")
options.add_argument("--no-first-run")
options.add_argument("--no-default-browser-check")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option("useAutomationExtension", False)

prefs = {
    "download.default_directory": download_dir,
    "download.prompt_for_download": False,
    "download.directory_upgrade": True
}
options.add_experimental_option("prefs", prefs)

driver = webdriver.Chrome(options=options)
wait = WebDriverWait(driver, timeout)

# ==========================================
# ===        STEP 3: PORTAL RUN          ===
# ==========================================
driver.get("http://10.24.1.71/hub-ops/tracking/shipments")
time.sleep(3)
try:
    username_input = driver.find_element(By.ID, "username")
    username_input.send_keys(" (Enter you mail ID) @flipkart.com")
    driver.find_element(By.ID, "password").send_keys("  (Enter Your EKL Password) ")
    driver.find_element(By.ID, "loginSubmit").click()
    input("🔐 Complete 2FA manually, then press Enter to continue...")
except:
    print("✅ Already logged in or login not required.")

try:
    wait.until(EC.element_to_be_clickable((By.XPATH, "//div[contains(text(),'Single Shipment Tracking')]"))).click()
    print("✅ Clicked 'Single Shipment Tracking'")
    wait.until(EC.element_to_be_clickable((By.XPATH, "//div[contains(text(),'Multiple Shipment Tracking')]"))).click()
    print("✅ Clicked 'Multiple Shipment Tracking'")
except Exception as e:
    print("❌ Navigation failed:", e)
    driver.quit()
    raise

# --- Web Utility Helpers ---
def get_input_field():
    container = wait.until(EC.presence_of_element_located(
        (By.CSS_SELECTOR, "div[data-testid='selectComponent-shipmentsToBeTracked']")
    ))
    return container.find_element(By.CSS_SELECTOR, "input[id^='react-select-'][type='text']")

def clear_input_field():
    try:
        clear_button = wait.until(EC.element_to_be_clickable(
            (By.XPATH, "//button[contains(@class, 'jNFxRN') and contains(text(), 'Clear')]")
        ))
        clear_button.click()
        time.sleep(1)
        print("🧹 Cleared input field using Clear button")
    except:
        input_field = get_input_field()
        input_field.send_keys(Keys.CONTROL + "a")
        input_field.send_keys(Keys.DELETE)
        print("🧹 Fallback: Cleared input field using keyboard")
        time.sleep(0.5)

def insert_ids_in_batch(ids):
    try:
        input_field = get_input_field()
        ids_string = ",".join(ids)
        
        driver.execute_script("arguments[0].focus();", input_field)
        driver.execute_script("arguments[0].value = '';", input_field)
        
        # Virtual DOM state update implementation
        driver.execute_script("""
            const input = arguments[0];
            const nativeInputValueSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, "value").set;
            nativeInputValueSetter.call(input, arguments[1]);
            
            const event = new Event('input', { bubbles: true });
            input.dispatchEvent(event);
        """, input_field, ids_string)
        
        input_field.send_keys(Keys.ENTER)
        time.sleep(1)
        print(f"⚠️ Inserted {len(ids)} IDs sequentially into portal field.")
        return True
    except Exception as e:
        print(f"❌ Error during insertion: {str(e)}")
        return False

def click_track_button():
    try:
        track_btn = wait.until(EC.element_to_be_clickable((By.XPATH, "//button[contains(text(),'Track')]")))
        driver.execute_script("arguments[0].click();", track_btn)
        print("📥 Clicked 'Track'")
        time.sleep(3)
        wait.until(EC.element_to_be_clickable((By.XPATH, "//button[contains(text(),'Download')]")))
        return True
    except Exception as e:
        print(f"❌ Track click failed: {e}")
        return False

def download_and_verify():
    try:
        before = set(os.listdir(download_dir))
        download_btn = wait.until(EC.element_to_be_clickable((By.XPATH, "//button[contains(text(),'Download')]")))
        driver.execute_script("arguments[0].click();", download_btn)
        print("📁 Clicked 'Download'")
        
        for _ in range(45):
            after = set(os.listdir(download_dir))
            new_files = list(after - before)
            new_files = [f for f in new_files if not f.endswith('.tmp') and not f.endswith('.crdownload')]
            
            if new_files:
                file_path = os.path.join(download_dir, new_files[0])
                time.sleep(2)
                if os.path.exists(file_path) and os.path.getsize(file_path) > MIN_FILE_SIZE_KB * 1024:
                    new_name = f"batch_{time.strftime('%Y%m%d_%H%M%S')}_{new_files[0]}"
                    shutil.move(file_path, os.path.join(output_dir, new_name))
                    print(f"✅ Downloaded and saved as {new_name}")
                    return True
                elif os.path.exists(file_path):
                    os.remove(file_path)
                    print("⚠️ Small or corrupt file cleared")
                    return False
            time.sleep(1)
        print("❌ Download timeout")
        return False
    except Exception as e:
        print(f"❌ Download error: {e}")
        return False

# --- Batch Execution Loop ---
batch_files = sorted([
    f for f in os.listdir(output_folder) 
    if f.startswith("Batch_") and f.endswith(".csv")
])

for file in batch_files:
    print(f"\n🚚 Processing {file}")
    df_batch = pd.read_csv(os.path.join(output_folder, file))
    ids = df_batch['tracking_id'].dropna().astype(str).tolist()

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"🔁 Attempt {attempt} for {file}")
        clear_input_field()
        if insert_ids_in_batch(ids) and click_track_button():
            if download_and_verify():
                break
        if attempt == MAX_RETRIES:
            print(f"❌ Failed to download {file} after {MAX_RETRIES} attempts. Skipping...")

driver.quit()
print("\n🎉 Web Extraction Complete. Beginning Post-Processing Phase...")

# ==========================================
# === STEP 4: MERGE, CLEAN, SORT, DATES  ===
# ==========================================
all_files = glob.glob(os.path.join(output_dir, "batch_*.csv"))

if not all_files:
    print(f"❌ No batch download files found in directory: {output_dir}")
else:
    print(f"🔄 Combining {len(all_files)} files into final spreadsheet...")
    combined_df = pd.concat([pd.read_csv(f) for f in all_files], ignore_index=True)
    
    # Target Column A dynamically (Index position 0) for deduplication
    column_a_name = combined_df.columns[0]
    
    # 1. Deduplication Step
    initial_count = len(combined_df)
    combined_df = combined_df.drop_duplicates(subset=[column_a_name], keep='first')
    dropped_count = initial_count - len(combined_df)
    print(f"🧹 Removed {dropped_count} duplicate rows based on column: '{column_a_name}'.")

    # 2. Sort by Column B dynamically (Index position 1) from A to Z
    column_b_name = combined_df.columns[1]
    print(f"⏳ Sorting rows from A to Z based on column: '{column_b_name}'...")
    combined_df = combined_df.sort_values(by=column_b_name, ascending=True)
    
    # 3. Date Formatting Step on Column K (Index position 10)
    try:
        column_k_name = combined_df.columns[10]  # Column K is index 10
        print(f"📅 Converting date format for Column K ('{column_k_name}') to MM-DD-YYYY...")
        
        # Coerce errors to NaT so missing/blank cells don't crack the processing sequence
        combined_df[column_k_name] = pd.to_datetime(combined_df[column_k_name], errors='coerce')
        
        # Format explicitly to MM-DD-YYYY string formatting structure
        combined_df[column_k_name] = combined_df[column_k_name].dt.strftime('%m-%d-%Y')
        print("✅ Date formatting applied successfully.")
    except Exception as date_err:
        print(f"⚠️ Warning: Could not reformat dates in Column K. Reason: {date_err}")

    # 4. Save Final Clean Consolidated Checkfile Master Report
    combined_df.to_csv(final_output_path, index=False)
    
    print(f"\n🎉 Success! Combined, Deduplicated, Sorted, and Dated.")
    print(f"📊 Final rows count: {len(combined_df)}")
    print(f"📁 Checkfile Master report saved at: {final_output_path}")

📦 Initializing data files...
✅ Saved Batch_001.csv with 3000 IDs
✅ Saved Batch_002.csv with 3000 IDs
✅ Saved Batch_003.csv with 3000 IDs
✅ Saved Batch_004.csv with 3000 IDs
✅ Saved Batch_005.csv with 3000 IDs
✅ Saved Batch_006.csv with 3000 IDs
✅ Saved Batch_007.csv with 3000 IDs
✅ Saved Batch_008.csv with 3000 IDs
✅ Saved Batch_009.csv with 3000 IDs
✅ Saved Batch_010.csv with 3000 IDs
✅ Saved Batch_011.csv with 3000 IDs
✅ Saved Batch_012.csv with 3000 IDs
✅ Saved Batch_013.csv with 3000 IDs
✅ Saved Batch_014.csv with 3000 IDs
✅ Saved Batch_015.csv with 3000 IDs
✅ Saved Batch_016.csv with 3000 IDs
✅ Saved Batch_017.csv with 3000 IDs
✅ Saved Batch_018.csv with 3000 IDs
✅ Saved Batch_019.csv with 3000 IDs
✅ Saved Batch_020.csv with 3000 IDs
✅ Saved Batch_021.csv with 3000 IDs
✅ Saved Batch_022.csv with 3000 IDs
✅ Saved Batch_023.csv with 3000 IDs
✅ Saved Batch_024.csv with 3000 IDs
✅ Saved Batch_025.csv with 3000 IDs
✅ Saved Batch_026.csv with 3000 IDs
✅ Saved Batch_027.csv with 3000 IDs
✅ Saved Batch_028.csv with 3000 IDs
✅ Saved Batch_029.csv with 3000 IDs
✅ Saved Batch_030.csv with 2417 IDs

🔐 Complete 2FA manually, then press Enter to continue...

✅ Clicked 'Single Shipment Tracking'
✅ Clicked 'Multiple Shipment Tracking'

🚚 Processing Batch_001.csv
🔁 Attempt 1 for Batch_001.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_091841_shipments 7_17_2026, 9_18_37 AM.csv

🚚 Processing Batch_002.csv
🔁 Attempt 1 for Batch_002.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
❌ Download timeout
🔁 Attempt 2 for Batch_002.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
❌ Download timeout
🔁 Attempt 3 for Batch_002.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092040_shipments 7_17_2026, 9_20_37 AM.csv

🚚 Processing Batch_003.csv
🔁 Attempt 1 for Batch_003.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
❌ Download timeout
🔁 Attempt 2 for Batch_003.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092146_shipments 7_17_2026, 9_21_43 AM.csv

🚚 Processing Batch_004.csv
🔁 Attempt 1 for Batch_004.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092200_shipments 7_17_2026, 9_21_57 AM.csv

🚚 Processing Batch_005.csv
🔁 Attempt 1 for Batch_005.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092214_shipments 7_17_2026, 9_22_11 AM.csv

🚚 Processing Batch_006.csv
🔁 Attempt 1 for Batch_006.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092229_shipments 7_17_2026, 9_22_26 AM.csv

🚚 Processing Batch_007.csv
🔁 Attempt 1 for Batch_007.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092243_shipments 7_17_2026, 9_22_41 AM.csv

🚚 Processing Batch_008.csv
🔁 Attempt 1 for Batch_008.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092258_shipments 7_17_2026, 9_22_55 AM.csv

🚚 Processing Batch_009.csv
🔁 Attempt 1 for Batch_009.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092312_shipments 7_17_2026, 9_23_09 AM.csv

🚚 Processing Batch_010.csv
🔁 Attempt 1 for Batch_010.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092325_shipments 7_17_2026, 9_23_23 AM.csv

🚚 Processing Batch_011.csv
🔁 Attempt 1 for Batch_011.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092340_shipments 7_17_2026, 9_23_37 AM.csv

🚚 Processing Batch_012.csv
🔁 Attempt 1 for Batch_012.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092354_shipments 7_17_2026, 9_23_52 AM.csv

🚚 Processing Batch_013.csv
🔁 Attempt 1 for Batch_013.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092411_shipments 7_17_2026, 9_24_08 AM.csv

🚚 Processing Batch_014.csv
🔁 Attempt 1 for Batch_014.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092425_shipments 7_17_2026, 9_24_23 AM.csv

🚚 Processing Batch_015.csv
🔁 Attempt 1 for Batch_015.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092439_shipments 7_17_2026, 9_24_36 AM.csv

🚚 Processing Batch_016.csv
🔁 Attempt 1 for Batch_016.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092451_shipments 7_17_2026, 9_24_49 AM.csv

🚚 Processing Batch_017.csv
🔁 Attempt 1 for Batch_017.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092505_shipments 7_17_2026, 9_25_03 AM.csv

🚚 Processing Batch_018.csv
🔁 Attempt 1 for Batch_018.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092520_shipments 7_17_2026, 9_25_17 AM.csv

🚚 Processing Batch_019.csv
🔁 Attempt 1 for Batch_019.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092538_shipments 7_17_2026, 9_25_35 AM.csv

🚚 Processing Batch_020.csv
🔁 Attempt 1 for Batch_020.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092552_shipments 7_17_2026, 9_25_50 AM.csv

🚚 Processing Batch_021.csv
🔁 Attempt 1 for Batch_021.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092609_shipments 7_17_2026, 9_26_06 AM.csv

🚚 Processing Batch_022.csv
🔁 Attempt 1 for Batch_022.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092624_shipments 7_17_2026, 9_26_20 AM.csv

🚚 Processing Batch_023.csv
🔁 Attempt 1 for Batch_023.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092639_shipments 7_17_2026, 9_26_36 AM.csv

🚚 Processing Batch_024.csv
🔁 Attempt 1 for Batch_024.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092656_shipments 7_17_2026, 9_26_54 AM.csv

🚚 Processing Batch_025.csv
🔁 Attempt 1 for Batch_025.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092711_shipments 7_17_2026, 9_27_09 AM.csv

🚚 Processing Batch_026.csv
🔁 Attempt 1 for Batch_026.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_092727_shipments 7_17_2026, 9_27_23 AM.csv

🚚 Processing Batch_027.csv
🔁 Attempt 1 for Batch_027.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
❌ Download timeout
🔁 Attempt 2 for Batch_027.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
❌ Download timeout
🔁 Attempt 3 for Batch_027.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
❌ Download timeout
🔁 Attempt 4 for Batch_027.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_093027_shipments 7_17_2026, 9_30_23 AM.csv

🚚 Processing Batch_028.csv
🔁 Attempt 1 for Batch_028.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_093041_shipments 7_17_2026, 9_30_38 AM.csv

🚚 Processing Batch_029.csv
🔁 Attempt 1 for Batch_029.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 3000 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_093054_shipments 7_17_2026, 9_30_52 AM.csv

🚚 Processing Batch_030.csv
🔁 Attempt 1 for Batch_030.csv
🧹 Cleared input field using Clear button
⚠️ Inserted 2417 IDs sequentially into portal field.
📥 Clicked 'Track'
📁 Clicked 'Download'
✅ Downloaded and saved as batch_20260717_093106_shipments 7_17_2026, 9_31_03 AM.csv

🎉 Web Extraction Complete. Beginning Post-Processing Phase...
🔄 Combining 30 files into final spreadsheet...
🧹 Removed 0 duplicate rows based on column: 'Tracking Id'.
⏳ Sorting rows from A to Z based on column: 'Shipment Type'...
📅 Converting date format for Column K ('Latest Update Time') to MM-DD-YYYY...
✅ Date formatting applied successfully.

🎉 Success! Combined, Deduplicated, Sorted, and Dated.
📊 Final rows count: 89417
📁 Checkfile Master report saved at: C:\Users\mohammadali1.vc\Desktop\Python data\Large Check File\Multitrack 17-07-2026.csv

In [15]:
#os.chdir(r"C:\Users\mohammadali1.vc\Desktop\Python data\Large Check File")
mt1=pd.read_csv("Multitrack 17-07-2026.csv")
mt1 = pd.DataFrame({col.replace(' ', '_'): mt1[col] for col in mt1.columns})
mt1

C:\Users\mohammadali1.vc\AppData\Local\Temp\ipykernel_32248\2034621631.py:2: DtypeWarning: Columns (0: Bag Id, 1: BagStatus, 2: Logistics Promise Date, 3: Refund Status, 4: Vendor) have mixed types. Specify dtype option on import or set low_memory=False.
  mt1=pd.read_csv("Multitrack 17-07-2026.csv")

,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor
0,AWPC0000083704,NORMAL_FORWARD,REGULAR,NaN,COD,6768.00,854101.0,Undelivered_No_Response,Satellitehub_Naugachia,Satellitehub_Naugachia,07-09-2026,CentralHub_KNL1,2026-05-29 17:20:20,Updated by CRON,DELIVERY_DATE_CHANGED: 16-Jun-2026,4.0,NaN,NaN,2026-06-16 23:59:59,2026-06-08 04:15:00,NaN,NaN,Satellitehub_Naugachia,2026-06-04 06:55:51,ORD-SO-731125,NaN,NaN,NaN,NaN
1,EMHP0000203602,NORMAL_FORWARD,REGULAR,NaN,PP,5949.15,671541.0,Undelivered_Not_Attended,SATELLITEHUB_KSGD,CentralHub_L_CJB3,07-16-2026,CentralHub_CBE,2026-07-16 15:36:27,NaN,NaN,0.0,NaN,NaN,2026-07-22 23:59:59,2026-07-22 03:15:00,NaN,NaN,SATELLITEHUB_KSGD,2026-07-16 23:54:27,671570,NaN,NaN,NaN,NaN
2,EMHP0000215172,NORMAL_FORWARD,REGULAR,NaN,PP,14499.00,609604.0,Out_For_Delivery,SATELLITEHUB_FKKRKL,SATELLITEHUB_FKKRKL,07-17-2026,CentralHub_CBE,2026-07-14 15:07:36,NaN,NaN,1.0,NaN,NaN,2026-07-20 23:59:59,2026-07-20 03:15:00,NaN,NaN,SATELLITEHUB_FKKRKL,2026-07-16 12:12:52,669543,NaN,NaN,NaN,NaN
3,EMHP0000214832,NORMAL_FORWARD,REGULAR,NaN,PP,17509.15,686004.0,Undelivered_Not_Attended,SATELLITEHUB_KTY1,SATELLITEHUB_KTY1,07-16-2026,CentralHub_CBE,2026-07-14 14:44:10,NaN,NaN,0.0,NaN,NaN,2026-07-19 23:59:59,2026-07-19 03:15:00,NaN,NaN,SATELLITEHUB_KTY1,2026-07-16 11:36:21,669574,NaN,NaN,NaN,NaN
4,EMHP0000228589,NORMAL_FORWARD,REGULAR,NaN,PP,10169.10,600097.0,Out_For_Delivery,SATELLITEHUB_FKTMB2,SATELLITEHUB_FKTMB2,07-17-2026,CentralHub_CBE,2026-07-13 14:53:48,NaN,NaN,1.0,NaN,NaN,2026-07-19 23:59:59,2026-07-19 03:15:00,NaN,NaN,SATELLITEHUB_FKTMB2,2026-07-17 06:31:32,669206,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89412,FLOR0000035396,Shipment not found in CL systems!!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89413,FLOR0000039644,Shipment not found in CL systems!!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89414,FLOR0000037592,Shipment not found in CL systems!!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89415,INWR0000104218,Shipment not found in CL systems!!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89416,FLOR0000038646,Shipment not found in CL systems!!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
merge2 = pd.merge(left=d91,right=mt1,left_on='tracking_id',right_on='Tracking_Id',how='left')
merge2

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,first_ph_in_post_rto_hub_name,first_ph_in_post_rto_datetime,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor
0,TFC001512055,NaN,AMAP0000000577,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-06-15,ShipmentDelivered,110086.0,Delhi,DELHI,560068.0,BANGALORE,KARNATAKA,2026-06-10,1.0,2026-06-10T10:27:23.000+05:30,2026-06-10,2026-06-10,2026-06-15T05:01:43.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T14:44:54.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5510.25,0.0,19000.0,METRO,False,NaN,2026-06-15T03:15:00+0530,PICKUPHUB_RPBAGHFM,BulkHub_BLR,2026-06-15,2026-06-10,SPS,120.0,25.0,19000.0,25.0,BulkHub_BLR,BulkHub_BLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-10,delivered,2026-06-15,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TFC001512213,NaN,AMAP0000000819,FSD_LARGE,AMA,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-07-05,ShipmentDelivered,110086.0,Delhi,DELHI,580023.0,DHARWAD,KARNATAKA,2026-06-30,1.0,2026-06-30T11:08:46.000+05:30,2026-06-30,2026-06-30,2026-07-05T05:25:29.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T18:00:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5628.75,0.0,13000.0,ROI,False,NaN,2026-07-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_FKHBLA,2026-07-05,2026-06-30,SPS,110.0,20.0,13000.0,20.0,SATELLITEHUB_FKHBLA,SATELLITEHUB_FKHBLA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-30,delivered,2026-07-05,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,940069,NaN,ARLP0000003366,FSD_LARGE,ARL,SINGER COOKMATE 5L,SINGER COOKMATE 5L,ext_sps,ARL,ARL : ARL_THA_01,ARL_448c561fc19f951b85377ebb5382e9af,Forward,SHIPMENT,PP,N,True,2026-06-12,ShipmentDelivered,401105.0,Thane,MAHARASHTRA,800007.0,PATNA,BIHAR,2026-06-03,1.0,2026-06-03T17:30:54.000+05:30,2026-06-04,2026-06-04,2026-06-12T05:01:52.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T18:26:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2784.00,0.0,2600.0,ROI,False,NaN,2026-06-13T03:15:00+0530,Pickuphub_FKMIB,SatelliteHub_PAT,2026-06-13,2026-06-04,SPS,45.0,20.0,2600.0,25.0,SatelliteHub_PAT,SatelliteHub_PAT,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-04,delivered,2026-06-12,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ORD-SO-813176,NaN,AWPC0000077622,FSD_LARGE,AWP,Hymatic Single Battery 12X8 16 Ltr Battery Ope...,ATE3A59AE91CK26A71A05,ext_sps,AWP,AWP : Patna WH,AWP_06690e9940963d92d58bcb3a6563d29c,Forward,SHIPMENT,COD,Z,True,2026-07-11,ShipmentDelivered,803201.0,Patna,BIHAR,851213.0,KHAGARIA,BIHAR,2026-07-08,1.0,2026-07-08T11:39:46.000+05:30,2026-07-08,2026-07-08,2026-07-11T07:45:01.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T22:05:14.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4874.00,3874.0,24450.0,ZONAL,False,NaN,2026-07-14T03:15:00+0530,PickupHub_PAT,SATELLITEHUB_KGG,2026-07-14,2026-07-08,SPS,64.0,49.0,24450.0,39.0,SATELLITEHUB_KGG,SATELLITEHUB_KGG,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-08,delivered,2026-07-11,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ORD-SO-796826,NaN,AWPC0000078604,FSD_LARGE,AWP,BALWAAN DOUBLE BATTERY-DOUBLE MOTOR BS-22D 12X...,ATE3A59AB38GD97A63A05,ext_sps,AWP,AWP : Rohit Bajaj,AWP_85296f55bcc56dc187a14f2f9c6e8299,Forward,SHIPMENT,COD,Z,True,2026-07-08,ShipmentDelivered,711302.0,Howrah,WEST BENGAL,848201.0,BEGUSARAI,BIHAR,2026-07-01,4.0,2026-07-01T10:03:33.000+05:30,2026-07-04,2026-07-04,2026-07-08T06:33:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T22:24:37.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,7370.00,6870.0,29172.0,ZONAL,False,NaN,2026-07-11T03:15:00+0530,PickupHub_FKHWH,Satellitehub_FKBEGU,2026-07-11,2026-07-04,SPS,64.0,53.0,29172.0,43.0,Satellitehub_FKBEGU,Satellitehub_FKBEGU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-04,delivered,2026-07-08,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921759,XPYE2ETDDR8JIQTK,NaN,UNCP0000314145,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,302021.0,JAIPUR,RAJASTHAN,2026-04-10,4.0,2026-04-10T14:36:16.000+05:30,2026-04-13,2026-04-13,2026-04-18T02:09:37.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T15:45:26.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JAI,2026-04-19,2026-04-13,SPS,30.0,8.0,3480.0,21.0,SatelliteHub_JAI,SatelliteHub_JAI,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
921760,CP66PCOX4L,NaN,UNCP0000314813,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-01,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,274301.0,DEORIA,UTTAR PRADESH,2026-04-14,3.0,2026-04-14T17:45:18.000+05:30,2026-04-17,2026-04-17,2026-04-30T23:56:26.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T21:43:49.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-28T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_KUSHINAGAR,2026-04-28,2026-04-17,SPS,20.0,19.0,6640.0,26.0,SATELLITEHUB_KUSHINAGAR,SATELLITEHUB_KUSHINAGAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-01,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
921761,E5VOT73QQV,NaN,UNCP0000314816,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-07,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,805110.0,NAWADA,BIHAR,2026-04-14,3.0,2026-04-14T17:45:24.000+05:30,2026-04-17,2026-04-17,2026-05-07T06:00:49.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T18:25:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-26T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_FKNWD,2026-04-26,2026-04-17,SPS,20.0,19.0,6640.0,26.0,Satellitehub_FKNWD,Satellitehub_FKNWD,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-07,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
921762,5XYZFK5V3Y0NOT0N,NaN,UNCP0000314002,FSD_LARGE,UNC,GATE ELECTRICAL,GATE ELECTRICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,382330.0,AHMEDABAD,GUJARAT,2026-04-10,4.0,2026-04-10T14:36:17.000+05:30,2026-04-13,2026-04-13,2026-04-18T07:53:46.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T23:10:07.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,5710.0,METRO,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_NAR,2026-04-19,2026-04-13,SPS,19.0,18.0,5710.0,25.0,SatelliteHub_NAR,SatelliteHub_NAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
921763,WETER7WN993JO9OG,NaN,UNCP0000314142,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-19,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,752001.0,PURI,ODISHA,2026-04-10,4.0,2026-04-10T14:36:18.000+05:30,2026-04-13,2026-04-13,2026-04-19T04:27:51.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T18:09:19.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-20T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_FKPUR,2026-04-20,2026-04-13,SPS,30.0,8.0,3480.0,21.0,Satellitehub_FKPUR,Satellitehub_FKPUR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-19,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
print(merge2['Current_Location'].isnull().sum())

848894

In [18]:
merge2['Latest_Update_Time'] = pd.to_datetime(merge2['Latest_Update_Time']).dt.date
merge2['end_date'] = pd.to_datetime(merge2['end_date']).dt.date
merge2['end_date']=np.where((merge2['Shipment_Type'].isin(['NORMAL_FORWARD'])),merge2.Latest_Update_Time,
                            np.where((merge2['Shipment_Type'].isin(['Shipment not found in CL systems!!'])),merge2.last_updated_at,merge2.end_date))

In [19]:
conditions = [
    (merge2['Latest_Status'] == 'Delivered') & (merge2['Cs_Notes'] == 'Marked_As_RTO'),
(merge2['Latest_Status'] == 'Delivered'),
(merge2['Latest_Status'] == 'Delivery_Update'),    
(merge2['Latest_Status'] == 'returned_to_seller'),
(merge2['Latest_Status'] == 'Rejected_By_Seller'),
(merge2['Latest_Status'] == 'Lost'),
(merge2['Shipment_Type']=='Shipment not found in CL systems!!')]
choices = ["Returned_to_seller","delivered","delivered","returned_to_seller","rejected_by_seller","lost","closed<45"]
merge2['ERP_Status'] = np.select(conditions,choices, default="Open")
merge2.ERP_Status.value_counts()

ERP_Status
Open                  893295
closed<45              16547
delivered              11158
rejected_by_seller       696
Returned_to_seller        60
lost                       8
Name: count, dtype: int64

In [20]:
merge2['Final_Status'] = np.where((merge2['FDP_status'] == "Open"),merge2.ERP_Status, merge2.FDP_status)
merge2['Final_Status'] = np.where((merge2['ERP_Status'] == "lost"), "Lost", merge2['Final_Status'])
merge2['Final_Status'] = np.where((merge2['ERP_Status'] == "Returned_to_seller"), "Returned_to_seller", merge2['Final_Status'])
merge2['Final_Status'] = np.where((merge2['ERP_Status'] == "delivered"), "delivered", merge2['Final_Status'])
merge2.Final_Status.value_counts()

Final_Status
delivered             785163
Returned_to_seller     58402
Open                   53359
closed<45              16469
Open-RTO                8273
rejected_by_seller        90
Lost                       8
Name: count, dtype: int64

In [21]:
merge2['Final_Status'] = np.where((merge2['Final_Status'] == "Open") & (merge2['Cs_Notes'] == 'Marked_As_RTO'),"Open-RTO", merge2.Final_Status)
merge2.Final_Status.value_counts()

Final_Status
delivered             785163
Returned_to_seller     58402
Open                   52817
closed<45              16469
Open-RTO                8815
rejected_by_seller        90
Lost                       8
Name: count, dtype: int64

In [22]:
merge2.loc[merge2['Final_Status'].isin(['Open','Open-RTO']),'end_date'] = '2026-07-17'
merge2

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,first_ph_in_post_rto_hub_name,first_ph_in_post_rto_datetime,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor,ERP_Status,Final_Status
0,TFC001512055,NaN,AMAP0000000577,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-06-15,ShipmentDelivered,110086.0,Delhi,DELHI,560068.0,BANGALORE,KARNATAKA,2026-06-10,1.0,2026-06-10T10:27:23.000+05:30,2026-06-10,2026-06-10,2026-06-15T05:01:43.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T14:44:54.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5510.25,0.0,19000.0,METRO,False,NaN,2026-06-15T03:15:00+0530,PICKUPHUB_RPBAGHFM,BulkHub_BLR,2026-06-15,2026-06-10,SPS,120.0,25.0,19000.0,25.0,BulkHub_BLR,BulkHub_BLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-10,delivered,2026-06-15,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered
1,TFC001512213,NaN,AMAP0000000819,FSD_LARGE,AMA,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-07-05,ShipmentDelivered,110086.0,Delhi,DELHI,580023.0,DHARWAD,KARNATAKA,2026-06-30,1.0,2026-06-30T11:08:46.000+05:30,2026-06-30,2026-06-30,2026-07-05T05:25:29.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T18:00:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5628.75,0.0,13000.0,ROI,False,NaN,2026-07-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_FKHBLA,2026-07-05,2026-06-30,SPS,110.0,20.0,13000.0,20.0,SATELLITEHUB_FKHBLA,SATELLITEHUB_FKHBLA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-30,delivered,2026-07-05,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered
2,940069,NaN,ARLP0000003366,FSD_LARGE,ARL,SINGER COOKMATE 5L,SINGER COOKMATE 5L,ext_sps,ARL,ARL : ARL_THA_01,ARL_448c561fc19f951b85377ebb5382e9af,Forward,SHIPMENT,PP,N,True,2026-06-12,ShipmentDelivered,401105.0,Thane,MAHARASHTRA,800007.0,PATNA,BIHAR,2026-06-03,1.0,2026-06-03T17:30:54.000+05:30,2026-06-04,2026-06-04,2026-06-12T05:01:52.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T18:26:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2784.00,0.0,2600.0,ROI,False,NaN,2026-06-13T03:15:00+0530,Pickuphub_FKMIB,SatelliteHub_PAT,2026-06-13,2026-06-04,SPS,45.0,20.0,2600.0,25.0,SatelliteHub_PAT,SatelliteHub_PAT,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-04,delivered,2026-06-12,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered
3,ORD-SO-813176,NaN,AWPC0000077622,FSD_LARGE,AWP,Hymatic Single Battery 12X8 16 Ltr Battery Ope...,ATE3A59AE91CK26A71A05,ext_sps,AWP,AWP : Patna WH,AWP_06690e9940963d92d58bcb3a6563d29c,Forward,SHIPMENT,COD,Z,True,2026-07-11,ShipmentDelivered,803201.0,Patna,BIHAR,851213.0,KHAGARIA,BIHAR,2026-07-08,1.0,2026-07-08T11:39:46.000+05:30,2026-07-08,2026-07-08,2026-07-11T07:45:01.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T22:05:14.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4874.00,3874.0,24450.0,ZONAL,False,NaN,2026-07-14T03:15:00+0530,PickupHub_PAT,SATELLITEHUB_KGG,2026-07-14,2026-07-08,SPS,64.0,49.0,24450.0,39.0,SATELLITEHUB_KGG,SATELLITEHUB_KGG,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-08,delivered,2026-07-11,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered
4,ORD-SO-796826,NaN,AWPC0000078604,FSD_LARGE,AWP,BALWAAN DOUBLE BATTERY-DOUBLE MOTOR BS-22D 12X...,ATE3A59AB38GD97A63A05,ext_sps,AWP,AWP : Rohit Bajaj,AWP_85296f55bcc56dc187a14f2f9c6e8299,Forward,SHIPMENT,COD,Z,True,2026-07-08,ShipmentDelivered,711302.0,Howrah,WEST BENGAL,848201.0,BEGUSARAI,BIHAR,2026-07-01,4.0,2026-07-01T10:03:33.000+05:30,2026-07-04,2026-07-04,2026-07-08T06:33:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T22:24:37.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,7370.00,6870.0,29172.0,ZONAL,False,NaN,2026-07-11T03:15:00+0530,PickupHub_FKHWH,Satellitehub_FKBEGU,2026-07-11,2026-07-04,SPS,64.0,53.0,29172.0,43.0,Satellitehub_FKBEGU,Satellitehub_FKBEGU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-04,delivered,2026-07-08,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921759,XPYE2ETDDR8JIQTK,NaN,UNCP0000314145,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,302021.0,JAIPUR,RAJASTHAN,2026-04-10,4.0,2026-04-10T14:36:16.000+05:30,2026-04-13,2026-04-13,2026-04-18T02:09:37.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T15:45:26.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JAI,2026-04-19,2026-04-13,SPS,30.0,8.0,3480.0,21.0,SatelliteHub_JAI,SatelliteHub_JAI,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered
921760,CP66PCOX4L,NaN,UNCP0000314813,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-01,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,274301.0,DEORIA,UTTAR PRADESH,2026-04-14,3.0,2026-04-14T17:45:18.000+05:30,2026-04-17,2026-04-17,2026-04-30T23:56:26.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T21:43:49.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-28T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_KUSHINAGAR,2026-04-28,2026-04-17,SPS,20.0,19.0,6640.0,26.0,SATELLITEHUB_KUSHINAGAR,SATELLITEHUB_KUSHINAGAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-01,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered
921761,E5VOT73QQV,NaN,UNCP0000314816,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-07,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,805110.0,NAWADA,BIHAR,2026-04-14,3.0,2026-04-14T17:45:24.000+05:30,2026-04-17,2026-04-17,2026-05-07T06:00:49.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T18:25:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-26T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_FKNWD,2026-04-26,2026-04-17,SPS,20.0,19.0,6640.0,26.0,Satellitehub_FKNWD,Satellitehub_FKNWD,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-07,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered
921762,5XYZFK5V3Y0NOT0N,NaN,UNCP0000314002,FSD_LARGE,UNC,GATE ELECTRICAL,GATE ELECTRICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,382330.0,AHMEDABAD,GUJARAT,2026-04-10,4.0,2026-04-10T14:36:17.000+05:30,2026-04-13,2026-04-13,2026-04-18T07:53:46.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T23:10:07.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,5710.0,METRO,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_NAR,2026-04-19,2026-04-13,SPS,19.0,18.0,5710.0,25.0,SatelliteHub_NAR,SatelliteHub_NAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered
921763,WETER7WN993JO9OG,NaN,UNCP0000314142,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-19,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,752001.0,PURI,ODISHA,2026-04-10,4.0,2026-04-10T14:36:18.000+05:30,2026-04-13,2026-04-13,2026-04-19T04:27:51.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T18:09:19.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-20T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_FKPUR,2026-04-20,2026-04-13,SPS,30.0,8.0,3480.0,21.0,Satellitehub_FKPUR,Satellitehub_FKPUR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-19,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered

In [23]:
#os.chdir(r"C:\Users\mohammadali1.vc\Desktop\Python data\Large Check File")
disputes=pd.read_csv("Dispute_Check.csv")
disputes1 = disputes.rename(columns={'AWB (TID) Number': 'AWB_TID_number'})
#disputes1 = disputes[['Timestamp','AWB_TID_number','Issue_Category','Proof','Email_Address','Case_type','Reason_for_Re-opening_the_case',
#                     'Seller_Name','Shipment_Type','Remarks/_Proof_Link','Client','Aging','Ageing_Bucket','Status','Reason','Acknowledgement_to_client_(Mail_Subject)',
#                    'Mail_Acknowledge_Date','Closed_By','Relabeling_Done','Ekart_Flyer','Cello_Taping_(Y/N)','Cello_Taping_(Body/_Mouth)',
#                    'Smartcheck_Remark','Product_Received','Description',
#                    'DH-PH_Mapping','PH_or_DH']]
disputes1

C:\Users\mohammadali1.vc\AppData\Local\Temp\ipykernel_32248\4060656932.py:2: DtypeWarning: Columns (0: Reason, 1: PH_or_DH) have mixed types. Specify dtype option on import or set low_memory=False.
  disputes=pd.read_csv("Dispute_Check.csv")

,Unnamed: 0,Timestamp,AWB_TID_number,Issue_Category,Status,Reason,PH_or_DH,Seller_type,Payment_Mode
0,0,2025-01-01,SOLC0000044625,Wrong Product,dispute not accepted,Beyond On TAT,NaN,SOL,COD
1,3,2025-01-01,SOLN9900002638,Partial Product Received,dispute not accepted,MPS Shipment,NaN,SOL,NaN
2,4,2025-01-01,SOLC0000045141,Wrong Product,dispute not accepted,Beyond On TAT,NaN,SOL,COD
3,6,2025-01-01,SOLC0000039522,Partial Product Received,dispute not accepted,Intacted Condition,NaN,SOL,COD
4,7,2025-01-01,SOLN9900011022,Partial Product Received,dispute not accepted,MPS Shipment,NaN,SOL,NaN
...,...,...,...,...,...,...,...,...,...
983215,2727471,2026-07-11,AWPC0000084365,RTO POD,open,NaN,NaN,AWP,COD
983216,2727472,2026-07-11,AWPC0000082759,RTO POD,open,NaN,NaN,AWP,COD
983217,2727473,2026-07-13,AWPC0001079525,RTO POD,open,NaN,NaN,AWP,COD
983218,2727474,2026-07-13,AWPC0001079524,RTO POD,open,NaN,NaN,AWP,COD
983219,2727475,2026-07-13,BGHP1005507625,RTO POD,open,NaN,NaN,BGH,Prepaid

In [24]:
mg1=merge2.merge(disputes1,left_on='tracking_id',right_on='AWB_TID_number',how='left')
mg1

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,first_ph_in_post_rto_hub_name,first_ph_in_post_rto_datetime,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor,ERP_Status,Final_Status,Unnamed: 0,Timestamp,AWB_TID_number,Issue_Category,Status,Reason,PH_or_DH,Seller_type,Payment_Mode
0,TFC001512055,NaN,AMAP0000000577,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-06-15,ShipmentDelivered,110086.0,Delhi,DELHI,560068.0,BANGALORE,KARNATAKA,2026-06-10,1.0,2026-06-10T10:27:23.000+05:30,2026-06-10,2026-06-10,2026-06-15T05:01:43.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T14:44:54.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5510.25,0.0,19000.0,METRO,False,NaN,2026-06-15T03:15:00+0530,PICKUPHUB_RPBAGHFM,BulkHub_BLR,2026-06-15,2026-06-10,SPS,120.0,25.0,19000.0,25.0,BulkHub_BLR,BulkHub_BLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-10,delivered,2026-06-15,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TFC001512213,NaN,AMAP0000000819,FSD_LARGE,AMA,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-07-05,ShipmentDelivered,110086.0,Delhi,DELHI,580023.0,DHARWAD,KARNATAKA,2026-06-30,1.0,2026-06-30T11:08:46.000+05:30,2026-06-30,2026-06-30,2026-07-05T05:25:29.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T18:00:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5628.75,0.0,13000.0,ROI,False,NaN,2026-07-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_FKHBLA,2026-07-05,2026-06-30,SPS,110.0,20.0,13000.0,20.0,SATELLITEHUB_FKHBLA,SATELLITEHUB_FKHBLA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-30,delivered,2026-07-05,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,940069,NaN,ARLP0000003366,FSD_LARGE,ARL,SINGER COOKMATE 5L,SINGER COOKMATE 5L,ext_sps,ARL,ARL : ARL_THA_01,ARL_448c561fc19f951b85377ebb5382e9af,Forward,SHIPMENT,PP,N,True,2026-06-12,ShipmentDelivered,401105.0,Thane,MAHARASHTRA,800007.0,PATNA,BIHAR,2026-06-03,1.0,2026-06-03T17:30:54.000+05:30,2026-06-04,2026-06-04,2026-06-12T05:01:52.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T18:26:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2784.00,0.0,2600.0,ROI,False,NaN,2026-06-13T03:15:00+0530,Pickuphub_FKMIB,SatelliteHub_PAT,2026-06-13,2026-06-04,SPS,45.0,20.0,2600.0,25.0,SatelliteHub_PAT,SatelliteHub_PAT,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-04,delivered,2026-06-12,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ORD-SO-813176,NaN,AWPC0000077622,FSD_LARGE,AWP,Hymatic Single Battery 12X8 16 Ltr Battery Ope...,ATE3A59AE91CK26A71A05,ext_sps,AWP,AWP : Patna WH,AWP_06690e9940963d92d58bcb3a6563d29c,Forward,SHIPMENT,COD,Z,True,2026-07-11,ShipmentDelivered,803201.0,Patna,BIHAR,851213.0,KHAGARIA,BIHAR,2026-07-08,1.0,2026-07-08T11:39:46.000+05:30,2026-07-08,2026-07-08,2026-07-11T07:45:01.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T22:05:14.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4874.00,3874.0,24450.0,ZONAL,False,NaN,2026-07-14T03:15:00+0530,PickupHub_PAT,SATELLITEHUB_KGG,2026-07-14,2026-07-08,SPS,64.0,49.0,24450.0,39.0,SATELLITEHUB_KGG,SATELLITEHUB_KGG,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-08,delivered,2026-07-11,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ORD-SO-796826,NaN,AWPC0000078604,FSD_LARGE,AWP,BALWAAN DOUBLE BATTERY-DOUBLE MOTOR BS-22D 12X...,ATE3A59AB38GD97A63A05,ext_sps,AWP,AWP : Rohit Bajaj,AWP_85296f55bcc56dc187a14f2f9c6e8299,Forward,SHIPMENT,COD,Z,True,2026-07-08,ShipmentDelivered,711302.0,Howrah,WEST BENGAL,848201.0,BEGUSARAI,BIHAR,2026-07-01,4.0,2026-07-01T10:03:33.000+05:30,2026-07-04,2026-07-04,2026-07-08T06:33:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T22:24:37.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,7370.00,6870.0,29172.0,ZONAL,False,NaN,2026-07-11T03:15:00+0530,PickupHub_FKHWH,Satellitehub_FKBEGU,2026-07-11,2026-07-04,SPS,64.0,53.0,29172.0,43.0,Satellitehub_FKBEGU,Satellitehub_FKBEGU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-04,delivered,2026-07-08,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921759,XPYE2ETDDR8JIQTK,NaN,UNCP0000314145,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,302021.0,JAIPUR,RAJASTHAN,2026-04-10,4.0,2026-04-10T14:36:16.000+05:30,2026-04-13,2026-04-13,2026-04-18T02:09:37.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T15:45:26.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JAI,2026-04-19,2026-04-13,SPS,30.0,8.0,3480.0,21.0,SatelliteHub_JAI,SatelliteHub_JAI,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
921760,CP66PCOX4L,NaN,UNCP0000314813,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-01,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,274301.0,DEORIA,UTTAR PRADESH,2026-04-14,3.0,2026-04-14T17:45:18.000+05:30,2026-04-17,2026-04-17,2026-04-30T23:56:26.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T21:43:49.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-28T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_KUSHINAGAR,2026-04-28,2026-04-17,SPS,20.0,19.0,6640.0,26.0,SATELLITEHUB_KUSHINAGAR,SATELLITEHUB_KUSHINAGAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-01,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
921761,E5VOT73QQV,NaN,UNCP0000314816,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-07,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,805110.0,NAWADA,BIHAR,2026-04-14,3.0,2026-04-14T17:45:24.000+05:30,2026-04-17,2026-04-17,2026-05-07T06:00:49.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T18:25:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-26T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_FKNWD,2026-04-26,2026-04-17,SPS,20.0,19.0,6640.0,26.0,Satellitehub_FKNWD,Satellitehub_FKNWD,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-07,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
921762,5XYZFK5V3Y0NOT0N,NaN,UNCP0000314002,FSD_LARGE,UNC,GATE ELECTRICAL,GATE ELECTRICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,382330.0,AHMEDABAD,GUJARAT,2026-04-10,4.0,2026-04-10T14:36:17.000+05:30,2026-04-13,2026-04-13,2026-04-18T07:53:46.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T23:10:07.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,5710.0,METRO,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_NAR,2026-04-19,2026-04-13,SPS,19.0,18.0,5710.0,25.0,SatelliteHub_NAR,SatelliteHub_NAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
921763,WETER7WN993JO9OG,NaN,UNCP0000314142,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-19,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,752001.0,PURI,ODISHA,2026-04-10,4.0,2026-04-10T14:36:18.000+05:30,2026-04-13,2026-04-13,2026-04-19T04:27:51.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T18:09:19.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-20T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_FKPUR,2026-04-20,2026-04-13,SPS,30.0,8.0,3480.0,21.0,Satellitehub_FKPUR,Satellitehub_FKPUR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-19,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
mg1['Final_Status'] = mg1['Final_Status'].replace({'closed<45': 'delivered'})
mg1.Final_Status.value_counts()

Final_Status
delivered             801632
Returned_to_seller     58402
Open                   52817
Open-RTO                8815
rejected_by_seller        90
Lost                       8
Name: count, dtype: int64

In [26]:
#os.chdir(r"C:\Users\mohammadali1.vc\Desktop\Python data\Large Check File")
v1=pd.read_excel("Rev 16May.xlsx")
drf=mg1.merge(v1,left_on='merchant_code',right_on='Customer Code',how='left')
p1=drf['shipment_value_1'].isnull().sum()
print(p1)

800833

In [27]:
drf['shipment_value_1']=drf['shipment_value_1'].fillna(630)
drf['shipment_value_1'].isnull().sum()

np.int64(0)

In [28]:
#drf=mg1.copy()

In [29]:
from datetime import datetime
drf['dispatch_date'] = pd.to_datetime(drf['dispatch_date']).dt.date

#drf['dispatch_date'] = drf['dispatch_date'].apply(lambda x: pd.to_datetime(x, format="%Y-%m-%d %H:%M:%S").date() if len(str(x)) > 10 else pd.to_datetime(x, format="%Y-%m-%d").date() if isinstance(x, str) else pd.NaT)
drf['todays_date']=datetime.today().strftime('%Y-%m-%d')
#drf['todays_date']="2023-11-17"

ageing_days=(pd.to_datetime(drf['todays_date']) - pd.to_datetime(drf['dispatch_date'])).dt.days
drf["ageing_1"]=ageing_days

In [30]:
def calculate_ageing_days(ageing):
    
    if ageing <= 45:
        return '<=45'
    elif ageing > 45:
        return '>45'
    else:
        return '0'

drf['Ageing_bucket'] = drf['ageing_1'].apply(calculate_ageing_days)

drf=drf.drop(drf[drf['tracking_id']=="END_OF_FILE"].index)

drf.Ageing_bucket.value_counts()

Ageing_bucket
>45     508579
<=45    413185
Name: count, dtype: int64

In [31]:
drf['loss'] = np.where(
    drf['Status'].isin(['dispute accepted', 'partial dispute accepted', 'open']),'conditional_Loss',
    np.where((drf['Final_Status'] == 'Returned_to_seller') & (drf['ageing'].between(45,60)),'RTS>45_60',
         np.where((drf['Final_Status']=='Returned_to_seller') & (drf['ageing']>60),'RTS>60',
            np.where(drf['Final_Status'].isin(['Lost']),'Lost',
                np.where((drf['Final_Status'] == 'Open'),'Open',
                    np.where((drf['Final_Status'] == 'Rejected_By_Seller'),'Rejected_By_Seller',
                        np.where((drf['ageing_1']<=45) & (drf['Final_Status'] == 'Open-RTO'),'<=45_Open-RTO',
                            np.where((drf['ageing_1'].between(46,60)) & (drf['Final_Status'] == 'Open-RTO'),'>45_60-open_RTO',
                            np.where((drf['ageing_1']>60) & (drf['Final_Status'] == 'Open-RTO'),'>60-open_RTO'
                                ,'Null')))))))))

drf.loss.value_counts()

loss
Null                859143
Open                 52817
<=45_Open-RTO         6615
>60-open_RTO          1319
>45_60-open_RTO        874
RTS>45_60              467
conditional_Loss       466
RTS>60                  55
Lost                     8
Name: count, dtype: int64

In [32]:
drf["global_tracking_id"] = (drf["global_tracking_id"].astype(str).str.strip().replace(["", "nan", "None"], np.nan))
drf["child_count"] = drf.groupby("global_tracking_id")["tracking_id"].transform("count")
drf["child_count"] = drf["child_count"].fillna(1).astype(int)
drf

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,first_ph_in_post_rto_hub_name,first_ph_in_post_rto_datetime,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor,ERP_Status,Final_Status,Unnamed: 0,Timestamp,AWB_TID_number,Issue_Category,Status,Reason,PH_or_DH,Seller_type,Payment_Mode,Customer Code,shipment_value_1,todays_date,ageing_1,Ageing_bucket,loss,child_count
0,TFC001512055,NaN,AMAP0000000577,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-06-15,ShipmentDelivered,110086.0,Delhi,DELHI,560068.0,BANGALORE,KARNATAKA,2026-06-10,1.0,2026-06-10,2026-06-10,2026-06-10,2026-06-15T05:01:43.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T14:44:54.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5510.25,0.0,19000.0,METRO,False,NaN,2026-06-15T03:15:00+0530,PICKUPHUB_RPBAGHFM,BulkHub_BLR,2026-06-15,2026-06-10,SPS,120.0,25.0,19000.0,25.0,BulkHub_BLR,BulkHub_BLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-10,delivered,2026-06-15,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,37,<=45,Null,1
1,TFC001512213,NaN,AMAP0000000819,FSD_LARGE,AMA,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-07-05,ShipmentDelivered,110086.0,Delhi,DELHI,580023.0,DHARWAD,KARNATAKA,2026-06-30,1.0,2026-06-30,2026-06-30,2026-06-30,2026-07-05T05:25:29.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T18:00:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5628.75,0.0,13000.0,ROI,False,NaN,2026-07-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_FKHBLA,2026-07-05,2026-06-30,SPS,110.0,20.0,13000.0,20.0,SATELLITEHUB_FKHBLA,SATELLITEHUB_FKHBLA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-30,delivered,2026-07-05,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,17,<=45,Null,1
2,940069,NaN,ARLP0000003366,FSD_LARGE,ARL,SINGER COOKMATE 5L,SINGER COOKMATE 5L,ext_sps,ARL,ARL : ARL_THA_01,ARL_448c561fc19f951b85377ebb5382e9af,Forward,SHIPMENT,PP,N,True,2026-06-12,ShipmentDelivered,401105.0,Thane,MAHARASHTRA,800007.0,PATNA,BIHAR,2026-06-03,1.0,2026-06-03,2026-06-04,2026-06-04,2026-06-12T05:01:52.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T18:26:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2784.00,0.0,2600.0,ROI,False,NaN,2026-06-13T03:15:00+0530,Pickuphub_FKMIB,SatelliteHub_PAT,2026-06-13,2026-06-04,SPS,45.0,20.0,2600.0,25.0,SatelliteHub_PAT,SatelliteHub_PAT,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-04,delivered,2026-06-12,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,44,<=45,Null,1
3,ORD-SO-813176,NaN,AWPC0000077622,FSD_LARGE,AWP,Hymatic Single Battery 12X8 16 Ltr Battery Ope...,ATE3A59AE91CK26A71A05,ext_sps,AWP,AWP : Patna WH,AWP_06690e9940963d92d58bcb3a6563d29c,Forward,SHIPMENT,COD,Z,True,2026-07-11,ShipmentDelivered,803201.0,Patna,BIHAR,851213.0,KHAGARIA,BIHAR,2026-07-08,1.0,2026-07-08,2026-07-08,2026-07-08,2026-07-11T07:45:01.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T22:05:14.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4874.00,3874.0,24450.0,ZONAL,False,NaN,2026-07-14T03:15:00+0530,PickupHub_PAT,SATELLITEHUB_KGG,2026-07-14,2026-07-08,SPS,64.0,49.0,24450.0,39.0,SATELLITEHUB_KGG,SATELLITEHUB_KGG,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-08,delivered,2026-07-11,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,9,<=45,Null,1
4,ORD-SO-796826,NaN,AWPC0000078604,FSD_LARGE,AWP,BALWAAN DOUBLE BATTERY-DOUBLE MOTOR BS-22D 12X...,ATE3A59AB38GD97A63A05,ext_sps,AWP,AWP : Rohit Bajaj,AWP_85296f55bcc56dc187a14f2f9c6e8299,Forward,SHIPMENT,COD,Z,True,2026-07-08,ShipmentDelivered,711302.0,Howrah,WEST BENGAL,848201.0,BEGUSARAI,BIHAR,2026-07-01,4.0,2026-07-01,2026-07-04,2026-07-04,2026-07-08T06:33:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T22:24:37.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,7370.00,6870.0,29172.0,ZONAL,False,NaN,2026-07-11T03:15:00+0530,PickupHub_FKHWH,Satellitehub_FKBEGU,2026-07-11,2026-07-04,SPS,64.0,53.0,29172.0,43.0,Satellitehub_FKBEGU,Satellitehub_FKBEGU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-04,delivered,2026-07-08,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,16,<=45,Null,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921759,XPYE2ETDDR8JIQTK,NaN,UNCP0000314145,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,302021.0,JAIPUR,RAJASTHAN,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-18T02:09:37.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T15:45:26.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JAI,2026-04-19,2026-04-13,SPS,30.0,8.0,3480.0,21.0,SatelliteHub_JAI,SatelliteHub_JAI,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,98,>45,Null,1
921760,CP66PCOX4L,NaN,UNCP0000314813,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-01,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,274301.0,DEORIA,UTTAR PRADESH,2026-04-14,3.0,2026-04-14,2026-04-17,2026-04-17,2026-04-30T23:56:26.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T21:43:49.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-28T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_KUSHINAGAR,2026-04-28,2026-04-17,SPS,20.0,19.0,6640.0,26.0,SATELLITEHUB_KUSHINAGAR,SATELLITEHUB_KUSHINAGAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-01,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,94,>45,Null,1
921761,E5VOT73QQV,NaN,UNCP0000314816,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-07,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,805110.0,NAWADA,BIHAR,2026-04-14,3.0,2026-04-14,2026-04-17,2026-04-17,2026-05-07T06:00:49.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T18:25:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-26T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_FKNWD,2026-04-26,2026-04-17,SPS,20.0,19.0,6640.0,26.0,Satellitehub_FKNWD,Satellitehub_FKNWD,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-07,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,94,>45,Null,1
921762,5XYZFK5V3Y0NOT0N,NaN,UNCP0000314002,FSD_LARGE,UNC,GATE ELECTRICAL,GATE ELECTRICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,382330.0,AHMEDABAD,GUJARAT,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-18T07:53:46.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T23:10:07.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,5710.0,METRO,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_NAR,2026-04-19,2026-04-13,SPS,19.0,18.0,5710.0,25.0,SatelliteHub_NAR,SatelliteHub_NAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,98,>45,Null,1
921763,WETER7WN993JO9OG,NaN,UNCP0000314142,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-19,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,752001.0,PURI,ODISHA,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-19T04:27:51.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T18:09:19.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-20T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_FKPUR,2026-04-20,2026-04-13,SPS,30.0,8.0,3480.0,21.0,Satellitehub_FKPUR,Satellitehub_FKPUR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-19,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,98,>45,Null,1

In [33]:
conditions = {'COM': 2000,'CUH': 3000,'SOL': 7500,'SWE': 10000,'TEL': 3000,'BBO':2000,'CUM':2000,
             'EMB':4000,'FLO':7000,'HBL':2000,'KPI':2000,'LUA':2000,'NKD':7000,'SDH':2000,'SWL':2000,'WZI':2000,
             'HOX':3000,'EML':2000,'ARL':2000,'LTL':4000,'OIL':1200,'SIL':2000,'VSL':1000,'ULT':2000}
series = drf['merchant_code'].map(conditions).fillna(5000)
check = drf["shipment_value"] / drf["child_count"]
drf['logistics_breach_bucket'] = np.minimum(drf['shipment_value'], series)

base_value = np.minimum(drf["shipment_value"], series)
new_logic_bucket = np.minimum(check, base_value)
drf["logistics_breach_bucket"] = np.where(drf["merchant_code"] == "IKE", check, new_logic_bucket)
drf["logistics_breach_bucket"] = drf["logistics_breach_bucket"].round(1)
drf

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,first_ph_in_post_rto_hub_name,first_ph_in_post_rto_datetime,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor,ERP_Status,Final_Status,Unnamed: 0,Timestamp,AWB_TID_number,Issue_Category,Status,Reason,PH_or_DH,Seller_type,Payment_Mode,Customer Code,shipment_value_1,todays_date,ageing_1,Ageing_bucket,loss,child_count,logistics_breach_bucket
0,TFC001512055,NaN,AMAP0000000577,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-06-15,ShipmentDelivered,110086.0,Delhi,DELHI,560068.0,BANGALORE,KARNATAKA,2026-06-10,1.0,2026-06-10,2026-06-10,2026-06-10,2026-06-15T05:01:43.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T14:44:54.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5510.25,0.0,19000.0,METRO,False,NaN,2026-06-15T03:15:00+0530,PICKUPHUB_RPBAGHFM,BulkHub_BLR,2026-06-15,2026-06-10,SPS,120.0,25.0,19000.0,25.0,BulkHub_BLR,BulkHub_BLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-10,delivered,2026-06-15,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,37,<=45,Null,1,5000.0
1,TFC001512213,NaN,AMAP0000000819,FSD_LARGE,AMA,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-07-05,ShipmentDelivered,110086.0,Delhi,DELHI,580023.0,DHARWAD,KARNATAKA,2026-06-30,1.0,2026-06-30,2026-06-30,2026-06-30,2026-07-05T05:25:29.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T18:00:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5628.75,0.0,13000.0,ROI,False,NaN,2026-07-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_FKHBLA,2026-07-05,2026-06-30,SPS,110.0,20.0,13000.0,20.0,SATELLITEHUB_FKHBLA,SATELLITEHUB_FKHBLA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-30,delivered,2026-07-05,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,17,<=45,Null,1,5000.0
2,940069,NaN,ARLP0000003366,FSD_LARGE,ARL,SINGER COOKMATE 5L,SINGER COOKMATE 5L,ext_sps,ARL,ARL : ARL_THA_01,ARL_448c561fc19f951b85377ebb5382e9af,Forward,SHIPMENT,PP,N,True,2026-06-12,ShipmentDelivered,401105.0,Thane,MAHARASHTRA,800007.0,PATNA,BIHAR,2026-06-03,1.0,2026-06-03,2026-06-04,2026-06-04,2026-06-12T05:01:52.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T18:26:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2784.00,0.0,2600.0,ROI,False,NaN,2026-06-13T03:15:00+0530,Pickuphub_FKMIB,SatelliteHub_PAT,2026-06-13,2026-06-04,SPS,45.0,20.0,2600.0,25.0,SatelliteHub_PAT,SatelliteHub_PAT,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-04,delivered,2026-06-12,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,44,<=45,Null,1,2000.0
3,ORD-SO-813176,NaN,AWPC0000077622,FSD_LARGE,AWP,Hymatic Single Battery 12X8 16 Ltr Battery Ope...,ATE3A59AE91CK26A71A05,ext_sps,AWP,AWP : Patna WH,AWP_06690e9940963d92d58bcb3a6563d29c,Forward,SHIPMENT,COD,Z,True,2026-07-11,ShipmentDelivered,803201.0,Patna,BIHAR,851213.0,KHAGARIA,BIHAR,2026-07-08,1.0,2026-07-08,2026-07-08,2026-07-08,2026-07-11T07:45:01.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T22:05:14.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4874.00,3874.0,24450.0,ZONAL,False,NaN,2026-07-14T03:15:00+0530,PickupHub_PAT,SATELLITEHUB_KGG,2026-07-14,2026-07-08,SPS,64.0,49.0,24450.0,39.0,SATELLITEHUB_KGG,SATELLITEHUB_KGG,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-08,delivered,2026-07-11,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,9,<=45,Null,1,4874.0
4,ORD-SO-796826,NaN,AWPC0000078604,FSD_LARGE,AWP,BALWAAN DOUBLE BATTERY-DOUBLE MOTOR BS-22D 12X...,ATE3A59AB38GD97A63A05,ext_sps,AWP,AWP : Rohit Bajaj,AWP_85296f55bcc56dc187a14f2f9c6e8299,Forward,SHIPMENT,COD,Z,True,2026-07-08,ShipmentDelivered,711302.0,Howrah,WEST BENGAL,848201.0,BEGUSARAI,BIHAR,2026-07-01,4.0,2026-07-01,2026-07-04,2026-07-04,2026-07-08T06:33:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T22:24:37.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,7370.00,6870.0,29172.0,ZONAL,False,NaN,2026-07-11T03:15:00+0530,PickupHub_FKHWH,Satellitehub_FKBEGU,2026-07-11,2026-07-04,SPS,64.0,53.0,29172.0,43.0,Satellitehub_FKBEGU,Satellitehub_FKBEGU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-04,delivered,2026-07-08,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,16,<=45,Null,1,5000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921759,XPYE2ETDDR8JIQTK,NaN,UNCP0000314145,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,302021.0,JAIPUR,RAJASTHAN,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-18T02:09:37.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T15:45:26.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JAI,2026-04-19,2026-04-13,SPS,30.0,8.0,3480.0,21.0,SatelliteHub_JAI,SatelliteHub_JAI,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,98,>45,Null,1,3000.0
921760,CP66PCOX4L,NaN,UNCP0000314813,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-01,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,274301.0,DEORIA,UTTAR PRADESH,2026-04-14,3.0,2026-04-14,2026-04-17,2026-04-17,2026-04-30T23:56:26.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T21:43:49.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-28T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_KUSHINAGAR,2026-04-28,2026-04-17,SPS,20.0,19.0,6640.0,26.0,SATELLITEHUB_KUSHINAGAR,SATELLITEHUB_KUSHINAGAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-01,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,94,>45,Null,1,3000.0
921761,E5VOT73QQV,NaN,UNCP0000314816,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-07,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,805110.0,NAWADA,BIHAR,2026-04-14,3.0,2026-04-14,2026-04-17,2026-04-17,2026-05-07T06:00:49.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T18:25:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-26T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_FKNWD,2026-04-26,2026-04-17,SPS,20.0,19.0,6640.0,26.0,Satellitehub_FKNWD,Satellitehub_FKNWD,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-07,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,94,>45,Null,1,3000.0
921762,5XYZFK5V3Y0NOT0N,NaN,UNCP0000314002,FSD_LARGE,UNC,GATE ELECTRICAL,GATE ELECTRICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,382330.0,AHMEDABAD,GUJARAT,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-18T07:53:46.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T23:10:07.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,5710.0,METRO,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_NAR,2026-04-19,2026-04-13,SPS,19.0,18.0,5710.0,25.0,SatelliteHub_NAR,SatelliteHub_NAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,98,>45,Null,1,3000.0
921763,WETER7WN993JO9OG,NaN,UNCP0000314142,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-19,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,752001.0,PURI,ODISHA,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-19T04:27:51.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T18:09:19.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-20T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_FKPUR,2026-04-20,2026-04-13,SPS,30.0,8.0,3480.0,21.0,Satellitehub_FKPUR,Satellitehub_FKPUR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-19,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0,2026-07-17,98,>45,Null,1,3000.0

In [34]:
q1=drf.pivot_table(index='loss',columns='dispatch_month',values='tracking_id',aggfunc='count')
q1.loc['Total'] = q1.sum()
q10=q1.drop(index='Null')
q10

dispatch_month           4         5         6         7
loss
<=45_Open-RTO          NaN       NaN    2881.0    3734.0
>45_60-open_RTO        NaN     819.0      55.0       NaN
>60-open_RTO         771.0     548.0       NaN       NaN
Lost                   NaN       2.0       6.0       NaN
Open                 271.0     484.0    1575.0   50487.0
RTS>45_60            207.0     259.0       1.0       NaN
RTS>60                45.0      10.0       NaN       NaN
conditional_Loss      83.0     100.0     254.0      29.0
Total             259322.0  238473.0  267246.0  156723.0

In [35]:
q2=drf.pivot_table(index='loss',columns='dispatch_month',values='logistics_breach_bucket',aggfunc='sum')
q20=q2.drop(index='Null')
q20

dispatch_month            4          5           6            7
loss
<=45_Open-RTO           NaN        NaN  10130363.6   12093397.8
>45_60-open_RTO         NaN  2838110.1    154597.9          NaN
>60-open_RTO      2340605.1  1905172.6         NaN          NaN
Lost                    NaN     7000.0     19241.9          NaN
Open               985327.1  1951546.0   6524924.2  172524830.5
RTS>45_60          719997.2  1142094.7      3115.4          NaN
RTS>60             132051.3    34895.5         NaN          NaN
conditional_Loss   216503.2   355246.8   1171798.6      81173.2

In [36]:
drf['shipment_value_1']=drf['shipment_value_1'].astype(int)

In [37]:
q9=drf.pivot_table(columns=['dispatch_month'],values='shipment_value_1',aggfunc='sum')
q9=q9.rename(index={"shipment_value_1" : "Total"})
q9

dispatch_month          4          5          6         7
Total           154419616  150035321  159359328  92140222

In [38]:
g5=pd.concat([q20,q9])

In [39]:
j1=pd.concat([q10,g5],axis=1)
j1

dispatch_month,4,5,6,7,4,5,6,7
<=45_Open-RTO,NaN,NaN,2881.0,3734.0,NaN,NaN,10130363.6,12093397.8
>45_60-open_RTO,NaN,819.0,55.0,NaN,NaN,2838110.1,154597.9,NaN
>60-open_RTO,771.0,548.0,NaN,NaN,2340605.1,1905172.6,NaN,NaN
Lost,NaN,2.0,6.0,NaN,NaN,7000.0,19241.9,NaN
Open,271.0,484.0,1575.0,50487.0,985327.1,1951546.0,6524924.2,172524830.5
RTS>45_60,207.0,259.0,1.0,NaN,719997.2,1142094.7,3115.4,NaN
RTS>60,45.0,10.0,NaN,NaN,132051.3,34895.5,NaN,NaN
conditional_Loss,83.0,100.0,254.0,29.0,216503.2,355246.8,1171798.6,81173.2
Total,259322.0,238473.0,267246.0,156723.0,154419616.0,150035321.0,159359328.0,92140222.0

In [40]:
g1=drf[~drf['loss'].isin(['Null'])]
h1=g1.pivot_table(columns=['dispatch_month'],values='tracking_id',aggfunc='count',fill_value=0)
h1=h1.rename(index={"tracking_id" : "Total Loss"})
h1

dispatch_month     4     5     6      7
Total Loss      1377  2222  4772  54250

In [41]:
h2=g1.pivot_table(columns=['dispatch_month'],values='logistics_breach_bucket',aggfunc='sum',fill_value=0)
h2=h2.rename(index={"logistics_breach_bucket" : "Total Loss"})

In [42]:
h10=pd.concat([h1,h2],axis=1)
h10

dispatch_month,4,5,6,7,4,5,6,7
Total Loss,1377,2222,4772,54250,4394483.9,8234065.7,18004041.6,184699401.5

In [43]:
s1=pd.concat([j1,h10])
s1=s1.fillna(0)
s1

dispatch_month,4,5,6,7,4,5,6,7
<=45_Open-RTO,0.0,0.0,2881.0,3734.0,0.0,0.0,10130363.6,12093397.8
>45_60-open_RTO,0.0,819.0,55.0,0.0,0.0,2838110.1,154597.9,0.0
>60-open_RTO,771.0,548.0,0.0,0.0,2340605.1,1905172.6,0.0,0.0
Lost,0.0,2.0,6.0,0.0,0.0,7000.0,19241.9,0.0
Open,271.0,484.0,1575.0,50487.0,985327.1,1951546.0,6524924.2,172524830.5
RTS>45_60,207.0,259.0,1.0,0.0,719997.2,1142094.7,3115.4,0.0
RTS>60,45.0,10.0,0.0,0.0,132051.3,34895.5,0.0,0.0
conditional_Loss,83.0,100.0,254.0,29.0,216503.2,355246.8,1171798.6,81173.2
Total,259322.0,238473.0,267246.0,156723.0,154419616.0,150035321.0,159359328.0,92140222.0
Total Loss,1377.0,2222.0,4772.0,54250.0,4394483.9,8234065.7,18004041.6,184699401.5

In [44]:
j1 = j1[~j1.index.duplicated(keep='first')]
h10 = h10[~h10.index.duplicated(keep='first')]

s1 = pd.concat([j1, h10])

In [45]:
percentage_undelivereds = (h10 / j1.loc["Total"]) * 100
percentage_undelivereds =percentage_undelivereds.rename(index={"percentage_undelivereds" : "Lost shipment"})
percentage_undelivereds = percentage_undelivereds.map(lambda x: f"{x:.2f}%")
percentage_undelivereds

dispatch_month      4      5      6       7      4      5       6        7
Total Loss      0.53%  0.93%  1.79%  34.62%  2.85%  5.49%  11.30%  200.45%

In [46]:
s8=pd.concat([s1,percentage_undelivereds])
s8

dispatch_month,4,5,6,7,4,5,6,7
<=45_Open-RTO,NaN,NaN,2881.0,3734.0,NaN,NaN,10130363.6,12093397.8
>45_60-open_RTO,NaN,819.0,55.0,NaN,NaN,2838110.1,154597.9,NaN
>60-open_RTO,771.0,548.0,NaN,NaN,2340605.1,1905172.6,NaN,NaN
Lost,NaN,2.0,6.0,NaN,NaN,7000.0,19241.9,NaN
Open,271.0,484.0,1575.0,50487.0,985327.1,1951546.0,6524924.2,172524830.5
RTS>45_60,207.0,259.0,1.0,NaN,719997.2,1142094.7,3115.4,NaN
RTS>60,45.0,10.0,NaN,NaN,132051.3,34895.5,NaN,NaN
conditional_Loss,83.0,100.0,254.0,29.0,216503.2,355246.8,1171798.6,81173.2
Total,259322.0,238473.0,267246.0,156723.0,154419616.0,150035321.0,159359328.0,92140222.0
Total Loss,1377.0,2222.0,4772.0,54250.0,4394483.9,8234065.7,18004041.6,184699401.5
Total Loss,0.53%,0.93%,1.79%,34.62%,2.85%,5.49%,11.30%,200.45%

In [47]:
ageing_1=(pd.to_datetime(drf['todays_date']) - pd.to_datetime(drf['Latest_Update_Time'])).dt.days
drf["last_scan_ageing"]=ageing_1
drf['last_scan_ageing']=drf['last_scan_ageing'].fillna(-1)
def last_scan_ageing_bucket(last_scan_ageing):
    
    if last_scan_ageing < 0:
        return "ageing 0"
    elif last_scan_ageing >= 0 and last_scan_ageing <=2:
        return "ageing 0-2"
    elif last_scan_ageing >=3 and last_scan_ageing <=5:
        return "ageing 3-5"
    elif last_scan_ageing >=6 and last_scan_ageing <=10:
        return "ageing 6-10"
    elif last_scan_ageing >=11 and last_scan_ageing <=20:
        return "ageing 11-20"
    else:
        return "ageing >20"

drf['last_scan_ageing_bucket'] = drf['last_scan_ageing'].apply(last_scan_ageing_bucket)
t1=drf[drf['Final_Status'].isin(['Open','Open-RTO']) & ~drf['last_scan_ageing'].isin([-1,0,1,2])]
t1.to_csv("Eagleye_out.csv",index=False)
t1

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,first_ph_in_post_rto_hub_name,first_ph_in_post_rto_datetime,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor,ERP_Status,Final_Status,Unnamed: 0,Timestamp,AWB_TID_number,Issue_Category,Status,Reason,PH_or_DH,Seller_type,Payment_Mode,Customer Code,shipment_value_1,todays_date,ageing_1,Ageing_bucket,loss,child_count,logistics_breach_bucket,last_scan_ageing,last_scan_ageing_bucket
13,ORD-SO-731125,NaN,AWPC0000083704,FSD_LARGE,AWP,SUMITOMO TOBLER 500ML,CPB5F14AM94FE32A00B73,ext_sps,AWP,AWP : Naveen Kumar,AWP_07244bb3805e9199e4db17a298d96c62,Forward,SHIPMENT,COD,N,True,2026-07-03,ShipmentUndeliveredAttempted,132001.0,Karnal,HARYANA,854101.0,KATIHAR,BIHAR,2026-05-29,1.0,2026-05-29,2026-05-29,2026-05-29,2026-06-04T07:02:57.000+05:30,2026-06-10T08:27:01.000+05:30,2026-07-03T08:15:41.000+05:30,NaN,Attempted,NaN,4.0,Customer Not Responding,Customer Not Responding,NaN,Customer Not Responding,NaN,NaN,NaN,6768.00,5006.0,12000.0,ROI,False,NaN,2026-06-08T04:15:00+0530,PickupHub_KNL1,Satellitehub_Naugachia,2026-06-08,2026-05-29,SPS,39.0,33.0,12000.0,21.0,Satellitehub_Naugachia,Satellitehub_Naugachia,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,5,2026-05-29,Open,2026-07-17,35.0,AWPC0000083704,NORMAL_FORWARD,REGULAR,NaN,COD,6768.00,854101.0,Undelivered_No_Response,Satellitehub_Naugachia,Satellitehub_Naugachia,2026-07-09,CentralHub_KNL1,2026-05-29 17:20:20,Updated by CRON,DELIVERY_DATE_CHANGED: 16-Jun-2026,4.0,NaN,NaN,2026-06-16 23:59:59,2026-06-08 04:15:00,NaN,NaN,Satellitehub_Naugachia,2026-06-04 06:55:51,ORD-SO-731125,NaN,NaN,NaN,NaN,Open,Open,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,49,>45,Open,1,5000.0,8.0,ageing 6-10
86,BH2504911,NaN,BHHC0004497972,FSD_LARGE,BHH,[BHI2220005801] \rSumitomo Glycel Herbicide G...,[BHI2220005801] \rSumitomo Glycel Herbicide ? ...,ext_sps,BHH,BHH : AgroHaat FC - Bannerghatta,BHH_99a93e438076a5ebcac12159a2ff1d1d,Forward,SHIPMENT,COD,Z,True,2026-07-14,InscannedAtFacility,560083.0,Bangalore,KARNATAKA,505188.0,ADIVARAMPET,TELANGANA,2026-07-12,1.0,2026-07-12,2026-07-12,2026-07-12,NaN,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,649.00,649.0,4000.0,ZONAL,False,NaN,2026-07-18T03:15:00+0530,Pickuphub_FKBGR2,CentralHub_L_SGR1,2026-07-18,2026-07-12,SPS,1.0,1.0,4000.0,1.0,NaN,SatelliteHub_GDV,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,2026-07-12,Open,2026-07-17,2.0,BHHC0004497972,NORMAL_FORWARD,REGULAR,NaN,COD,649.00,505188.0,Undelivered_Not_Attended,SatelliteHub_GDV,CentralHub_L_SGR1,2026-07-14,CentralHub_FKBGR2,2026-07-12 16:28:12,NaN,NaN,0.0,NaN,NaN,2026-07-18 23:59:59,2026-07-18 03:15:00,NaN,NaN,SatelliteHub_GDV,2026-07-14 12:50:24,BH2504911,NaN,NaN,NaN,NaN,Open,Open,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,5,<=45,Open,1,649.0,3.0,ageing 3-5
176,612652,NaN,EMHR0000046623,FSD_LARGE,EMH,Emma Black Mattress,EMABK122183AAB,ext_sps,EMH,EMH : Emma Sleep,EMH_627b98a00211d3b14674c9abd0aef01d,RVP,RVP,PP,N,False,2026-07-11,InScanAtHub,781006.0,KAMRUP,ASSAM,131001.0,SONIPAT,HARYANA,2026-07-09,0.0,2026-07-09,2026-07-11,2026-07-11,NaN,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10299.00,0.0,37650.0,ROI,False,NaN,NaN,NaN,CentralHub_PBI,NaN,2026-07-11,SPS,183.0,15.0,37650.0,190.0,NaN,PICKUPHUB_MPHUB_SONIPAT,NaN,2026-07-10T08:26:38.000+05:30,2026-07-10T08:26:38.000+05:30,1.0,2026-07-10T19:52:15.000+05:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,2026-07-11,Open,2026-07-17,0.0,EMHR0000046623,PICKUP_ONLY,REGULAR,NaN,RVP,10299.00,131001.0,Expected,PICKUPHUB_MPHUB_SONIPAT,CentralHub_L_YKBX1,2026-07-14,Satellitehub_GUW2,2026-07-10 19:35:26,RVP,NaN,1.0,NaN,NaN,2026-07-10 10:46:44,NaN,NaN,NaN,PICKUPHUB_MPHUB_SONIPAT,2026-07-11 15:33:28,612652,NaN,NaN,NaN,NaN,Open,Open,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,8,<=45,Open,1,5000.0,3.0,ageing 3-5
289,42979959IYDBD5CD5C,NaN,FCLC0001462920,FSD_LARGE,FCL,Babyhug Foldable Bathtub with Cushion and Inbu...,13262430,ext_sps,FCL,FCL : Hyderabad,FCL_83f8a713f5271136517e4b7f0dd8a674,Forward,SHIPMENT,COD,N,True,2026-07-14,PickupReceived,509228.0,Rangareddy,TELANGANA,471001.0,CHHATARPUR,MADHYA PRADESH,2026-07-13,1.0,2026-07-14,2026-07-14,2026-07-14,NaN,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2895.00,1553.0,2900.0,ROI,False,NaN,NaN,Pickuphub_JDC,Pickuphub_JDC,NaN,2026-07-14,SPS,82.0,10.0,2900.0,51.0,NaN,Satellitehub_CTPR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,2026-07-14,Open,2026-07-17,0.0,FCLC0001462920,NORMAL_FORWARD,REGULAR,NaN,COD,2895.00,471001.0,Expected,Satellitehub_CTPR,Centralhub_JDC,2026-07-13,NaN,NaN,NaN,NaN,0.0,NaN,NaN,2026-07-23 23:57:27,NaN,NaN,NaN,Satellitehub_CTPR,NaN,42979959IYDBD5CD5C,NaN,NaN,NaN,NaN,Open,Open,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,3,<=45,Open,1,2895.0,4.0,ageing 3-5
303,12086555CHZ7656B64,NaN,FCLP0000649753,FSD_LARGE,FCL,Taffykids 100% Cotton Woven Sleeveless Daisy P...,21122681,ext_sps,FCL,FCL : HUNDREDCLOTHES PRIVATE LIMITED,FCL_24e8367ccac49d004c4108bb0f693e03,RTO,RTO,PP,N,True,2026-04-30,ShipmentUndeliveredAttempted,421302.0,Bhiwandi,MAHARASHTRA,680570.0,THRISSUR,KERALA,2026-04-21,1.0,2026-04-21,2026-04-21,2026-04-21,2026-04-29T16:02:56.000+05:30,2026-04-29T16:03:02.000+05:30,2026-04-30T07:54:55.000+05:30,NaN,Attempted,2026-04-30T18:32:17.000+05:30,2.0,RequestForReschedule,RequestForReschedule,SatelliteHub_TCR,RequestForReschedule,ORC_validated with customer,ShipmentUndeliveredAttempted,NaN,599.00,0.0,200.0,ROI,False,NaN,2026-04-29T03:15:00+0530,PickupHub_BHI1,SatelliteHub_TCR,2026-04-29,2026-04-21,SPS,30.0,2.0,200.0,40.0,SatelliteHub_TCR,PickupHub_MPHub_BHI1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,NaN,NaN,4,2026-04-21,Open-RTO,2026-07-17,9.0,FCLP0000649753,NORMAL_FORWARD,ECONOMY,NaN,PP,599.00,421302.0,Untraceable,PickupHub_MPHub_BHI1,SatelliteHub_TCR,2026-05-03,CentralHub_BHW1,2026-04-21 19:45:39,Updated by CRON,Marked_As_RTO,2.0,NaN,NaN,2026-04-30 23:59:59,2026-04-29 03:15:00,NaN,NaN,SatelliteHub_TCR,2026-04-29 15:55:54,12086555CHZ7656B64,NaN,NaN,NaN,NaN,Open,Open-RTO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,87,>45,>60-open_RTO,1,599.0,75.0,ageing >20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
914522,NYK-344960769-4196499-1,NaN,NKDC0000044690,FSD_LARGE,NKD,Nykaa Black Magic Kajal - Black(0.3gm),NYKAC00000132,ext_sps,NKD,NKD : Nykaa eB2B Warehouse Patna,NKD_ef2707b9c90671f302cc91d92780951a,RTO,RTO,COD,Z,True,2026-04-17,ShipmentUndeliveredAttempted,804451.0,Patna,BIHAR,802158.0,ARRAH,BIHAR,2026-04-13,1.0,2026-04-13,2026-04-13,2026-04-13,2026-04-16T05:37:27.000+05:30,2026-04-16T09:35:36.000+05:30,2026-04-16T09:35:36.000+05:30,NaN,Attempted,2026-04-17T00:02:09.000+05:30,1.0,OrderRejectedByCustomer,OrderRejectedByCustomer,Satellitehub_BhojpurSplit,OrderRejectedByCustomer,ORC_validated with customer,ShipmentUndeliveredAttempted,NaN,2388.00,994.0,500.0,ZONAL,False,NaN,2026-04-17T04:15:00+0530,PickupHub_PAT,Satellitehub_BhojpurSplit,2026-04-17,2026-04-13,SPS,27.0,9.0,500.0,19.0,Satellitehub_BhojpurSplit,Pickuphub_MPhub_PAT,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,4,2026-04-13,Open-RTO,2026-07-17,4.0,NKDC0000044690,NORMAL_FORWARD,ECONOMY,NaN,COD,2388.00,804451.0,Untraceable,Pickuphub_MPhub_PAT,Satellitehub_BhojpurSplit,2026-05-29,CentralHub_PAT1,2026-04-14 01:22:48,Updated by CRON,Marked_As_RTO,1.0,NaN,NaN,2026-04-17 23:59:59,2026-04-17 04:15:00,NaN,NaN,Satellitehub_BhojpurSplit,2026-04-16 05:30:22,NYK-344960769-4196499-1,NaN,NaN,NaN,NaN,Open,Open-RTO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,95,>45,>60-open_RTO,1,2388.0,49.0,ageing >20
914748,CP26643391_1,NaN,PRHP0000152761,FSD_LARGE,PRH,Bank Mahapack Selection Box Hindi Book Kit,19702,ext_sps,PRH,PRH : Metis Eduventures Private Limited,PRH_03cdd8b0b4e9b5df79c34db861cc1e22,RTO,RTO,PP,N,True,2026-06-02,InScanAtHub,201301.0,Noida,UTTAR PRADESH,403802.0,SOUTH GOA,GOA,2026-04-03,1.0,2026-04-03,2026-04-03,2026-04-03,NaN,NaN,NaN,NaN,Not_Attempted,2026-05-04T14:59:13.000+05:30,0.0,NaN,NaN,Motherhub_GGN,NaN,Shipment Delayed,NaN,NaN,3220.31,0.0,2853.0,ROI,True,NaN,2026-04-08T03:15:00+0530,PICKUPHUB_GNOIDAFM,Motherhub_JKS,2026-04-08,2026-04-03,SPS,5.0,5.0,2853.0,5.0,NaN,PickupHub_MPHub_GNOIDAFM,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,2026-04-03,Open-RTO,2026-07-17,60.0,PRHP0000152761,NORMAL_FORWARD,ECONOMY,NaN,PP,3220.31,201301.0,Undelivered_Not_Attended,PickupHub_MPHub_GNOIDAFM,MotherHub_YKB,2026-06-17,CENTRALHUB_GNOIDAFM,2026-04-03 19:41:18,NaN,Marked_As_RTO,0.0,EMPGNOIDA-124025,REACHED,2026-04-08 23:59:59,2026-04-08 03:15:00,NaN,NaN,Satellitehub_VASC,2026-06-17 06:04:07,CP26643391_1,NaN,NaN,NaN,NaN,Open,Open-RTO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRH,98,2026-07-17,105,>45,>60-open_RTO,1,3220.3,30.0,ageing >20
917105,REHP0000027425,NaN,REHP0000027425,FSD_LARGE,REH,Livpure Comforter Pink steel grey Single 56x90...,Livpure Comforter Pink steel grey Single 56x90...,ext_sps,REH,REH : Warehouse,REH_b0a1d8b5d056129d2a6de99d1e691e29,Forward,SHIPMENT,PP,N,True,2026-06-01,InScanAtHub,560058.0,Bangalore,KARNATAKA,110034.0,NEW DELHI,DELHI,2026-05-26,1.0,2026-05-26,2026-05-26,2026-05-26,NaN,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3500.00,0.0,5000.0,METRO,False,NaN,2026-06-02T03:15:00+0530,PickupHub_FKYWP,CentralHub_L_YKBX1,2026-06-02,2026-05-26,SPS,0.0,0.0,5000.0,0.0,NaN,SATELLITEHUB_AZADPUR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,2026-05-26,Open,2026-07-17,6.0,REHP0000027425,NORMAL_FORWARD,ECONOMY,NaN,PP,3500.00,560058.0,Expected,PickupHub_MPHub_FKYWP,SATELLITEHUB_AZADPUR,2026-06-16,CENTRALHUB_FKYWP,2026-05-26 18:28:59,NaN,Marked_As_RTO,0.0,NaN,NaN,2026-06-02 23:59:59,2026-06-02 03:15:00,NaN,NaN,SATELLITEHUB_AZADPUR,2026-06-01 20:43:23,REHP0000027425,NaN,NaN,NaN,NaN,Open,Open-RTO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,52,>45,>45_60-open_RTO,1,3500.0,31.0,ageing >20
917376,REHP0000027349,NaN,REHP0000027349,FSD_LARGE,REH,Maharaja Ednis Neo Water heater - 10 Litre |,Maharaja Ednis Neo Water heater - 10 Litre |,ext_sps,REH,REH : Warehouse,REH_b0a1d8b5d056129d2a6de99d1e691e29,Forward,SHIPMENT,PP,Z,True,2026-05-25,InScanAtHub,560058.0,Bangalore,KARNATAKA,600048.0,CHENNAI,TAMIL NADU,2026-05-23,1.0,2026-05-23,2026-05-23,2026-05-23,NaN,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7599.00,0.0,5000.0,ZONAL,False,NaN,2026-05-28T03:15:00+0530,PickupHub_FKYWP,CentralHub_L_CHNX7,2026-05-28,2026-05-23,SPS,0.0,0.0,5000.0,0.0,NaN,SatelliteHub_TMB1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,2026-05-23,Open,2026-07-17,2.0,REHP0000027349,NORMAL_FORWARD,ECONOMY,NaN,PP,7599.00,560058.0,Undelivered_Not_Attended,PickupHub_MPHub_FKYWP,CentralHub_L_CHNX7,2026-06-16,CENTRALHUB_FKYWP,2026-05-23 19:49:36,NaN,Marked_As_RTO,0.0,NaN,NaN,2026-05-28 23:59:59,2026-05-28 03:15:00,NaN,NaN,SatelliteHub_TMB1,2026-05-25 14:53:03,REHP0000027349,NaN,NaN,NaN,NaN,Open,Open-RTO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,55,>45,>45_60-open_RTO,1,5000.0,31.0,ageing >20
917920,REHP0000011496,NaN,REHP0000011496,FSD_LARGE,REH,Sujata Pedestal Fan SPF09 |,Sujata Pedestal Fan SPF09 |,ext_sps,REH,REH : Warehouse,REH_b0a1d8b5d056129d2a6de99d1e691e29,Forward,SHIPMENT,PP,Z,True,2026-05-30,InScanAtHub,560058.0,Bangalore,KARNATAKA,501102.0,RANGA REDDY,TELANGANA,2026-05-28,1.0,2026-05-28,2026-05-28,2026-05-28,NaN,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4356.00,0.0,5000.0,ZONAL,False,NaN,2026-06-01T03:15:00+0530,PickupHub_FKYWP,CentralHub_L_SGR1,2026-06-01,2026-05-28,SPS,0.0,0.0,5000.0,0.0,NaN,SATELLITEHUB_VKR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,2026-05-28,Open,2026-07-17,2.0,REHP0000011496,NORMAL_FORWARD,ECONOMY,NaN,PP,4356.00,560058.0,Expected,PickupHub_MPHub_FKYWP,SatelliteHub_ADB,2026-06-17,CENTRALHUB_FKYWP,2026-05-28 18:24:59,NaN,Marked_As_RTO,0.0,NaN,NaN,2026-06-01 23:59:59,2026-06-01 03:15:00,NaN,NaN,SATELLITEHUB_VKR,2026-05-30 17:36:45,REHP0000011496,NaN,NaN,NaN,NaN,Open,Open-RTO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,50,>45,>45_60-open_RTO,1,4356.0,30.0,ageing >20

In [48]:
t2=pd.read_csv("6a59aad3b066d77cf54396d2.csv")
t2

,Facility,Department,Casper ID,Date,Time,Shipment/Bag ID,Seal ID,PTC Code,Device #
0,CentralHub_LUD,OUTBOUND,manjeetsharma.vc,13-07-2026,07:36 PM,SOLC9900220467,NaN,NaN,4CPT9D3
1,Satellitehub_FKDURG,LM-PRC,mohanlalyadav.vc,16-07-2026,02:35 PM,FLOP1001250115,NaN,NaN,8CN1280012
2,CentralHub_L_KOL5,MH-INBOUND,3216379,12-07-2026,12:12 PM,MOHC2700102162,NaN,NaN,UNKNOWN
3,CentralHub_MPL1,MH-OUTBOUND,3384247,14-07-2026,05:46 PM,BHHC0004552115,NaN,NaN,UNKNOWN
4,CentralHub_L_KAL1,MH-OUTBOUND,3331665,14-07-2026,05:30 PM,NAHC0000644639,NaN,NaN,01602527051188
...,...,...,...,...,...,...,...,...,...
8282,CentralHub_L_MUMX,MH-OUTBOUND,3184173,14-07-2026,12:32 PM,FLOP1001251656,NaN,NaN,UNKNOWN
8283,Satellitehub_KLKR,LM-PRC,santhosh.3plcud4,16-07-2026,09:06 PM,NKDC0000063586,NaN,NaN,unknown-windows
8284,CentralHub_L_SGR1,INBOUND,konkanibharatk1.vc,14-07-2026,05:05 AM,KPIP0000230204,NaN,NaN,UNKNOWN
8285,CentralHub_L_MUMX,MH-OUTBOUND,2648371,11-07-2026,01:39 PM,FLOC1001248671,NaN,NaN,UNKNOWN
8286,Motherhub_DIC,MH-SEMI LARGE TAGGING,4119409,12-07-2026,08:00 PM,FCLP0001277843,NaN,NaN,UNKNOWN

In [49]:
drf1=drf.merge(t2[['Shipment/Bag ID','Date','Facility']],left_on='tracking_id',right_on='Shipment/Bag ID',how='left').drop_duplicates(subset='tracking_id')
drf1

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,first_ph_in_post_rto_hub_name,first_ph_in_post_rto_datetime,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor,ERP_Status,Final_Status,Unnamed: 0,Timestamp,AWB_TID_number,Issue_Category,Status,Reason,PH_or_DH,Seller_type,Payment_Mode,Customer Code,shipment_value_1,todays_date,ageing_1,Ageing_bucket,loss,child_count,logistics_breach_bucket,last_scan_ageing,last_scan_ageing_bucket,Shipment/Bag ID,Date,Facility
0,TFC001512055,NaN,AMAP0000000577,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-06-15,ShipmentDelivered,110086.0,Delhi,DELHI,560068.0,BANGALORE,KARNATAKA,2026-06-10,1.0,2026-06-10,2026-06-10,2026-06-10,2026-06-15T05:01:43.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T14:44:54.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5510.25,0.0,19000.0,METRO,False,NaN,2026-06-15T03:15:00+0530,PICKUPHUB_RPBAGHFM,BulkHub_BLR,2026-06-15,2026-06-10,SPS,120.0,25.0,19000.0,25.0,BulkHub_BLR,BulkHub_BLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-10,delivered,2026-06-15,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,37,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaN,NaN
1,TFC001512213,NaN,AMAP0000000819,FSD_LARGE,AMA,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-07-05,ShipmentDelivered,110086.0,Delhi,DELHI,580023.0,DHARWAD,KARNATAKA,2026-06-30,1.0,2026-06-30,2026-06-30,2026-06-30,2026-07-05T05:25:29.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T18:00:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5628.75,0.0,13000.0,ROI,False,NaN,2026-07-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_FKHBLA,2026-07-05,2026-06-30,SPS,110.0,20.0,13000.0,20.0,SATELLITEHUB_FKHBLA,SATELLITEHUB_FKHBLA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-30,delivered,2026-07-05,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,17,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaN,NaN
2,940069,NaN,ARLP0000003366,FSD_LARGE,ARL,SINGER COOKMATE 5L,SINGER COOKMATE 5L,ext_sps,ARL,ARL : ARL_THA_01,ARL_448c561fc19f951b85377ebb5382e9af,Forward,SHIPMENT,PP,N,True,2026-06-12,ShipmentDelivered,401105.0,Thane,MAHARASHTRA,800007.0,PATNA,BIHAR,2026-06-03,1.0,2026-06-03,2026-06-04,2026-06-04,2026-06-12T05:01:52.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T18:26:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2784.00,0.0,2600.0,ROI,False,NaN,2026-06-13T03:15:00+0530,Pickuphub_FKMIB,SatelliteHub_PAT,2026-06-13,2026-06-04,SPS,45.0,20.0,2600.0,25.0,SatelliteHub_PAT,SatelliteHub_PAT,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-04,delivered,2026-06-12,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,44,<=45,Null,1,2000.0,-1.0,ageing 0,NaN,NaN,NaN
3,ORD-SO-813176,NaN,AWPC0000077622,FSD_LARGE,AWP,Hymatic Single Battery 12X8 16 Ltr Battery Ope...,ATE3A59AE91CK26A71A05,ext_sps,AWP,AWP : Patna WH,AWP_06690e9940963d92d58bcb3a6563d29c,Forward,SHIPMENT,COD,Z,True,2026-07-11,ShipmentDelivered,803201.0,Patna,BIHAR,851213.0,KHAGARIA,BIHAR,2026-07-08,1.0,2026-07-08,2026-07-08,2026-07-08,2026-07-11T07:45:01.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T22:05:14.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4874.00,3874.0,24450.0,ZONAL,False,NaN,2026-07-14T03:15:00+0530,PickupHub_PAT,SATELLITEHUB_KGG,2026-07-14,2026-07-08,SPS,64.0,49.0,24450.0,39.0,SATELLITEHUB_KGG,SATELLITEHUB_KGG,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-08,delivered,2026-07-11,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,9,<=45,Null,1,4874.0,-1.0,ageing 0,NaN,NaN,NaN
4,ORD-SO-796826,NaN,AWPC0000078604,FSD_LARGE,AWP,BALWAAN DOUBLE BATTERY-DOUBLE MOTOR BS-22D 12X...,ATE3A59AB38GD97A63A05,ext_sps,AWP,AWP : Rohit Bajaj,AWP_85296f55bcc56dc187a14f2f9c6e8299,Forward,SHIPMENT,COD,Z,True,2026-07-08,ShipmentDelivered,711302.0,Howrah,WEST BENGAL,848201.0,BEGUSARAI,BIHAR,2026-07-01,4.0,2026-07-01,2026-07-04,2026-07-04,2026-07-08T06:33:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T22:24:37.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,7370.00,6870.0,29172.0,ZONAL,False,NaN,2026-07-11T03:15:00+0530,PickupHub_FKHWH,Satellitehub_FKBEGU,2026-07-11,2026-07-04,SPS,64.0,53.0,29172.0,43.0,Satellitehub_FKBEGU,Satellitehub_FKBEGU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-04,delivered,2026-07-08,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,16,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921759,XPYE2ETDDR8JIQTK,NaN,UNCP0000314145,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,302021.0,JAIPUR,RAJASTHAN,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-18T02:09:37.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T15:45:26.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JAI,2026-04-19,2026-04-13,SPS,30.0,8.0,3480.0,21.0,SatelliteHub_JAI,SatelliteHub_JAI,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaN,NaN
921760,CP66PCOX4L,NaN,UNCP0000314813,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-01,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,274301.0,DEORIA,UTTAR PRADESH,2026-04-14,3.0,2026-04-14,2026-04-17,2026-04-17,2026-04-30T23:56:26.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T21:43:49.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-28T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_KUSHINAGAR,2026-04-28,2026-04-17,SPS,20.0,19.0,6640.0,26.0,SATELLITEHUB_KUSHINAGAR,SATELLITEHUB_KUSHINAGAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-01,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,94,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaN,NaN
921761,E5VOT73QQV,NaN,UNCP0000314816,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-07,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,805110.0,NAWADA,BIHAR,2026-04-14,3.0,2026-04-14,2026-04-17,2026-04-17,2026-05-07T06:00:49.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T18:25:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-26T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_FKNWD,2026-04-26,2026-04-17,SPS,20.0,19.0,6640.0,26.0,Satellitehub_FKNWD,Satellitehub_FKNWD,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-07,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,94,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaN,NaN
921762,5XYZFK5V3Y0NOT0N,NaN,UNCP0000314002,FSD_LARGE,UNC,GATE ELECTRICAL,GATE ELECTRICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,382330.0,AHMEDABAD,GUJARAT,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-18T07:53:46.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T23:10:07.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,5710.0,METRO,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_NAR,2026-04-19,2026-04-13,SPS,19.0,18.0,5710.0,25.0,SatelliteHub_NAR,SatelliteHub_NAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaN,NaN
921763,WETER7WN993JO9OG,NaN,UNCP0000314142,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-19,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,752001.0,PURI,ODISHA,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-19T04:27:51.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T18:09:19.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-20T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_FKPUR,2026-04-20,2026-04-13,SPS,30.0,8.0,3480.0,21.0,Satellitehub_FKPUR,Satellitehub_FKPUR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-19,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaN,NaN

In [50]:
#drf1['Date']=pd.to_datetime(drf1['Date']).dt.date
drf1['Date'] = pd.to_datetime(drf1['Date'], format='%d-%m-%Y').dt.date
drf1['check2']=np.where((drf1['Date'] > drf1['Latest_Update_Time']),True,False)
drf1['Current_Location']=np.where((drf1['check2']==True),drf1.Facility,drf1.Current_Location)
#drf2['Merged_current_location']=drf2['Merged_current_location'].fillna(drf2['Current_Location'])
drf1

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,first_ph_in_post_rto_hub_name,first_ph_in_post_rto_datetime,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor,ERP_Status,Final_Status,Unnamed: 0,Timestamp,AWB_TID_number,Issue_Category,Status,Reason,PH_or_DH,Seller_type,Payment_Mode,Customer Code,shipment_value_1,todays_date,ageing_1,Ageing_bucket,loss,child_count,logistics_breach_bucket,last_scan_ageing,last_scan_ageing_bucket,Shipment/Bag ID,Date,Facility,check2
0,TFC001512055,NaN,AMAP0000000577,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-06-15,ShipmentDelivered,110086.0,Delhi,DELHI,560068.0,BANGALORE,KARNATAKA,2026-06-10,1.0,2026-06-10,2026-06-10,2026-06-10,2026-06-15T05:01:43.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T14:44:54.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5510.25,0.0,19000.0,METRO,False,NaN,2026-06-15T03:15:00+0530,PICKUPHUB_RPBAGHFM,BulkHub_BLR,2026-06-15,2026-06-10,SPS,120.0,25.0,19000.0,25.0,BulkHub_BLR,BulkHub_BLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-10,delivered,2026-06-15,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,37,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaT,NaN,False
1,TFC001512213,NaN,AMAP0000000819,FSD_LARGE,AMA,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-07-05,ShipmentDelivered,110086.0,Delhi,DELHI,580023.0,DHARWAD,KARNATAKA,2026-06-30,1.0,2026-06-30,2026-06-30,2026-06-30,2026-07-05T05:25:29.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T18:00:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5628.75,0.0,13000.0,ROI,False,NaN,2026-07-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_FKHBLA,2026-07-05,2026-06-30,SPS,110.0,20.0,13000.0,20.0,SATELLITEHUB_FKHBLA,SATELLITEHUB_FKHBLA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-30,delivered,2026-07-05,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,17,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaT,NaN,False
2,940069,NaN,ARLP0000003366,FSD_LARGE,ARL,SINGER COOKMATE 5L,SINGER COOKMATE 5L,ext_sps,ARL,ARL : ARL_THA_01,ARL_448c561fc19f951b85377ebb5382e9af,Forward,SHIPMENT,PP,N,True,2026-06-12,ShipmentDelivered,401105.0,Thane,MAHARASHTRA,800007.0,PATNA,BIHAR,2026-06-03,1.0,2026-06-03,2026-06-04,2026-06-04,2026-06-12T05:01:52.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T18:26:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2784.00,0.0,2600.0,ROI,False,NaN,2026-06-13T03:15:00+0530,Pickuphub_FKMIB,SatelliteHub_PAT,2026-06-13,2026-06-04,SPS,45.0,20.0,2600.0,25.0,SatelliteHub_PAT,SatelliteHub_PAT,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-04,delivered,2026-06-12,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,44,<=45,Null,1,2000.0,-1.0,ageing 0,NaN,NaT,NaN,False
3,ORD-SO-813176,NaN,AWPC0000077622,FSD_LARGE,AWP,Hymatic Single Battery 12X8 16 Ltr Battery Ope...,ATE3A59AE91CK26A71A05,ext_sps,AWP,AWP : Patna WH,AWP_06690e9940963d92d58bcb3a6563d29c,Forward,SHIPMENT,COD,Z,True,2026-07-11,ShipmentDelivered,803201.0,Patna,BIHAR,851213.0,KHAGARIA,BIHAR,2026-07-08,1.0,2026-07-08,2026-07-08,2026-07-08,2026-07-11T07:45:01.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T22:05:14.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4874.00,3874.0,24450.0,ZONAL,False,NaN,2026-07-14T03:15:00+0530,PickupHub_PAT,SATELLITEHUB_KGG,2026-07-14,2026-07-08,SPS,64.0,49.0,24450.0,39.0,SATELLITEHUB_KGG,SATELLITEHUB_KGG,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-08,delivered,2026-07-11,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,9,<=45,Null,1,4874.0,-1.0,ageing 0,NaN,NaT,NaN,False
4,ORD-SO-796826,NaN,AWPC0000078604,FSD_LARGE,AWP,BALWAAN DOUBLE BATTERY-DOUBLE MOTOR BS-22D 12X...,ATE3A59AB38GD97A63A05,ext_sps,AWP,AWP : Rohit Bajaj,AWP_85296f55bcc56dc187a14f2f9c6e8299,Forward,SHIPMENT,COD,Z,True,2026-07-08,ShipmentDelivered,711302.0,Howrah,WEST BENGAL,848201.0,BEGUSARAI,BIHAR,2026-07-01,4.0,2026-07-01,2026-07-04,2026-07-04,2026-07-08T06:33:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T22:24:37.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,7370.00,6870.0,29172.0,ZONAL,False,NaN,2026-07-11T03:15:00+0530,PickupHub_FKHWH,Satellitehub_FKBEGU,2026-07-11,2026-07-04,SPS,64.0,53.0,29172.0,43.0,Satellitehub_FKBEGU,Satellitehub_FKBEGU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-04,delivered,2026-07-08,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,16,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaT,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921759,XPYE2ETDDR8JIQTK,NaN,UNCP0000314145,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,302021.0,JAIPUR,RAJASTHAN,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-18T02:09:37.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T15:45:26.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JAI,2026-04-19,2026-04-13,SPS,30.0,8.0,3480.0,21.0,SatelliteHub_JAI,SatelliteHub_JAI,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False
921760,CP66PCOX4L,NaN,UNCP0000314813,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-01,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,274301.0,DEORIA,UTTAR PRADESH,2026-04-14,3.0,2026-04-14,2026-04-17,2026-04-17,2026-04-30T23:56:26.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T21:43:49.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-28T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_KUSHINAGAR,2026-04-28,2026-04-17,SPS,20.0,19.0,6640.0,26.0,SATELLITEHUB_KUSHINAGAR,SATELLITEHUB_KUSHINAGAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-01,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,94,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False
921761,E5VOT73QQV,NaN,UNCP0000314816,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-07,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,805110.0,NAWADA,BIHAR,2026-04-14,3.0,2026-04-14,2026-04-17,2026-04-17,2026-05-07T06:00:49.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T18:25:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-26T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_FKNWD,2026-04-26,2026-04-17,SPS,20.0,19.0,6640.0,26.0,Satellitehub_FKNWD,Satellitehub_FKNWD,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-07,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,94,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False
921762,5XYZFK5V3Y0NOT0N,NaN,UNCP0000314002,FSD_LARGE,UNC,GATE ELECTRICAL,GATE ELECTRICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,382330.0,AHMEDABAD,GUJARAT,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-18T07:53:46.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T23:10:07.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,5710.0,METRO,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_NAR,2026-04-19,2026-04-13,SPS,19.0,18.0,5710.0,25.0,SatelliteHub_NAR,SatelliteHub_NAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False
921763,WETER7WN993JO9OG,NaN,UNCP0000314142,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-19,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,752001.0,PURI,ODISHA,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-19T04:27:51.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T18:09:19.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-20T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_FKPUR,2026-04-20,2026-04-13,SPS,30.0,8.0,3480.0,21.0,Satellitehub_FKPUR,Satellitehub_FKPUR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-19,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False

In [51]:
map1=pd.read_excel("Large XD mapping.xlsx")
map1['Hub name']=map1['Hub name'].str.lower()
map1

drf1['Current_Location']=drf1['Current_Location'].str.lower()
drf2=drf1.merge(map1[['Hub name']],left_on='Current_Location',right_on='Hub name',how='left')
drf2

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,first_ph_in_post_rto_hub_name,first_ph_in_post_rto_datetime,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor,ERP_Status,Final_Status,Unnamed: 0,Timestamp,AWB_TID_number,Issue_Category,Status,Reason,PH_or_DH,Seller_type,Payment_Mode,Customer Code,shipment_value_1,todays_date,ageing_1,Ageing_bucket,loss,child_count,logistics_breach_bucket,last_scan_ageing,last_scan_ageing_bucket,Shipment/Bag ID,Date,Facility,check2,Hub name
0,TFC001512055,NaN,AMAP0000000577,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-06-15,ShipmentDelivered,110086.0,Delhi,DELHI,560068.0,BANGALORE,KARNATAKA,2026-06-10,1.0,2026-06-10,2026-06-10,2026-06-10,2026-06-15T05:01:43.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T14:44:54.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5510.25,0.0,19000.0,METRO,False,NaN,2026-06-15T03:15:00+0530,PICKUPHUB_RPBAGHFM,BulkHub_BLR,2026-06-15,2026-06-10,SPS,120.0,25.0,19000.0,25.0,BulkHub_BLR,BulkHub_BLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-10,delivered,2026-06-15,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,37,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN
1,TFC001512213,NaN,AMAP0000000819,FSD_LARGE,AMA,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-07-05,ShipmentDelivered,110086.0,Delhi,DELHI,580023.0,DHARWAD,KARNATAKA,2026-06-30,1.0,2026-06-30,2026-06-30,2026-06-30,2026-07-05T05:25:29.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T18:00:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5628.75,0.0,13000.0,ROI,False,NaN,2026-07-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_FKHBLA,2026-07-05,2026-06-30,SPS,110.0,20.0,13000.0,20.0,SATELLITEHUB_FKHBLA,SATELLITEHUB_FKHBLA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-30,delivered,2026-07-05,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,17,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN
2,940069,NaN,ARLP0000003366,FSD_LARGE,ARL,SINGER COOKMATE 5L,SINGER COOKMATE 5L,ext_sps,ARL,ARL : ARL_THA_01,ARL_448c561fc19f951b85377ebb5382e9af,Forward,SHIPMENT,PP,N,True,2026-06-12,ShipmentDelivered,401105.0,Thane,MAHARASHTRA,800007.0,PATNA,BIHAR,2026-06-03,1.0,2026-06-03,2026-06-04,2026-06-04,2026-06-12T05:01:52.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T18:26:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2784.00,0.0,2600.0,ROI,False,NaN,2026-06-13T03:15:00+0530,Pickuphub_FKMIB,SatelliteHub_PAT,2026-06-13,2026-06-04,SPS,45.0,20.0,2600.0,25.0,SatelliteHub_PAT,SatelliteHub_PAT,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-04,delivered,2026-06-12,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,44,<=45,Null,1,2000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN
3,ORD-SO-813176,NaN,AWPC0000077622,FSD_LARGE,AWP,Hymatic Single Battery 12X8 16 Ltr Battery Ope...,ATE3A59AE91CK26A71A05,ext_sps,AWP,AWP : Patna WH,AWP_06690e9940963d92d58bcb3a6563d29c,Forward,SHIPMENT,COD,Z,True,2026-07-11,ShipmentDelivered,803201.0,Patna,BIHAR,851213.0,KHAGARIA,BIHAR,2026-07-08,1.0,2026-07-08,2026-07-08,2026-07-08,2026-07-11T07:45:01.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T22:05:14.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4874.00,3874.0,24450.0,ZONAL,False,NaN,2026-07-14T03:15:00+0530,PickupHub_PAT,SATELLITEHUB_KGG,2026-07-14,2026-07-08,SPS,64.0,49.0,24450.0,39.0,SATELLITEHUB_KGG,SATELLITEHUB_KGG,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-08,delivered,2026-07-11,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,9,<=45,Null,1,4874.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN
4,ORD-SO-796826,NaN,AWPC0000078604,FSD_LARGE,AWP,BALWAAN DOUBLE BATTERY-DOUBLE MOTOR BS-22D 12X...,ATE3A59AB38GD97A63A05,ext_sps,AWP,AWP : Rohit Bajaj,AWP_85296f55bcc56dc187a14f2f9c6e8299,Forward,SHIPMENT,COD,Z,True,2026-07-08,ShipmentDelivered,711302.0,Howrah,WEST BENGAL,848201.0,BEGUSARAI,BIHAR,2026-07-01,4.0,2026-07-01,2026-07-04,2026-07-04,2026-07-08T06:33:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T22:24:37.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,7370.00,6870.0,29172.0,ZONAL,False,NaN,2026-07-11T03:15:00+0530,PickupHub_FKHWH,Satellitehub_FKBEGU,2026-07-11,2026-07-04,SPS,64.0,53.0,29172.0,43.0,Satellitehub_FKBEGU,Satellitehub_FKBEGU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-04,delivered,2026-07-08,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,16,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921759,XPYE2ETDDR8JIQTK,NaN,UNCP0000314145,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,302021.0,JAIPUR,RAJASTHAN,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-18T02:09:37.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T15:45:26.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JAI,2026-04-19,2026-04-13,SPS,30.0,8.0,3480.0,21.0,SatelliteHub_JAI,SatelliteHub_JAI,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN
921760,CP66PCOX4L,NaN,UNCP0000314813,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-01,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,274301.0,DEORIA,UTTAR PRADESH,2026-04-14,3.0,2026-04-14,2026-04-17,2026-04-17,2026-04-30T23:56:26.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T21:43:49.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-28T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_KUSHINAGAR,2026-04-28,2026-04-17,SPS,20.0,19.0,6640.0,26.0,SATELLITEHUB_KUSHINAGAR,SATELLITEHUB_KUSHINAGAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-01,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,94,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN
921761,E5VOT73QQV,NaN,UNCP0000314816,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-07,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,805110.0,NAWADA,BIHAR,2026-04-14,3.0,2026-04-14,2026-04-17,2026-04-17,2026-05-07T06:00:49.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T18:25:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-26T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_FKNWD,2026-04-26,2026-04-17,SPS,20.0,19.0,6640.0,26.0,Satellitehub_FKNWD,Satellitehub_FKNWD,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-07,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,94,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN
921762,5XYZFK5V3Y0NOT0N,NaN,UNCP0000314002,FSD_LARGE,UNC,GATE ELECTRICAL,GATE ELECTRICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,382330.0,AHMEDABAD,GUJARAT,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-18T07:53:46.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T23:10:07.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,5710.0,METRO,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_NAR,2026-04-19,2026-04-13,SPS,19.0,18.0,5710.0,25.0,SatelliteHub_NAR,SatelliteHub_NAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN
921763,WETER7WN993JO9OG,NaN,UNCP0000314142,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-19,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,752001.0,PURI,ODISHA,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-19T04:27:51.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T18:09:19.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-20T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_FKPUR,2026-04-20,2026-04-13,SPS,30.0,8.0,3480.0,21.0,Satellitehub_FKPUR,Satellitehub_FKPUR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-19,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN

In [52]:
drf2['Pickup_hub']=drf2['Pickup_hub'].str.lower()
drf2['Pickuphub_new'] = drf2['Pickup_hub'].str.split('_').str[-1].str.rstrip('0123456789')
drf2['Current_loc_new'] = drf2['Current_Location'].str.split('_').str[-1].str.rstrip('0123456789')

drf2['check']=drf2['Pickuphub_new']==drf2['Current_loc_new']

satellite_bulk_condition = drf2['Current_Location'].str.startswith(('satellitehub', 'bulkhub'))
check_condition = ~(drf2['Latest_Status'] == 'Expected') & (drf2['check'] == True)  
hub_name_condition = drf2['Hub name'].notnull()
expected = (drf2['Latest_Status'] == 'Expected') & (drf2['Current_Location'].str.startswith(('satellitehub', 'bulkhub')))
expected1 = (drf2['Latest_Status'] == 'Expected') & (drf2['check'] == True)
expected2 = (drf2['Latest_Status'] == 'Expected') & (drf2['Hub name'].notnull())

drf2['Asset'] =np.where(expected,'In Transit LM',
               np.where(expected1,'In Transit FM',
               np.where(expected2,'In Transit XD',
                np.where(satellite_bulk_condition, 'AT LM',
               np.where(check_condition, 'AT FM',
               np.where(hub_name_condition, 'AT XD','Nan'))))))

drf2.Asset.value_counts()

Asset
Nan              863289
In Transit XD     19932
AT LM             17854
AT XD             13999
AT FM              2976
In Transit LM      2415
In Transit FM      1299
Name: count, dtype: int64

In [53]:
fi=drf2[['shipment_value','logistics_breach_bucket']]
fi

        shipment_value  logistics_breach_bucket
0              5510.25                   5000.0
1              5628.75                   5000.0
2              2784.00                   2000.0
3              4874.00                   4874.0
4              7370.00                   5000.0
...                ...                      ...
921759         3000.00                   3000.0
921760         3000.00                   3000.0
921761         3000.00                   3000.0
921762         3000.00                   3000.0
921763         3000.00                   3000.0

[921764 rows x 2 columns]

In [54]:
# ==============================================================================
# 🎯 CRASH-PROOF COMBINED FIX FOR DATAFRAME: drf2
# ==============================================================================

# Step 1: Clean column names to prevent hidden space errors
drf2.columns = [str(col).strip() for col in drf2.columns]

# ------------------------------------------------------------------------------
# 📈 TASK 1: EXTRACT DATE FROM ph_in_time FOR BLANKS IN ph_in_date_final
# ------------------------------------------------------------------------------
# Safety: Create 'ph_in_date_final' if it doesn't exist in this file
if "ph_in_date_final" not in drf2.columns:
    drf2["ph_in_date_final"] = pd.NA

# Treat empty spaces/strings as true blanks (NaN)
drf2["ph_in_date_final"] = drf2["ph_in_date_final"].astype(str).str.strip()
drf2["ph_in_date_final"] = drf2["ph_in_date_final"].replace(['nan', 'None', '', 'NaT'], pd.NA)

# Find where the date column is blank
date_blanks = drf2["ph_in_date_final"].isna()

# Parse timestamps dynamically and fill only those blank rows
if "ph_in_time" in drf2.columns:
    extracted_dates = pd.to_datetime(
        drf2.loc[date_blanks, "ph_in_time"], 
        dayfirst=True, 
        errors='coerce'
    ).dt.strftime("%Y-%m-%d")

    drf2.loc[date_blanks, "ph_in_date_final"] = extracted_dates

drf2["ph_in_date_final"] = drf2["ph_in_date_final"].fillna("")


# ------------------------------------------------------------------------------
# 🔄 TASK 2: FILL BLANKS IN No. of Attempts FROM fsd_number_of_ofd_attempts
# ------------------------------------------------------------------------------
# Safety: If "No. of Attempts" doesn't exist at all, initialize it as empty
if "No._of_Attempts" not in drf2.columns:
    drf2["No._of_Attempts"] = pd.NA

# Treat empty strings as true blanks (NaN)
drf2["No._of_Attempts"] = drf2["No._of_Attempts"].astype(str).str.strip()
drf2["No._of_Attempts"] = drf2["No._of_Attempts"].replace(['nan', 'None', '', 'NaT'], pd.NA)

# Fill empty slots using the data from fsd_number_of_ofd_attempts
if "fsd_number_of_ofd_attempts" in drf2.columns:
    drf2["No._of_Attempts"] = drf2["No._of_Attempts"].fillna(drf2["fsd_number_of_ofd_attempts"])
else:
    print("⚠️ Warning: 'fsd_number_of_ofd_attempts' column was not found in drf2!")

print("🎯 Success! Logic applied to drf2 safely without crashes.")

🎯 Success! Logic applied to drf2 safely without crashes.

In [55]:
drf2

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,first_ph_in_post_rto_hub_name,first_ph_in_post_rto_datetime,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor,ERP_Status,Final_Status,Unnamed: 0,Timestamp,AWB_TID_number,Issue_Category,Status,Reason,PH_or_DH,Seller_type,Payment_Mode,Customer Code,shipment_value_1,todays_date,ageing_1,Ageing_bucket,loss,child_count,logistics_breach_bucket,last_scan_ageing,last_scan_ageing_bucket,Shipment/Bag ID,Date,Facility,check2,Hub name,Pickuphub_new,Current_loc_new,check,Asset
0,TFC001512055,NaN,AMAP0000000577,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-06-15,ShipmentDelivered,110086.0,Delhi,DELHI,560068.0,BANGALORE,KARNATAKA,2026-06-10,1.0,2026-06-10,2026-06-10,2026-06-10,2026-06-15T05:01:43.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T14:44:54.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5510.25,0.0,19000.0,METRO,False,NaN,2026-06-15T03:15:00+0530,pickuphub_rpbaghfm,BulkHub_BLR,2026-06-15,2026-06-10,SPS,120.0,25.0,19000.0,25.0,BulkHub_BLR,BulkHub_BLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-10,delivered,2026-06-15,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,37,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,rpbaghfm,NaN,False,Nan
1,TFC001512213,NaN,AMAP0000000819,FSD_LARGE,AMA,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-07-05,ShipmentDelivered,110086.0,Delhi,DELHI,580023.0,DHARWAD,KARNATAKA,2026-06-30,1.0,2026-06-30,2026-06-30,2026-06-30,2026-07-05T05:25:29.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T18:00:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5628.75,0.0,13000.0,ROI,False,NaN,2026-07-05T03:15:00+0530,pickuphub_rpbaghfm,SATELLITEHUB_FKHBLA,2026-07-05,2026-06-30,SPS,110.0,20.0,13000.0,20.0,SATELLITEHUB_FKHBLA,SATELLITEHUB_FKHBLA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-30,delivered,2026-07-05,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,17,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,rpbaghfm,NaN,False,Nan
2,940069,NaN,ARLP0000003366,FSD_LARGE,ARL,SINGER COOKMATE 5L,SINGER COOKMATE 5L,ext_sps,ARL,ARL : ARL_THA_01,ARL_448c561fc19f951b85377ebb5382e9af,Forward,SHIPMENT,PP,N,True,2026-06-12,ShipmentDelivered,401105.0,Thane,MAHARASHTRA,800007.0,PATNA,BIHAR,2026-06-03,1.0,2026-06-03,2026-06-04,2026-06-04,2026-06-12T05:01:52.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T18:26:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2784.00,0.0,2600.0,ROI,False,NaN,2026-06-13T03:15:00+0530,pickuphub_fkmib,SatelliteHub_PAT,2026-06-13,2026-06-04,SPS,45.0,20.0,2600.0,25.0,SatelliteHub_PAT,SatelliteHub_PAT,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-04,delivered,2026-06-12,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,44,<=45,Null,1,2000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkmib,NaN,False,Nan
3,ORD-SO-813176,NaN,AWPC0000077622,FSD_LARGE,AWP,Hymatic Single Battery 12X8 16 Ltr Battery Ope...,ATE3A59AE91CK26A71A05,ext_sps,AWP,AWP : Patna WH,AWP_06690e9940963d92d58bcb3a6563d29c,Forward,SHIPMENT,COD,Z,True,2026-07-11,ShipmentDelivered,803201.0,Patna,BIHAR,851213.0,KHAGARIA,BIHAR,2026-07-08,1.0,2026-07-08,2026-07-08,2026-07-08,2026-07-11T07:45:01.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T22:05:14.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4874.00,3874.0,24450.0,ZONAL,False,NaN,2026-07-14T03:15:00+0530,pickuphub_pat,SATELLITEHUB_KGG,2026-07-14,2026-07-08,SPS,64.0,49.0,24450.0,39.0,SATELLITEHUB_KGG,SATELLITEHUB_KGG,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-08,delivered,2026-07-11,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,9,<=45,Null,1,4874.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,pat,NaN,False,Nan
4,ORD-SO-796826,NaN,AWPC0000078604,FSD_LARGE,AWP,BALWAAN DOUBLE BATTERY-DOUBLE MOTOR BS-22D 12X...,ATE3A59AB38GD97A63A05,ext_sps,AWP,AWP : Rohit Bajaj,AWP_85296f55bcc56dc187a14f2f9c6e8299,Forward,SHIPMENT,COD,Z,True,2026-07-08,ShipmentDelivered,711302.0,Howrah,WEST BENGAL,848201.0,BEGUSARAI,BIHAR,2026-07-01,4.0,2026-07-01,2026-07-04,2026-07-04,2026-07-08T06:33:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T22:24:37.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,7370.00,6870.0,29172.0,ZONAL,False,NaN,2026-07-11T03:15:00+0530,pickuphub_fkhwh,Satellitehub_FKBEGU,2026-07-11,2026-07-04,SPS,64.0,53.0,29172.0,43.0,Satellitehub_FKBEGU,Satellitehub_FKBEGU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-04,delivered,2026-07-08,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,16,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkhwh,NaN,False,Nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921759,XPYE2ETDDR8JIQTK,NaN,UNCP0000314145,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,302021.0,JAIPUR,RAJASTHAN,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-18T02:09:37.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T15:45:26.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-19T03:15:00+0530,pickuphub_fkbgr2,SatelliteHub_JAI,2026-04-19,2026-04-13,SPS,30.0,8.0,3480.0,21.0,SatelliteHub_JAI,SatelliteHub_JAI,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan
921760,CP66PCOX4L,NaN,UNCP0000314813,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-01,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,274301.0,DEORIA,UTTAR PRADESH,2026-04-14,3.0,2026-04-14,2026-04-17,2026-04-17,2026-04-30T23:56:26.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T21:43:49.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-28T03:15:00+0530,pickuphub_fkbgr2,SATELLITEHUB_KUSHINAGAR,2026-04-28,2026-04-17,SPS,20.0,19.0,6640.0,26.0,SATELLITEHUB_KUSHINAGAR,SATELLITEHUB_KUSHINAGAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-01,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,94,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan
921761,E5VOT73QQV,NaN,UNCP0000314816,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-07,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,805110.0,NAWADA,BIHAR,2026-04-14,3.0,2026-04-14,2026-04-17,2026-04-17,2026-05-07T06:00:49.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T18:25:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-26T03:15:00+0530,pickuphub_fkbgr2,Satellitehub_FKNWD,2026-04-26,2026-04-17,SPS,20.0,19.0,6640.0,26.0,Satellitehub_FKNWD,Satellitehub_FKNWD,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-07,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,94,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan
921762,5XYZFK5V3Y0NOT0N,NaN,UNCP0000314002,FSD_LARGE,UNC,GATE ELECTRICAL,GATE ELECTRICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,382330.0,AHMEDABAD,GUJARAT,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-18T07:53:46.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T23:10:07.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,5710.0,METRO,False,NaN,2026-04-19T03:15:00+0530,pickuphub_fkbgr2,SatelliteHub_NAR,2026-04-19,2026-04-13,SPS,19.0,18.0,5710.0,25.0,SatelliteHub_NAR,SatelliteHub_NAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan
921763,WETER7WN993JO9OG,NaN,UNCP0000314142,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-19,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,752001.0,PURI,ODISHA,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-19T04:27:51.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T18:09:19.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-20T03:15:00+0530,pickuphub_fkbgr2,Satellitehub_FKPUR,2026-04-20,2026-04-13,SPS,30.0,8.0,3480.0,21.0,Satellitehub_FKPUR,Satellitehub_FKPUR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-19,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan

In [56]:
import pandas as pd

# Load Zone Mapping
zone_mapping = pd.read_excel('Zone Mapping.xlsx', sheet_name='Sheet1')
zone_mapping.columns = ['pincode', 'zone']
zone_mapping['pincode'] = zone_mapping['pincode'].astype(int)

# Normalize dest_pincode to int for matching
drf2['dest_pincode'] = drf2['dest_pincode'].astype(float).astype('Int64')

# Map zone
drf2['dest_zone'] = drf2['dest_pincode'].map(zone_mapping.set_index('pincode')['zone'])

# Insert dest_zone right after dest_pincode
col = drf2.pop('dest_zone')
dest_pincode_idx = drf2.columns.get_loc('dest_pincode')
drf2.insert(dest_pincode_idx + 1, 'dest_zone', col)

# Verify
print(drf2[['dest_pincode', 'dest_zone']].head(10))
print(f"\nUnmapped rows: {drf2['dest_zone'].isna().sum()} / {len(drf2)}")

   dest_pincode dest_zone
0        560068     South
1        580023     South
2        800007      East
3        851213      East
4        848201      East
5        712410      East
6        843121      East
7        847302      East
8        243303     North
9        825301      East

Unmapped rows: 0 / 921764

In [57]:
drf2

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_zone,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,first_ph_in_post_rto_hub_name,first_ph_in_post_rto_datetime,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor,ERP_Status,Final_Status,Unnamed: 0,Timestamp,AWB_TID_number,Issue_Category,Status,Reason,PH_or_DH,Seller_type,Payment_Mode,Customer Code,shipment_value_1,todays_date,ageing_1,Ageing_bucket,loss,child_count,logistics_breach_bucket,last_scan_ageing,last_scan_ageing_bucket,Shipment/Bag ID,Date,Facility,check2,Hub name,Pickuphub_new,Current_loc_new,check,Asset
0,TFC001512055,NaN,AMAP0000000577,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-06-15,ShipmentDelivered,110086.0,Delhi,DELHI,560068,South,BANGALORE,KARNATAKA,2026-06-10,1.0,2026-06-10,2026-06-10,2026-06-10,2026-06-15T05:01:43.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T14:44:54.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5510.25,0.0,19000.0,METRO,False,NaN,2026-06-15T03:15:00+0530,pickuphub_rpbaghfm,BulkHub_BLR,2026-06-15,2026-06-10,SPS,120.0,25.0,19000.0,25.0,BulkHub_BLR,BulkHub_BLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-10,delivered,2026-06-15,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,37,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,rpbaghfm,NaN,False,Nan
1,TFC001512213,NaN,AMAP0000000819,FSD_LARGE,AMA,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-07-05,ShipmentDelivered,110086.0,Delhi,DELHI,580023,South,DHARWAD,KARNATAKA,2026-06-30,1.0,2026-06-30,2026-06-30,2026-06-30,2026-07-05T05:25:29.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T18:00:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5628.75,0.0,13000.0,ROI,False,NaN,2026-07-05T03:15:00+0530,pickuphub_rpbaghfm,SATELLITEHUB_FKHBLA,2026-07-05,2026-06-30,SPS,110.0,20.0,13000.0,20.0,SATELLITEHUB_FKHBLA,SATELLITEHUB_FKHBLA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-30,delivered,2026-07-05,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,17,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,rpbaghfm,NaN,False,Nan
2,940069,NaN,ARLP0000003366,FSD_LARGE,ARL,SINGER COOKMATE 5L,SINGER COOKMATE 5L,ext_sps,ARL,ARL : ARL_THA_01,ARL_448c561fc19f951b85377ebb5382e9af,Forward,SHIPMENT,PP,N,True,2026-06-12,ShipmentDelivered,401105.0,Thane,MAHARASHTRA,800007,East,PATNA,BIHAR,2026-06-03,1.0,2026-06-03,2026-06-04,2026-06-04,2026-06-12T05:01:52.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T18:26:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2784.00,0.0,2600.0,ROI,False,NaN,2026-06-13T03:15:00+0530,pickuphub_fkmib,SatelliteHub_PAT,2026-06-13,2026-06-04,SPS,45.0,20.0,2600.0,25.0,SatelliteHub_PAT,SatelliteHub_PAT,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-04,delivered,2026-06-12,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,44,<=45,Null,1,2000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkmib,NaN,False,Nan
3,ORD-SO-813176,NaN,AWPC0000077622,FSD_LARGE,AWP,Hymatic Single Battery 12X8 16 Ltr Battery Ope...,ATE3A59AE91CK26A71A05,ext_sps,AWP,AWP : Patna WH,AWP_06690e9940963d92d58bcb3a6563d29c,Forward,SHIPMENT,COD,Z,True,2026-07-11,ShipmentDelivered,803201.0,Patna,BIHAR,851213,East,KHAGARIA,BIHAR,2026-07-08,1.0,2026-07-08,2026-07-08,2026-07-08,2026-07-11T07:45:01.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T22:05:14.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4874.00,3874.0,24450.0,ZONAL,False,NaN,2026-07-14T03:15:00+0530,pickuphub_pat,SATELLITEHUB_KGG,2026-07-14,2026-07-08,SPS,64.0,49.0,24450.0,39.0,SATELLITEHUB_KGG,SATELLITEHUB_KGG,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-08,delivered,2026-07-11,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,9,<=45,Null,1,4874.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,pat,NaN,False,Nan
4,ORD-SO-796826,NaN,AWPC0000078604,FSD_LARGE,AWP,BALWAAN DOUBLE BATTERY-DOUBLE MOTOR BS-22D 12X...,ATE3A59AB38GD97A63A05,ext_sps,AWP,AWP : Rohit Bajaj,AWP_85296f55bcc56dc187a14f2f9c6e8299,Forward,SHIPMENT,COD,Z,True,2026-07-08,ShipmentDelivered,711302.0,Howrah,WEST BENGAL,848201,East,BEGUSARAI,BIHAR,2026-07-01,4.0,2026-07-01,2026-07-04,2026-07-04,2026-07-08T06:33:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T22:24:37.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,7370.00,6870.0,29172.0,ZONAL,False,NaN,2026-07-11T03:15:00+0530,pickuphub_fkhwh,Satellitehub_FKBEGU,2026-07-11,2026-07-04,SPS,64.0,53.0,29172.0,43.0,Satellitehub_FKBEGU,Satellitehub_FKBEGU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-04,delivered,2026-07-08,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,16,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkhwh,NaN,False,Nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921759,XPYE2ETDDR8JIQTK,NaN,UNCP0000314145,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,302021,North,JAIPUR,RAJASTHAN,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-18T02:09:37.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T15:45:26.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-19T03:15:00+0530,pickuphub_fkbgr2,SatelliteHub_JAI,2026-04-19,2026-04-13,SPS,30.0,8.0,3480.0,21.0,SatelliteHub_JAI,SatelliteHub_JAI,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan
921760,CP66PCOX4L,NaN,UNCP0000314813,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-01,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,274301,North,DEORIA,UTTAR PRADESH,2026-04-14,3.0,2026-04-14,2026-04-17,2026-04-17,2026-04-30T23:56:26.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T21:43:49.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-28T03:15:00+0530,pickuphub_fkbgr2,SATELLITEHUB_KUSHINAGAR,2026-04-28,2026-04-17,SPS,20.0,19.0,6640.0,26.0,SATELLITEHUB_KUSHINAGAR,SATELLITEHUB_KUSHINAGAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-01,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,94,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan
921761,E5VOT73QQV,NaN,UNCP0000314816,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-07,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,805110,East,NAWADA,BIHAR,2026-04-14,3.0,2026-04-14,2026-04-17,2026-04-17,2026-05-07T06:00:49.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T18:25:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-26T03:15:00+0530,pickuphub_fkbgr2,Satellitehub_FKNWD,2026-04-26,2026-04-17,SPS,20.0,19.0,6640.0,26.0,Satellitehub_FKNWD,Satellitehub_FKNWD,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-07,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,94,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan
921762,5XYZFK5V3Y0NOT0N,NaN,UNCP0000314002,FSD_LARGE,UNC,GATE ELECTRICAL,GATE ELECTRICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,382330,West,AHMEDABAD,GUJARAT,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-18T07:53:46.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T23:10:07.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,5710.0,METRO,False,NaN,2026-04-19T03:15:00+0530,pickuphub_fkbgr2,SatelliteHub_NAR,2026-04-19,2026-04-13,SPS,19.0,18.0,5710.0,25.0,SatelliteHub_NAR,SatelliteHub_NAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan
921763,WETER7WN993JO9OG,NaN,UNCP0000314142,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-19,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,752001,East,PURI,ODISHA,2026-04-10,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-19T04:27:51.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T18:09:19.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-20T03:15:00+0530,pickuphub_fkbgr2,Satellitehub_FKPUR,2026-04-20,2026-04-13,SPS,30.0,8.0,3480.0,21.0,Satellitehub_FKPUR,Satellitehub_FKPUR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-19,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan

In [58]:
# Add week number based on current year start (Jan 1, 2026)
drf2['week_no'] = ((pd.to_datetime(drf2['created_at']) - pd.Timestamp('2026-01-01')) / pd.Timedelta(weeks=1)).apply(lambda x: int(x) + 1)

# Insert after created_at
col = drf2.pop('week_no')
created_at_idx = drf2.columns.get_loc('created_at')
drf2.insert(created_at_idx + 1, 'week_no', col)

print(drf2[['created_at', 'week_no']].head(10))

   created_at  week_no
0  2026-06-10       23
1  2026-06-30       26
2  2026-06-03       22
3  2026-07-08       27
4  2026-07-01       26
5  2026-06-26       26
6  2026-06-26       26
7  2026-06-24       25
8  2026-06-22       25
9  2026-06-22       25

In [59]:
drf2

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_zone,dest_city,dest_state,created_at,week_no,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,first_ph_in_post_rto_hub_name,first_ph_in_post_rto_datetime,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor,ERP_Status,Final_Status,Unnamed: 0,Timestamp,AWB_TID_number,Issue_Category,Status,Reason,PH_or_DH,Seller_type,Payment_Mode,Customer Code,shipment_value_1,todays_date,ageing_1,Ageing_bucket,loss,child_count,logistics_breach_bucket,last_scan_ageing,last_scan_ageing_bucket,Shipment/Bag ID,Date,Facility,check2,Hub name,Pickuphub_new,Current_loc_new,check,Asset
0,TFC001512055,NaN,AMAP0000000577,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-06-15,ShipmentDelivered,110086.0,Delhi,DELHI,560068,South,BANGALORE,KARNATAKA,2026-06-10,23,1.0,2026-06-10,2026-06-10,2026-06-10,2026-06-15T05:01:43.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T14:44:54.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5510.25,0.0,19000.0,METRO,False,NaN,2026-06-15T03:15:00+0530,pickuphub_rpbaghfm,BulkHub_BLR,2026-06-15,2026-06-10,SPS,120.0,25.0,19000.0,25.0,BulkHub_BLR,BulkHub_BLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-10,delivered,2026-06-15,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,37,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,rpbaghfm,NaN,False,Nan
1,TFC001512213,NaN,AMAP0000000819,FSD_LARGE,AMA,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-07-05,ShipmentDelivered,110086.0,Delhi,DELHI,580023,South,DHARWAD,KARNATAKA,2026-06-30,26,1.0,2026-06-30,2026-06-30,2026-06-30,2026-07-05T05:25:29.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T18:00:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5628.75,0.0,13000.0,ROI,False,NaN,2026-07-05T03:15:00+0530,pickuphub_rpbaghfm,SATELLITEHUB_FKHBLA,2026-07-05,2026-06-30,SPS,110.0,20.0,13000.0,20.0,SATELLITEHUB_FKHBLA,SATELLITEHUB_FKHBLA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-30,delivered,2026-07-05,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,17,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,rpbaghfm,NaN,False,Nan
2,940069,NaN,ARLP0000003366,FSD_LARGE,ARL,SINGER COOKMATE 5L,SINGER COOKMATE 5L,ext_sps,ARL,ARL : ARL_THA_01,ARL_448c561fc19f951b85377ebb5382e9af,Forward,SHIPMENT,PP,N,True,2026-06-12,ShipmentDelivered,401105.0,Thane,MAHARASHTRA,800007,East,PATNA,BIHAR,2026-06-03,22,1.0,2026-06-03,2026-06-04,2026-06-04,2026-06-12T05:01:52.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T18:26:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2784.00,0.0,2600.0,ROI,False,NaN,2026-06-13T03:15:00+0530,pickuphub_fkmib,SatelliteHub_PAT,2026-06-13,2026-06-04,SPS,45.0,20.0,2600.0,25.0,SatelliteHub_PAT,SatelliteHub_PAT,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-04,delivered,2026-06-12,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,44,<=45,Null,1,2000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkmib,NaN,False,Nan
3,ORD-SO-813176,NaN,AWPC0000077622,FSD_LARGE,AWP,Hymatic Single Battery 12X8 16 Ltr Battery Ope...,ATE3A59AE91CK26A71A05,ext_sps,AWP,AWP : Patna WH,AWP_06690e9940963d92d58bcb3a6563d29c,Forward,SHIPMENT,COD,Z,True,2026-07-11,ShipmentDelivered,803201.0,Patna,BIHAR,851213,East,KHAGARIA,BIHAR,2026-07-08,27,1.0,2026-07-08,2026-07-08,2026-07-08,2026-07-11T07:45:01.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T22:05:14.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4874.00,3874.0,24450.0,ZONAL,False,NaN,2026-07-14T03:15:00+0530,pickuphub_pat,SATELLITEHUB_KGG,2026-07-14,2026-07-08,SPS,64.0,49.0,24450.0,39.0,SATELLITEHUB_KGG,SATELLITEHUB_KGG,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-08,delivered,2026-07-11,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,9,<=45,Null,1,4874.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,pat,NaN,False,Nan
4,ORD-SO-796826,NaN,AWPC0000078604,FSD_LARGE,AWP,BALWAAN DOUBLE BATTERY-DOUBLE MOTOR BS-22D 12X...,ATE3A59AB38GD97A63A05,ext_sps,AWP,AWP : Rohit Bajaj,AWP_85296f55bcc56dc187a14f2f9c6e8299,Forward,SHIPMENT,COD,Z,True,2026-07-08,ShipmentDelivered,711302.0,Howrah,WEST BENGAL,848201,East,BEGUSARAI,BIHAR,2026-07-01,26,4.0,2026-07-01,2026-07-04,2026-07-04,2026-07-08T06:33:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T22:24:37.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,7370.00,6870.0,29172.0,ZONAL,False,NaN,2026-07-11T03:15:00+0530,pickuphub_fkhwh,Satellitehub_FKBEGU,2026-07-11,2026-07-04,SPS,64.0,53.0,29172.0,43.0,Satellitehub_FKBEGU,Satellitehub_FKBEGU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-04,delivered,2026-07-08,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,16,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkhwh,NaN,False,Nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921759,XPYE2ETDDR8JIQTK,NaN,UNCP0000314145,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,302021,North,JAIPUR,RAJASTHAN,2026-04-10,15,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-18T02:09:37.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T15:45:26.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-19T03:15:00+0530,pickuphub_fkbgr2,SatelliteHub_JAI,2026-04-19,2026-04-13,SPS,30.0,8.0,3480.0,21.0,SatelliteHub_JAI,SatelliteHub_JAI,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan
921760,CP66PCOX4L,NaN,UNCP0000314813,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-01,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,274301,North,DEORIA,UTTAR PRADESH,2026-04-14,15,3.0,2026-04-14,2026-04-17,2026-04-17,2026-04-30T23:56:26.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T21:43:49.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-28T03:15:00+0530,pickuphub_fkbgr2,SATELLITEHUB_KUSHINAGAR,2026-04-28,2026-04-17,SPS,20.0,19.0,6640.0,26.0,SATELLITEHUB_KUSHINAGAR,SATELLITEHUB_KUSHINAGAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-01,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,94,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan
921761,E5VOT73QQV,NaN,UNCP0000314816,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-07,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,805110,East,NAWADA,BIHAR,2026-04-14,15,3.0,2026-04-14,2026-04-17,2026-04-17,2026-05-07T06:00:49.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T18:25:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-26T03:15:00+0530,pickuphub_fkbgr2,Satellitehub_FKNWD,2026-04-26,2026-04-17,SPS,20.0,19.0,6640.0,26.0,Satellitehub_FKNWD,Satellitehub_FKNWD,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-07,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,94,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan
921762,5XYZFK5V3Y0NOT0N,NaN,UNCP0000314002,FSD_LARGE,UNC,GATE ELECTRICAL,GATE ELECTRICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,382330,West,AHMEDABAD,GUJARAT,2026-04-10,15,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-18T07:53:46.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T23:10:07.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,5710.0,METRO,False,NaN,2026-04-19T03:15:00+0530,pickuphub_fkbgr2,SatelliteHub_NAR,2026-04-19,2026-04-13,SPS,19.0,18.0,5710.0,25.0,SatelliteHub_NAR,SatelliteHub_NAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan
921763,WETER7WN993JO9OG,NaN,UNCP0000314142,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-19,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,752001,East,PURI,ODISHA,2026-04-10,15,4.0,2026-04-10,2026-04-13,2026-04-13,2026-04-19T04:27:51.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T18:09:19.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-20T03:15:00+0530,pickuphub_fkbgr2,Satellitehub_FKPUR,2026-04-20,2026-04-13,SPS,30.0,8.0,3480.0,21.0,Satellitehub_FKPUR,Satellitehub_FKPUR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-19,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan

In [60]:
import pandas as pd
from datetime import date

# Calculate Ph_in_Ageing = today - ph_in_date_final
today = pd.Timestamp(date.today())
drf2['Ph_in_Ageing'] = (today - pd.to_datetime(drf2['ph_in_date_final'])).dt.days

# Insert after ph_in_date_final
col = drf2.pop('Ph_in_Ageing')
ph_in_idx = drf2.columns.get_loc('ph_in_date_final')
drf2.insert(ph_in_idx + 1, 'Ph_in_Ageing', col)

print(drf2[['ph_in_date_final', 'Ph_in_Ageing']].head(10))

  ph_in_date_final  Ph_in_Ageing
0       2026-06-10          37.0
1       2026-06-30          17.0
2       2026-06-04          43.0
3       2026-07-08           9.0
4       2026-07-04          13.0
5       2026-06-27          20.0
6       2026-06-26          21.0
7       2026-06-25          22.0
8       2026-06-23          24.0
9       2026-06-22          25.0

In [61]:
drf2

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_zone,dest_city,dest_state,created_at,week_no,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,Ph_in_Ageing,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,first_ph_in_post_rto_hub_name,first_ph_in_post_rto_datetime,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor,ERP_Status,Final_Status,Unnamed: 0,Timestamp,AWB_TID_number,Issue_Category,Status,Reason,PH_or_DH,Seller_type,Payment_Mode,Customer Code,shipment_value_1,todays_date,ageing_1,Ageing_bucket,loss,child_count,logistics_breach_bucket,last_scan_ageing,last_scan_ageing_bucket,Shipment/Bag ID,Date,Facility,check2,Hub name,Pickuphub_new,Current_loc_new,check,Asset
0,TFC001512055,NaN,AMAP0000000577,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-JUMBO-8] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-06-15,ShipmentDelivered,110086.0,Delhi,DELHI,560068,South,BANGALORE,KARNATAKA,2026-06-10,23,1.0,2026-06-10,2026-06-10,37.0,2026-06-10,2026-06-15T05:01:43.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T08:24:00.000+05:30,2026-06-15T14:44:54.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5510.25,0.0,19000.0,METRO,False,NaN,2026-06-15T03:15:00+0530,pickuphub_rpbaghfm,BulkHub_BLR,2026-06-15,2026-06-10,SPS,120.0,25.0,19000.0,25.0,BulkHub_BLR,BulkHub_BLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-10,delivered,2026-06-15,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,37,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,rpbaghfm,NaN,False,Nan
1,TFC001512213,NaN,AMAP0000000819,FSD_LARGE,AMA,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,[UY-BB-SNOOZE-LARGE-2] \rYogi - Bean Bag Bed -...,ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-07-05,ShipmentDelivered,110086.0,Delhi,DELHI,580023,South,DHARWAD,KARNATAKA,2026-06-30,26,1.0,2026-06-30,2026-06-30,17.0,2026-06-30,2026-07-05T05:25:29.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T08:19:45.000+05:30,2026-07-05T18:00:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5628.75,0.0,13000.0,ROI,False,NaN,2026-07-05T03:15:00+0530,pickuphub_rpbaghfm,SATELLITEHUB_FKHBLA,2026-07-05,2026-06-30,SPS,110.0,20.0,13000.0,20.0,SATELLITEHUB_FKHBLA,SATELLITEHUB_FKHBLA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-30,delivered,2026-07-05,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,17,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,rpbaghfm,NaN,False,Nan
2,940069,NaN,ARLP0000003366,FSD_LARGE,ARL,SINGER COOKMATE 5L,SINGER COOKMATE 5L,ext_sps,ARL,ARL : ARL_THA_01,ARL_448c561fc19f951b85377ebb5382e9af,Forward,SHIPMENT,PP,N,True,2026-06-12,ShipmentDelivered,401105.0,Thane,MAHARASHTRA,800007,East,PATNA,BIHAR,2026-06-03,22,1.0,2026-06-03,2026-06-04,43.0,2026-06-04,2026-06-12T05:01:52.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T09:09:51.000+05:30,2026-06-12T18:26:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2784.00,0.0,2600.0,ROI,False,NaN,2026-06-13T03:15:00+0530,pickuphub_fkmib,SatelliteHub_PAT,2026-06-13,2026-06-04,SPS,45.0,20.0,2600.0,25.0,SatelliteHub_PAT,SatelliteHub_PAT,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,6,2026-06-04,delivered,2026-06-12,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,44,<=45,Null,1,2000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkmib,NaN,False,Nan
3,ORD-SO-813176,NaN,AWPC0000077622,FSD_LARGE,AWP,Hymatic Single Battery 12X8 16 Ltr Battery Ope...,ATE3A59AE91CK26A71A05,ext_sps,AWP,AWP : Patna WH,AWP_06690e9940963d92d58bcb3a6563d29c,Forward,SHIPMENT,COD,Z,True,2026-07-11,ShipmentDelivered,803201.0,Patna,BIHAR,851213,East,KHAGARIA,BIHAR,2026-07-08,27,1.0,2026-07-08,2026-07-08,9.0,2026-07-08,2026-07-11T07:45:01.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T09:14:23.000+05:30,2026-07-11T22:05:14.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4874.00,3874.0,24450.0,ZONAL,False,NaN,2026-07-14T03:15:00+0530,pickuphub_pat,SATELLITEHUB_KGG,2026-07-14,2026-07-08,SPS,64.0,49.0,24450.0,39.0,SATELLITEHUB_KGG,SATELLITEHUB_KGG,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-08,delivered,2026-07-11,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,9,<=45,Null,1,4874.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,pat,NaN,False,Nan
4,ORD-SO-796826,NaN,AWPC0000078604,FSD_LARGE,AWP,BALWAAN DOUBLE BATTERY-DOUBLE MOTOR BS-22D 12X...,ATE3A59AB38GD97A63A05,ext_sps,AWP,AWP : Rohit Bajaj,AWP_85296f55bcc56dc187a14f2f9c6e8299,Forward,SHIPMENT,COD,Z,True,2026-07-08,ShipmentDelivered,711302.0,Howrah,WEST BENGAL,848201,East,BEGUSARAI,BIHAR,2026-07-01,26,4.0,2026-07-01,2026-07-04,13.0,2026-07-04,2026-07-08T06:33:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T12:55:32.000+05:30,2026-07-08T22:24:37.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,7370.00,6870.0,29172.0,ZONAL,False,NaN,2026-07-11T03:15:00+0530,pickuphub_fkhwh,Satellitehub_FKBEGU,2026-07-11,2026-07-04,SPS,64.0,53.0,29172.0,43.0,Satellitehub_FKBEGU,Satellitehub_FKBEGU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,7,2026-07-04,delivered,2026-07-08,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,16,<=45,Null,1,5000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkhwh,NaN,False,Nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921759,XPYE2ETDDR8JIQTK,NaN,UNCP0000314145,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,302021,North,JAIPUR,RAJASTHAN,2026-04-10,15,4.0,2026-04-10,2026-04-13,95.0,2026-04-13,2026-04-18T02:09:37.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T07:57:35.000+05:30,2026-04-18T15:45:26.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-19T03:15:00+0530,pickuphub_fkbgr2,SatelliteHub_JAI,2026-04-19,2026-04-13,SPS,30.0,8.0,3480.0,21.0,SatelliteHub_JAI,SatelliteHub_JAI,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan
921760,CP66PCOX4L,NaN,UNCP0000314813,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-01,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,274301,North,DEORIA,UTTAR PRADESH,2026-04-14,15,3.0,2026-04-14,2026-04-17,91.0,2026-04-17,2026-04-30T23:56:26.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T08:03:44.000+05:30,2026-05-01T21:43:49.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-28T03:15:00+0530,pickuphub_fkbgr2,SATELLITEHUB_KUSHINAGAR,2026-04-28,2026-04-17,SPS,20.0,19.0,6640.0,26.0,SATELLITEHUB_KUSHINAGAR,SATELLITEHUB_KUSHINAGAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-01,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,94,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan
921761,E5VOT73QQV,NaN,UNCP0000314816,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-05-07,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,805110,East,NAWADA,BIHAR,2026-04-14,15,3.0,2026-04-14,2026-04-17,91.0,2026-04-17,2026-05-07T06:00:49.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T06:59:44.000+05:30,2026-05-07T18:25:57.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ShipmentNotReady,3000.00,0.0,6640.0,ROI,False,NaN,2026-04-26T03:15:00+0530,pickuphub_fkbgr2,Satellitehub_FKNWD,2026-04-26,2026-04-17,SPS,20.0,19.0,6640.0,26.0,Satellitehub_FKNWD,Satellitehub_FKNWD,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-17,delivered,2026-05-07,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,94,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan
921762,5XYZFK5V3Y0NOT0N,NaN,UNCP0000314002,FSD_LARGE,UNC,GATE ELECTRICAL,GATE ELECTRICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-18,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,382330,West,AHMEDABAD,GUJARAT,2026-04-10,15,4.0,2026-04-10,2026-04-13,95.0,2026-04-13,2026-04-18T07:53:46.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T09:23:27.000+05:30,2026-04-18T23:10:07.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,5710.0,METRO,False,NaN,2026-04-19T03:15:00+0530,pickuphub_fkbgr2,SatelliteHub_NAR,2026-04-19,2026-04-13,SPS,19.0,18.0,5710.0,25.0,SatelliteHub_NAR,SatelliteHub_NAR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-18,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan
921763,WETER7WN993JO9OG,NaN,UNCP0000314142,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-19,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,752001,East,PURI,ODISHA,2026-04-10,15,4.0,2026-04-10,2026-04-13,95.0,2026-04-13,2026-04-19T04:27:51.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T08:11:33.000+05:30,2026-04-19T18:09:19.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.00,0.0,3480.0,ROI,False,NaN,2026-04-20T03:15:00+0530,pickuphub_fkbgr2,Satellitehub_FKPUR,2026-04-20,2026-04-13,SPS,30.0,8.0,3480.0,21.0,Satellitehub_FKPUR,Satellitehub_FKPUR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,4,2026-04-13,delivered,2026-04-19,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-07-17,98,>45,Null,1,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN,fkbgr,NaN,False,Nan

In [62]:
#os.chdir(r"C:\Users\mohammadali1.vc\Desktop\Python data\Large Check File")
s8.to_csv("large_sum_17_Jul Rev.csv")
drf2.to_csv("large_check_17_Jul Rev.csv",index=False)