In [2]:
import pandas as pd
import numpy as np
import os
pd.set_option('display.max_columns',None)

In [3]:
os.chdir(r"C:\Users\mohammadali1.vc\Desktop\Python data\Large Check File")
dift=pd.read_csv("FDP_06 May.csv")
dift.dropna(subset=["ph_in_time", "dh_receive_time","ph_in_date_final"], how="all", inplace=True)
dift

C:\Users\mohammadali1.vc\AppData\Local\Temp\ipykernel_10132\442543483.py:2: DtypeWarning: Columns (0: order_id, 1: global_tracking_id, 2: product_id, 3: is_forward, 4: upstream_rto_flag, 5: global_merchant_reference_id, 6: first_rvp_pickup_time, 7: last_rvp_pickup_time, 8: actual_rvp_pickup_time, 9: checks, 10: ismandatory_list, 11: fe_result_list, 12: checks_failed) have mixed types. Specify dtype option on import or set low_memory=False.
  dift=pd.read_csv("FDP_06 May.csv")

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated
0,TFC001511752,NaN,AMAP0000000097,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-05-06T00:00:08.000+05:30,ShipmentUndeliveredAttempted,110086.0,Delhi,DELHI,682030.0,ERNAKULAM,KERALA,2026-04-28T08:19:25.000+05:30,1.0,2026-04-28T08:19:20.000+05:30,2026-04-28,2026-04-28T13:59:25.000+05:30,2026-05-04T06:24:00.000+05:30,2026-05-05T11:23:57.000+05:30,2026-05-05T11:23:57.000+05:30,NaN,Attempted,NaN,1.0,RequestForReschedule,RequestForReschedule,NaN,RequestForReschedule,NaN,NaN,NaN,6738.3,0.0,19000.0,ROI,False,NaN,2026-05-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_KOC,2026-05-05,2026-04-28,SPS,130.0,30.0,19000.0,30.0,SATELLITEHUB_KOC,SATELLITEHUB_KOC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False
1,885596,NaN,ARLP0000001325,FSD_LARGE,ARL,SINGER COOKMATE 5L,885596,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-13T20:06:13.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,282001.0,AGRA,UTTAR PRADESH,2026-02-07T22:35:35.000+05:30,2.0,2026-02-07T22:34:58.000+05:30,2026-02-09,NaN,2026-02-13T02:01:56.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T20:06:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-15T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_AGR1,2026-02-15,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_AGR1,SATELLITEHUB_AGR1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True
2,885835,NaN,ARLP0000001328,FSD_LARGE,ARL,SINGER COOKMATE 5L,885835,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-19T17:43:18.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,147105.0,PATIALA,PUNJAB,2026-02-07T22:35:26.000+05:30,5.0,2026-02-07T22:34:58.000+05:30,2026-02-12,NaN,2026-02-18T10:09:16.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T17:43:18.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_Sangrur,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_Sangrur,SATELLITEHUB_Sangrur,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True
3,907611,NaN,ARLP0000001553,FSD_LARGE,ARL,SINGER COOKMATE 5L,907611,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-24T18:56:35.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,323601.0,KESHORAIPATAN,RAJASTHAN,2026-02-07T22:35:04.000+05:30,5.0,2026-02-07T22:34:52.000+05:30,2026-02-12,NaN,2026-02-19T06:09:01.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T18:56:35.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T00:00:00+0530,Pickuphub_FKMIB,SATELLITEHUB_KOTA,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_KOTA,SATELLITEHUB_KOTA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True
4,882107,NaN,ARLP0000001631,FSD_LARGE,ARL,SINGER LEO 3L WH,882107,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-16T20:33:40.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,333042.0,JHUJHUNU,RAJASTHAN,2026-02-07T22:35:06.000+05:30,2.0,2026-02-07T22:34:55.000+05:30,2026-02-09,NaN,2026-02-12T20:00:37.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T20:33:40.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,4640.0,0.0,3400.0,ROI,False,NaN,2026-02-18T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_JHUNJHUNU,2026-02-18,NaN,SPS,41.0,23.0,3400.0,26.0,SATELLITEHUB_JHUNJHUNU,SATELLITEHUB_JHUNJHUNU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751661,ODN2MDAHNQI0KW5O,NaN,UNCP0000313886,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-25T21:37:23.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,457001.0,RATLAM,MADHYA PRADESH,2026-04-10T14:36:40.000+05:30,4.0,2026-04-10T14:36:19.000+05:30,2026-04-13,2026-04-13T17:10:53.000+05:30,2026-04-20T16:17:48.000+05:30,2026-04-25T09:25:55.000+05:30,2026-04-25T09:25:55.000+05:30,2026-04-25T21:37:23.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,6640.0,ROI,False,NaN,2026-04-22T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_MSR,2026-04-22,2026-04-13,SPS,20.0,19.0,6640.0,26.0,Satellitehub_MSR,Satellitehub_MSR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True
751662,8ST9XZVNQLM5BEZV,NaN,UNCP0000313904,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-19T22:27:03.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,181205.0,JAMMU,JAMMU AND KASHMIR,2026-04-10T14:36:25.000+05:30,4.0,2026-04-10T14:36:16.000+05:30,2026-04-13,2026-04-13T17:10:59.000+05:30,2026-04-19T07:21:49.000+05:30,2026-04-19T08:53:20.000+05:30,2026-04-19T08:53:20.000+05:30,2026-04-19T22:27:03.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,8000.0,JK_NE,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_JMU1,2026-04-19,2026-04-13,SPS,39.0,13.0,8000.0,26.0,SATELLITEHUB_JMU1,SATELLITEHUB_JMU1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True
751663,KY82EZROFZQEDLLZ,NaN,UNCP0000314451,FSD_LARGE,UNC,GATE CIVIL,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,RTO,RTO,PP,N,True,2026-04-17T18:17:40.000+05:30,ShipmentRtoCompleted,560062.0,Bengaluru,KARNATAKA,800002.0,PATNA,BIHAR,2026-04-14T17:45:38.000+05:30,1.0,2026-04-14T17:45:23.000+05:30,2026-04-15,2026-04-15T16:00:20.000+05:30,NaN,NaN,NaN,NaN,Not_Attempted,2026-04-15T18:25:04.000+05:30,0.0,NaN,NaN,CentralHub_FKBGR2,NaN,Shipment Delayed,NaN,NaN,3000.0,0.0,6640.0,ROI,True,NaN,2026-04-24T03:15:00+0530,Pickuphub_FKBGR2,NaN,2026-04-24,2026-04-15,SPS,20.0,19.0,6640.0,26.0,NaN,Pickuphub_MpHub_FKBGR2,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
751664,54NPGRHABH,NaN,UNCP0000315271,FSD_LARGE,UNC,IIT JEE 4.0 NOTES,IIT JEE 4.0 NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,Z,True,2026-04-21T20:48:05.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,413304.0,PANDHARPUR,MAHARASHTRA,2026-04-15T18:50:50.000+05:30,1.0,2026-04-15T18:50:41.000+05:30,2026-04-16,2026-04-16T16:27:40.000+05:30,2026-04-20T06:33:27.000+05:30,2026-04-21T08:47:27.000+05:30,2026-04-21T08:47:27.000+05:30,2026-04-21T20:48:05.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,0.0,8970.0,ROI,False,NaN,2026-04-21T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_FKSOL,2026-04-21,2026-04-16,SPS,22.0,22.0,8970.0,29.0,SatelliteHub_FKSOL,SatelliteHub_FKSOL,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True
751665,1FDMWEV7NF,NaN,UNCP0000315586,FSD_LARGE,UNC,IIT JEE 4.0 NOTES,IIT JEE 4.0 NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,Z,True,2026-04-27T23:04:13.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,431517.0,BEED,MAHARASHTRA,2026-04-20T14:12:10.000+05:30,1.0,2026-04-20T14:12:04.000+05:30,2026-04-21,2026-04-21T17:50:14.000+05:30,2026-04-24T15:51:59.000+05:30,2026-04-27T09:10:19.000+05:30,2026-04-27T09:10:19.000+05:30,2026-04-27T23:04:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,0.0,8970.0,ZONAL,False,NaN,2026-05-01T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_FKLTR,2026-05-01,2026-04-21,SPS,22.0,22.0,8970.0,29.0,SatelliteHub_FKLTR,SatelliteHub_FKLTR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True

In [4]:
#dift["dispatch_month"] = pd.to_datetime(dift["dispatch_date"], format="%Y-%m-%d %H:%M:%S").dt.month
dift["dispatch_month"] = pd.to_datetime(dift["dispatch_date"], format='mixed').dt.month
dift.dispatch_month.value_counts()

dispatch_month
4    258821
3    234833
2    171025
5     30067
Name: count, dtype: int64

In [5]:
dift2=dift[~dift['dispatch_month'].isin([10,11,12])]
dift2

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,dispatch_month
0,TFC001511752,NaN,AMAP0000000097,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-05-06T00:00:08.000+05:30,ShipmentUndeliveredAttempted,110086.0,Delhi,DELHI,682030.0,ERNAKULAM,KERALA,2026-04-28T08:19:25.000+05:30,1.0,2026-04-28T08:19:20.000+05:30,2026-04-28,2026-04-28T13:59:25.000+05:30,2026-05-04T06:24:00.000+05:30,2026-05-05T11:23:57.000+05:30,2026-05-05T11:23:57.000+05:30,NaN,Attempted,NaN,1.0,RequestForReschedule,RequestForReschedule,NaN,RequestForReschedule,NaN,NaN,NaN,6738.3,0.0,19000.0,ROI,False,NaN,2026-05-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_KOC,2026-05-05,2026-04-28,SPS,130.0,30.0,19000.0,30.0,SATELLITEHUB_KOC,SATELLITEHUB_KOC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,4
1,885596,NaN,ARLP0000001325,FSD_LARGE,ARL,SINGER COOKMATE 5L,885596,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-13T20:06:13.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,282001.0,AGRA,UTTAR PRADESH,2026-02-07T22:35:35.000+05:30,2.0,2026-02-07T22:34:58.000+05:30,2026-02-09,NaN,2026-02-13T02:01:56.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T20:06:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-15T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_AGR1,2026-02-15,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_AGR1,SATELLITEHUB_AGR1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2
2,885835,NaN,ARLP0000001328,FSD_LARGE,ARL,SINGER COOKMATE 5L,885835,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-19T17:43:18.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,147105.0,PATIALA,PUNJAB,2026-02-07T22:35:26.000+05:30,5.0,2026-02-07T22:34:58.000+05:30,2026-02-12,NaN,2026-02-18T10:09:16.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T17:43:18.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_Sangrur,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_Sangrur,SATELLITEHUB_Sangrur,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2
3,907611,NaN,ARLP0000001553,FSD_LARGE,ARL,SINGER COOKMATE 5L,907611,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-24T18:56:35.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,323601.0,KESHORAIPATAN,RAJASTHAN,2026-02-07T22:35:04.000+05:30,5.0,2026-02-07T22:34:52.000+05:30,2026-02-12,NaN,2026-02-19T06:09:01.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T18:56:35.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T00:00:00+0530,Pickuphub_FKMIB,SATELLITEHUB_KOTA,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_KOTA,SATELLITEHUB_KOTA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2
4,882107,NaN,ARLP0000001631,FSD_LARGE,ARL,SINGER LEO 3L WH,882107,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-16T20:33:40.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,333042.0,JHUJHUNU,RAJASTHAN,2026-02-07T22:35:06.000+05:30,2.0,2026-02-07T22:34:55.000+05:30,2026-02-09,NaN,2026-02-12T20:00:37.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T20:33:40.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,4640.0,0.0,3400.0,ROI,False,NaN,2026-02-18T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_JHUNJHUNU,2026-02-18,NaN,SPS,41.0,23.0,3400.0,26.0,SATELLITEHUB_JHUNJHUNU,SATELLITEHUB_JHUNJHUNU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751661,ODN2MDAHNQI0KW5O,NaN,UNCP0000313886,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-25T21:37:23.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,457001.0,RATLAM,MADHYA PRADESH,2026-04-10T14:36:40.000+05:30,4.0,2026-04-10T14:36:19.000+05:30,2026-04-13,2026-04-13T17:10:53.000+05:30,2026-04-20T16:17:48.000+05:30,2026-04-25T09:25:55.000+05:30,2026-04-25T09:25:55.000+05:30,2026-04-25T21:37:23.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,6640.0,ROI,False,NaN,2026-04-22T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_MSR,2026-04-22,2026-04-13,SPS,20.0,19.0,6640.0,26.0,Satellitehub_MSR,Satellitehub_MSR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,4
751662,8ST9XZVNQLM5BEZV,NaN,UNCP0000313904,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-04-19T22:27:03.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,181205.0,JAMMU,JAMMU AND KASHMIR,2026-04-10T14:36:25.000+05:30,4.0,2026-04-10T14:36:16.000+05:30,2026-04-13,2026-04-13T17:10:59.000+05:30,2026-04-19T07:21:49.000+05:30,2026-04-19T08:53:20.000+05:30,2026-04-19T08:53:20.000+05:30,2026-04-19T22:27:03.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,8000.0,JK_NE,False,NaN,2026-04-19T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_JMU1,2026-04-19,2026-04-13,SPS,39.0,13.0,8000.0,26.0,SATELLITEHUB_JMU1,SATELLITEHUB_JMU1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,4
751663,KY82EZROFZQEDLLZ,NaN,UNCP0000314451,FSD_LARGE,UNC,GATE CIVIL,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,RTO,RTO,PP,N,True,2026-04-17T18:17:40.000+05:30,ShipmentRtoCompleted,560062.0,Bengaluru,KARNATAKA,800002.0,PATNA,BIHAR,2026-04-14T17:45:38.000+05:30,1.0,2026-04-14T17:45:23.000+05:30,2026-04-15,2026-04-15T16:00:20.000+05:30,NaN,NaN,NaN,NaN,Not_Attempted,2026-04-15T18:25:04.000+05:30,0.0,NaN,NaN,CentralHub_FKBGR2,NaN,Shipment Delayed,NaN,NaN,3000.0,0.0,6640.0,ROI,True,NaN,2026-04-24T03:15:00+0530,Pickuphub_FKBGR2,NaN,2026-04-24,2026-04-15,SPS,20.0,19.0,6640.0,26.0,NaN,Pickuphub_MpHub_FKBGR2,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
751664,54NPGRHABH,NaN,UNCP0000315271,FSD_LARGE,UNC,IIT JEE 4.0 NOTES,IIT JEE 4.0 NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,Z,True,2026-04-21T20:48:05.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,413304.0,PANDHARPUR,MAHARASHTRA,2026-04-15T18:50:50.000+05:30,1.0,2026-04-15T18:50:41.000+05:30,2026-04-16,2026-04-16T16:27:40.000+05:30,2026-04-20T06:33:27.000+05:30,2026-04-21T08:47:27.000+05:30,2026-04-21T08:47:27.000+05:30,2026-04-21T20:48:05.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,0.0,8970.0,ROI,False,NaN,2026-04-21T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_FKSOL,2026-04-21,2026-04-16,SPS,22.0,22.0,8970.0,29.0,SatelliteHub_FKSOL,SatelliteHub_FKSOL,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,4
751665,1FDMWEV7NF,NaN,UNCP0000315586,FSD_LARGE,UNC,IIT JEE 4.0 NOTES,IIT JEE 4.0 NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,Z,True,2026-04-27T23:04:13.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,431517.0,BEED,MAHARASHTRA,2026-04-20T14:12:10.000+05:30,1.0,2026-04-20T14:12:04.000+05:30,2026-04-21,2026-04-21T17:50:14.000+05:30,2026-04-24T15:51:59.000+05:30,2026-04-27T09:10:19.000+05:30,2026-04-27T09:10:19.000+05:30,2026-04-27T23:04:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,0.0,8970.0,ZONAL,False,NaN,2026-05-01T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_FKLTR,2026-05-01,2026-04-21,SPS,22.0,22.0,8970.0,29.0,SatelliteHub_FKLTR,SatelliteHub_FKLTR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,4

In [6]:
#os.chdir(r"C:\Users\mohammadali1.vc\Desktop\Python data\Large Check File")
dift1=pd.read_csv("FDP_02 Mar.csv")
dift1.dropna(subset=["ph_in_time", "dh_receive_time"], how="all", inplace=True)
dift1

C:\Users\mohammadali1.vc\AppData\Local\Temp\ipykernel_10132\3537536849.py:2: DtypeWarning: Columns (0: order_id, 1: global_tracking_id, 2: product_id, 3: is_forward, 4: upstream_rto_flag, 5: global_merchant_reference_id, 6: first_rvp_pickup_time, 7: last_rvp_pickup_time, 8: actual_rvp_pickup_time, 9: rvp_reason, 10: checks, 11: ismandatory_list, 12: fe_result_list, 13: checks_failed) have mixed types. Specify dtype option on import or set low_memory=False.
  dift1=pd.read_csv("FDP_02 Mar.csv")

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated
0,884852,NaN,ARLP0000001947,FSD_LARGE,ARL,SINGER PD JMG 3J,884852,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-17T21:54:28.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,854205.0,PURNIA,BIHAR,2026-02-07T22:35:20.000+05:30,2.0,2026-02-07T22:34:57.000+05:30,2026-02-09,2026-02-09T16:27:15.000+05:30,2026-02-16T06:25:47.000+05:30,2026-02-17T09:10:53.000+05:30,2026-02-17T09:10:53.000+05:30,2026-02-17T21:54:28.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3940.0,0.0,4460.0,ROI,False,NaN,2026-02-17T03:15:00+0530,Pickuphub_FKMIB,Satellitehub_PRN1,2026-02-17,2026-02-09,SPS,47.0,21.0,4460.0,25.0,Satellitehub_PRN1,Satellitehub_PRN1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True
1,885069,NaN,ARLP0000001955,FSD_LARGE,ARL,SINGER PD JMG 3J,885069,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-18T21:18:13.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,121102.0,PALWAL,HARYANA,2026-02-07T22:35:24.000+05:30,6.0,2026-02-07T22:34:57.000+05:30,2026-02-13,2026-02-13T19:29:30.000+05:30,2026-02-18T05:21:55.000+05:30,2026-02-18T08:21:41.000+05:30,2026-02-18T08:21:41.000+05:30,2026-02-18T21:18:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,3940.0,0.0,4460.0,ROI,False,NaN,2026-02-18T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_PALWAL,2026-02-18,2026-02-13,SPS,47.0,21.0,4460.0,25.0,SATELLITEHUB_PALWAL,SATELLITEHUB_PALWAL,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True
2,885122,NaN,ARLP0000001957,FSD_LARGE,ARL,SINGER PD JMG 3J,885122,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-15T22:30:21.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,206246.0,ETAWAH,UTTAR PRADESH,2026-02-07T22:35:24.000+05:30,2.0,2026-02-07T22:34:57.000+05:30,2026-02-09,2026-02-09T16:40:23.000+05:30,2026-02-13T03:22:24.000+05:30,2026-02-13T07:02:09.000+05:30,2026-02-15T06:44:56.000+05:30,2026-02-15T22:30:21.000+05:30,Attempted,NaN,2.0,Customer Not Responding,Customer Not Responding,NaN,Customer Not Responding,NaN,NaN,ManpowerIssue,3940.0,0.0,4460.0,ROI,False,NaN,2026-02-16T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_AURAIYA,2026-02-16,2026-02-09,SPS,47.0,21.0,4460.0,25.0,SATELLITEHUB_AURAIYA,SATELLITEHUB_AURAIYA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True
3,889138,NaN,ARLP0000002047,FSD_LARGE,ARL,SINGER PD JMG 3J,889138,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-15T18:19:56.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,143001.0,AMRITSAR,PUNJAB,2026-02-07T22:35:44.000+05:30,2.0,2026-02-07T22:34:59.000+05:30,2026-02-09,NaN,2026-02-15T07:27:25.000+05:30,2026-02-15T09:58:13.000+05:30,2026-02-15T09:58:13.000+05:30,2026-02-15T18:19:56.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3940.0,0.0,4460.0,ROI,False,NaN,2026-02-16T03:15:00+0530,Pickuphub_FKMIB,SatelliteHub_ASR,2026-02-16,NaN,SPS,47.0,21.0,4460.0,25.0,SatelliteHub_ASR,SatelliteHub_ASR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True
4,894074,NaN,ARLP0000002180,FSD_LARGE,ARL,SINGER PD JMG 3J,894074,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-13T19:32:40.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,509204.0,MAHABUB NAGAR,TELANGANA,2026-02-07T22:35:21.000+05:30,2.0,2026-02-07T22:34:57.000+05:30,2026-02-09,NaN,2026-02-12T07:48:57.000+05:30,2026-02-13T08:59:52.000+05:30,2026-02-13T08:59:52.000+05:30,2026-02-13T19:32:40.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3940.0,0.0,4460.0,ROI,False,NaN,2026-02-17T03:15:00+0530,Pickuphub_FKMIB,Satellitehub_MBGFK,2026-02-17,NaN,SPS,47.0,21.0,4460.0,25.0,Satellitehub_MBGFK,Satellitehub_MBGFK,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480187,G9S1EO8V6RJUC3JD,NaN,UNCP0000309219,FSD_LARGE,UNC,BANK NOTES,BANK NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-06T17:31:36.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,482002.0,JABALPUR,MADHYA PRADESH,2026-01-30T15:46:09.000+05:30,4.0,2026-01-30T15:46:04.000+05:30,2026-02-02,2026-02-02T20:25:42.000+05:30,2026-02-06T06:44:08.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T17:31:36.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,4130.0,ROI,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JLR,2026-02-07,2026-02-02,SPS,19.0,13.0,4130.0,25.0,SatelliteHub_JLR,SatelliteHub_JLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True
480188,64B1EZX31KGO5GB1,NaN,UNCP0000309258,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-07T21:40:56.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,410506.0,PUNE,MAHARASHTRA,2026-01-30T15:46:01.000+05:30,3.0,2026-01-30T15:45:56.000+05:30,2026-02-03,2026-02-03T04:12:16.000+05:30,2026-02-07T06:55:08.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T21:40:56.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,8000.0,METRO,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_PCMC,2026-02-07,2026-02-03,SPS,39.0,13.0,8000.0,26.0,Satellitehub_PCMC,Satellitehub_PCMC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True
480189,1UFR4ZNPP3Y9KD02,NaN,UNCP0000309428,FSD_LARGE,UNC,CAFOACCRK,CAFOACCRK,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-10T21:23:16.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,400089.0,MUMBAI,MAHARASHTRA,2026-02-05T16:46:30.000+05:30,1.0,2026-02-05T16:46:24.000+05:30,2026-02-06,2026-02-06T20:41:47.000+05:30,2026-02-10T08:52:18.000+05:30,2026-02-10T10:41:31.000+05:30,2026-02-10T10:41:31.000+05:30,2026-02-10T21:23:16.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,0.0,3920.0,METRO,False,NaN,2026-02-10T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_CHV,2026-02-10,2026-02-06,SPS,19.0,12.0,3920.0,25.0,SatelliteHub_CHV,SatelliteHub_CHV,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True
480190,V3CS2ZWC6N,NaN,UNCP0000310061,FSD_LARGE,UNC,IIT_PCM_12_4.0,IIT_PCM_12_4.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-28T21:42:24.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,211011.0,ALLAHABAD,UTTAR PRADESH,2026-02-18T16:32:06.000+05:30,3.0,2026-02-18T16:32:02.000+05:30,2026-02-20,2026-02-20T19:38:43.000+05:30,2026-02-28T03:57:48.000+05:30,2026-02-28T07:25:13.000+05:30,2026-02-28T07:25:13.000+05:30,2026-02-28T21:42:24.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,5080.0,ROI,False,NaN,2026-02-28T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_ALD,2026-02-28,2026-02-20,SPS,24.0,12.0,5080.0,29.0,SatelliteHub_ALD,SatelliteHub_ALD,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True
480191,K94PJD9GLXKCNWT0,NaN,UNCP0000310148,FSD_LARGE,UNC,IIT JEE 4.0 NOTES,IIT JEE 4.0 NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-27T20:30:51.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,302033.0,JAIPUR,RAJASTHAN,2026-02-20T14:56:15.000+05:30,2.0,2026-02-20T14:56:10.000+05:30,2026-02-21,2026-02-21T19:18:31.000+05:30,2026-02-27T07:06:41.000+05:30,2026-02-27T08:11:57.000+05:30,2026-02-27T08:11:57.000+05:30,2026-02-27T20:30:51.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,3000.0,0.0,8970.0,ROI,False,NaN,2026-02-28T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_JAISITAPURA,2026-02-28,2026-02-21,SPS,22.0,22.0,8970.0,29.0,SATELLITEHUB_JAISITAPURA,SATELLITEHUB_JAISITAPURA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True

In [7]:
#os.chdir(r"/Users/prem.b/Documents/large/dump")
#dift4=pd.read_csv("oct_large.csv")
#dift4

In [8]:
#dift1["dispatch_month"] = pd.to_datetime(dift["dispatch_date"], format="%Y-%m-%d %H:%M:%S").dt.month
dift1["dispatch_month"] = pd.to_datetime(dift["dispatch_date"], format='mixed').dt.month
dift1.dispatch_month.value_counts()

dispatch_month
3.0    123847
4.0    122588
2.0     91850
5.0     17379
Name: count, dtype: int64

In [9]:
dift3=dift1[~dift1['dispatch_month'].isin([10,11,12])]
dift3

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,dispatch_month
0,884852,NaN,ARLP0000001947,FSD_LARGE,ARL,SINGER PD JMG 3J,884852,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-17T21:54:28.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,854205.0,PURNIA,BIHAR,2026-02-07T22:35:20.000+05:30,2.0,2026-02-07T22:34:57.000+05:30,2026-02-09,2026-02-09T16:27:15.000+05:30,2026-02-16T06:25:47.000+05:30,2026-02-17T09:10:53.000+05:30,2026-02-17T09:10:53.000+05:30,2026-02-17T21:54:28.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3940.0,0.0,4460.0,ROI,False,NaN,2026-02-17T03:15:00+0530,Pickuphub_FKMIB,Satellitehub_PRN1,2026-02-17,2026-02-09,SPS,47.0,21.0,4460.0,25.0,Satellitehub_PRN1,Satellitehub_PRN1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,4.0
1,885069,NaN,ARLP0000001955,FSD_LARGE,ARL,SINGER PD JMG 3J,885069,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-18T21:18:13.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,121102.0,PALWAL,HARYANA,2026-02-07T22:35:24.000+05:30,6.0,2026-02-07T22:34:57.000+05:30,2026-02-13,2026-02-13T19:29:30.000+05:30,2026-02-18T05:21:55.000+05:30,2026-02-18T08:21:41.000+05:30,2026-02-18T08:21:41.000+05:30,2026-02-18T21:18:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,3940.0,0.0,4460.0,ROI,False,NaN,2026-02-18T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_PALWAL,2026-02-18,2026-02-13,SPS,47.0,21.0,4460.0,25.0,SATELLITEHUB_PALWAL,SATELLITEHUB_PALWAL,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
2,885122,NaN,ARLP0000001957,FSD_LARGE,ARL,SINGER PD JMG 3J,885122,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-15T22:30:21.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,206246.0,ETAWAH,UTTAR PRADESH,2026-02-07T22:35:24.000+05:30,2.0,2026-02-07T22:34:57.000+05:30,2026-02-09,2026-02-09T16:40:23.000+05:30,2026-02-13T03:22:24.000+05:30,2026-02-13T07:02:09.000+05:30,2026-02-15T06:44:56.000+05:30,2026-02-15T22:30:21.000+05:30,Attempted,NaN,2.0,Customer Not Responding,Customer Not Responding,NaN,Customer Not Responding,NaN,NaN,ManpowerIssue,3940.0,0.0,4460.0,ROI,False,NaN,2026-02-16T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_AURAIYA,2026-02-16,2026-02-09,SPS,47.0,21.0,4460.0,25.0,SATELLITEHUB_AURAIYA,SATELLITEHUB_AURAIYA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
3,889138,NaN,ARLP0000002047,FSD_LARGE,ARL,SINGER PD JMG 3J,889138,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-15T18:19:56.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,143001.0,AMRITSAR,PUNJAB,2026-02-07T22:35:44.000+05:30,2.0,2026-02-07T22:34:59.000+05:30,2026-02-09,NaN,2026-02-15T07:27:25.000+05:30,2026-02-15T09:58:13.000+05:30,2026-02-15T09:58:13.000+05:30,2026-02-15T18:19:56.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3940.0,0.0,4460.0,ROI,False,NaN,2026-02-16T03:15:00+0530,Pickuphub_FKMIB,SatelliteHub_ASR,2026-02-16,NaN,SPS,47.0,21.0,4460.0,25.0,SatelliteHub_ASR,SatelliteHub_ASR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
4,894074,NaN,ARLP0000002180,FSD_LARGE,ARL,SINGER PD JMG 3J,894074,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-13T19:32:40.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,509204.0,MAHABUB NAGAR,TELANGANA,2026-02-07T22:35:21.000+05:30,2.0,2026-02-07T22:34:57.000+05:30,2026-02-09,NaN,2026-02-12T07:48:57.000+05:30,2026-02-13T08:59:52.000+05:30,2026-02-13T08:59:52.000+05:30,2026-02-13T19:32:40.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3940.0,0.0,4460.0,ROI,False,NaN,2026-02-17T03:15:00+0530,Pickuphub_FKMIB,Satellitehub_MBGFK,2026-02-17,NaN,SPS,47.0,21.0,4460.0,25.0,Satellitehub_MBGFK,Satellitehub_MBGFK,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480187,G9S1EO8V6RJUC3JD,NaN,UNCP0000309219,FSD_LARGE,UNC,BANK NOTES,BANK NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-06T17:31:36.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,482002.0,JABALPUR,MADHYA PRADESH,2026-01-30T15:46:09.000+05:30,4.0,2026-01-30T15:46:04.000+05:30,2026-02-02,2026-02-02T20:25:42.000+05:30,2026-02-06T06:44:08.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T17:31:36.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,4130.0,ROI,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JLR,2026-02-07,2026-02-02,SPS,19.0,13.0,4130.0,25.0,SatelliteHub_JLR,SatelliteHub_JLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,5.0
480188,64B1EZX31KGO5GB1,NaN,UNCP0000309258,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-07T21:40:56.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,410506.0,PUNE,MAHARASHTRA,2026-01-30T15:46:01.000+05:30,3.0,2026-01-30T15:45:56.000+05:30,2026-02-03,2026-02-03T04:12:16.000+05:30,2026-02-07T06:55:08.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T21:40:56.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,8000.0,METRO,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_PCMC,2026-02-07,2026-02-03,SPS,39.0,13.0,8000.0,26.0,Satellitehub_PCMC,Satellitehub_PCMC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,5.0
480189,1UFR4ZNPP3Y9KD02,NaN,UNCP0000309428,FSD_LARGE,UNC,CAFOACCRK,CAFOACCRK,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-10T21:23:16.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,400089.0,MUMBAI,MAHARASHTRA,2026-02-05T16:46:30.000+05:30,1.0,2026-02-05T16:46:24.000+05:30,2026-02-06,2026-02-06T20:41:47.000+05:30,2026-02-10T08:52:18.000+05:30,2026-02-10T10:41:31.000+05:30,2026-02-10T10:41:31.000+05:30,2026-02-10T21:23:16.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,0.0,3920.0,METRO,False,NaN,2026-02-10T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_CHV,2026-02-10,2026-02-06,SPS,19.0,12.0,3920.0,25.0,SatelliteHub_CHV,SatelliteHub_CHV,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
480190,V3CS2ZWC6N,NaN,UNCP0000310061,FSD_LARGE,UNC,IIT_PCM_12_4.0,IIT_PCM_12_4.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-28T21:42:24.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,211011.0,ALLAHABAD,UTTAR PRADESH,2026-02-18T16:32:06.000+05:30,3.0,2026-02-18T16:32:02.000+05:30,2026-02-20,2026-02-20T19:38:43.000+05:30,2026-02-28T03:57:48.000+05:30,2026-02-28T07:25:13.000+05:30,2026-02-28T07:25:13.000+05:30,2026-02-28T21:42:24.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,5080.0,ROI,False,NaN,2026-02-28T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_ALD,2026-02-28,2026-02-20,SPS,24.0,12.0,5080.0,29.0,SatelliteHub_ALD,SatelliteHub_ALD,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
480191,K94PJD9GLXKCNWT0,NaN,UNCP0000310148,FSD_LARGE,UNC,IIT JEE 4.0 NOTES,IIT JEE 4.0 NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-27T20:30:51.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,302033.0,JAIPUR,RAJASTHAN,2026-02-20T14:56:15.000+05:30,2.0,2026-02-20T14:56:10.000+05:30,2026-02-21,2026-02-21T19:18:31.000+05:30,2026-02-27T07:06:41.000+05:30,2026-02-27T08:11:57.000+05:30,2026-02-27T08:11:57.000+05:30,2026-02-27T20:30:51.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,3000.0,0.0,8970.0,ROI,False,NaN,2026-02-28T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_JAISITAPURA,2026-02-28,2026-02-21,SPS,22.0,22.0,8970.0,29.0,SATELLITEHUB_JAISITAPURA,SATELLITEHUB_JAISITAPURA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0

In [10]:
#os.chdir(r"/Users/prem.b/Documents/large/dump")
#ift1=pd.read_csv("nov_dump.csv")
#ift1

In [11]:
dif=pd.concat([dift2,dift3])
dif

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,dispatch_month
0,TFC001511752,NaN,AMAP0000000097,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-05-06T00:00:08.000+05:30,ShipmentUndeliveredAttempted,110086.0,Delhi,DELHI,682030.0,ERNAKULAM,KERALA,2026-04-28T08:19:25.000+05:30,1.0,2026-04-28T08:19:20.000+05:30,2026-04-28,2026-04-28T13:59:25.000+05:30,2026-05-04T06:24:00.000+05:30,2026-05-05T11:23:57.000+05:30,2026-05-05T11:23:57.000+05:30,NaN,Attempted,NaN,1.0,RequestForReschedule,RequestForReschedule,NaN,RequestForReschedule,NaN,NaN,NaN,6738.3,0.0,19000.0,ROI,False,NaN,2026-05-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_KOC,2026-05-05,2026-04-28,SPS,130.0,30.0,19000.0,30.0,SATELLITEHUB_KOC,SATELLITEHUB_KOC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,4.0
1,885596,NaN,ARLP0000001325,FSD_LARGE,ARL,SINGER COOKMATE 5L,885596,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-13T20:06:13.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,282001.0,AGRA,UTTAR PRADESH,2026-02-07T22:35:35.000+05:30,2.0,2026-02-07T22:34:58.000+05:30,2026-02-09,NaN,2026-02-13T02:01:56.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T20:06:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-15T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_AGR1,2026-02-15,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_AGR1,SATELLITEHUB_AGR1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
2,885835,NaN,ARLP0000001328,FSD_LARGE,ARL,SINGER COOKMATE 5L,885835,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-19T17:43:18.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,147105.0,PATIALA,PUNJAB,2026-02-07T22:35:26.000+05:30,5.0,2026-02-07T22:34:58.000+05:30,2026-02-12,NaN,2026-02-18T10:09:16.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T17:43:18.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_Sangrur,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_Sangrur,SATELLITEHUB_Sangrur,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
3,907611,NaN,ARLP0000001553,FSD_LARGE,ARL,SINGER COOKMATE 5L,907611,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-24T18:56:35.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,323601.0,KESHORAIPATAN,RAJASTHAN,2026-02-07T22:35:04.000+05:30,5.0,2026-02-07T22:34:52.000+05:30,2026-02-12,NaN,2026-02-19T06:09:01.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T18:56:35.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T00:00:00+0530,Pickuphub_FKMIB,SATELLITEHUB_KOTA,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_KOTA,SATELLITEHUB_KOTA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
4,882107,NaN,ARLP0000001631,FSD_LARGE,ARL,SINGER LEO 3L WH,882107,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-16T20:33:40.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,333042.0,JHUJHUNU,RAJASTHAN,2026-02-07T22:35:06.000+05:30,2.0,2026-02-07T22:34:55.000+05:30,2026-02-09,NaN,2026-02-12T20:00:37.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T20:33:40.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,4640.0,0.0,3400.0,ROI,False,NaN,2026-02-18T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_JHUNJHUNU,2026-02-18,NaN,SPS,41.0,23.0,3400.0,26.0,SATELLITEHUB_JHUNJHUNU,SATELLITEHUB_JHUNJHUNU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480187,G9S1EO8V6RJUC3JD,NaN,UNCP0000309219,FSD_LARGE,UNC,BANK NOTES,BANK NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-06T17:31:36.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,482002.0,JABALPUR,MADHYA PRADESH,2026-01-30T15:46:09.000+05:30,4.0,2026-01-30T15:46:04.000+05:30,2026-02-02,2026-02-02T20:25:42.000+05:30,2026-02-06T06:44:08.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T17:31:36.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,4130.0,ROI,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JLR,2026-02-07,2026-02-02,SPS,19.0,13.0,4130.0,25.0,SatelliteHub_JLR,SatelliteHub_JLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,5.0
480188,64B1EZX31KGO5GB1,NaN,UNCP0000309258,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-07T21:40:56.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,410506.0,PUNE,MAHARASHTRA,2026-01-30T15:46:01.000+05:30,3.0,2026-01-30T15:45:56.000+05:30,2026-02-03,2026-02-03T04:12:16.000+05:30,2026-02-07T06:55:08.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T21:40:56.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,8000.0,METRO,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_PCMC,2026-02-07,2026-02-03,SPS,39.0,13.0,8000.0,26.0,Satellitehub_PCMC,Satellitehub_PCMC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,5.0
480189,1UFR4ZNPP3Y9KD02,NaN,UNCP0000309428,FSD_LARGE,UNC,CAFOACCRK,CAFOACCRK,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-10T21:23:16.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,400089.0,MUMBAI,MAHARASHTRA,2026-02-05T16:46:30.000+05:30,1.0,2026-02-05T16:46:24.000+05:30,2026-02-06,2026-02-06T20:41:47.000+05:30,2026-02-10T08:52:18.000+05:30,2026-02-10T10:41:31.000+05:30,2026-02-10T10:41:31.000+05:30,2026-02-10T21:23:16.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,0.0,3920.0,METRO,False,NaN,2026-02-10T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_CHV,2026-02-10,2026-02-06,SPS,19.0,12.0,3920.0,25.0,SatelliteHub_CHV,SatelliteHub_CHV,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
480190,V3CS2ZWC6N,NaN,UNCP0000310061,FSD_LARGE,UNC,IIT_PCM_12_4.0,IIT_PCM_12_4.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-28T21:42:24.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,211011.0,ALLAHABAD,UTTAR PRADESH,2026-02-18T16:32:06.000+05:30,3.0,2026-02-18T16:32:02.000+05:30,2026-02-20,2026-02-20T19:38:43.000+05:30,2026-02-28T03:57:48.000+05:30,2026-02-28T07:25:13.000+05:30,2026-02-28T07:25:13.000+05:30,2026-02-28T21:42:24.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,5080.0,ROI,False,NaN,2026-02-28T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_ALD,2026-02-28,2026-02-20,SPS,24.0,12.0,5080.0,29.0,SatelliteHub_ALD,SatelliteHub_ALD,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
480191,K94PJD9GLXKCNWT0,NaN,UNCP0000310148,FSD_LARGE,UNC,IIT JEE 4.0 NOTES,IIT JEE 4.0 NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-27T20:30:51.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,302033.0,JAIPUR,RAJASTHAN,2026-02-20T14:56:15.000+05:30,2.0,2026-02-20T14:56:10.000+05:30,2026-02-21,2026-02-21T19:18:31.000+05:30,2026-02-27T07:06:41.000+05:30,2026-02-27T08:11:57.000+05:30,2026-02-27T08:11:57.000+05:30,2026-02-27T20:30:51.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,3000.0,0.0,8970.0,ROI,False,NaN,2026-02-28T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_JAISITAPURA,2026-02-28,2026-02-21,SPS,22.0,22.0,8970.0,29.0,SATELLITEHUB_JAISITAPURA,SATELLITEHUB_JAISITAPURA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0

In [12]:
d9=dif.drop_duplicates(subset='tracking_id')
d9

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,dispatch_month
0,TFC001511752,NaN,AMAP0000000097,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-05-06T00:00:08.000+05:30,ShipmentUndeliveredAttempted,110086.0,Delhi,DELHI,682030.0,ERNAKULAM,KERALA,2026-04-28T08:19:25.000+05:30,1.0,2026-04-28T08:19:20.000+05:30,2026-04-28,2026-04-28T13:59:25.000+05:30,2026-05-04T06:24:00.000+05:30,2026-05-05T11:23:57.000+05:30,2026-05-05T11:23:57.000+05:30,NaN,Attempted,NaN,1.0,RequestForReschedule,RequestForReschedule,NaN,RequestForReschedule,NaN,NaN,NaN,6738.3,0.0,19000.0,ROI,False,NaN,2026-05-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_KOC,2026-05-05,2026-04-28,SPS,130.0,30.0,19000.0,30.0,SATELLITEHUB_KOC,SATELLITEHUB_KOC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,4.0
1,885596,NaN,ARLP0000001325,FSD_LARGE,ARL,SINGER COOKMATE 5L,885596,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-13T20:06:13.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,282001.0,AGRA,UTTAR PRADESH,2026-02-07T22:35:35.000+05:30,2.0,2026-02-07T22:34:58.000+05:30,2026-02-09,NaN,2026-02-13T02:01:56.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T20:06:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-15T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_AGR1,2026-02-15,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_AGR1,SATELLITEHUB_AGR1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
2,885835,NaN,ARLP0000001328,FSD_LARGE,ARL,SINGER COOKMATE 5L,885835,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-19T17:43:18.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,147105.0,PATIALA,PUNJAB,2026-02-07T22:35:26.000+05:30,5.0,2026-02-07T22:34:58.000+05:30,2026-02-12,NaN,2026-02-18T10:09:16.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T17:43:18.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_Sangrur,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_Sangrur,SATELLITEHUB_Sangrur,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
3,907611,NaN,ARLP0000001553,FSD_LARGE,ARL,SINGER COOKMATE 5L,907611,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-24T18:56:35.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,323601.0,KESHORAIPATAN,RAJASTHAN,2026-02-07T22:35:04.000+05:30,5.0,2026-02-07T22:34:52.000+05:30,2026-02-12,NaN,2026-02-19T06:09:01.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T18:56:35.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T00:00:00+0530,Pickuphub_FKMIB,SATELLITEHUB_KOTA,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_KOTA,SATELLITEHUB_KOTA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
4,882107,NaN,ARLP0000001631,FSD_LARGE,ARL,SINGER LEO 3L WH,882107,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-16T20:33:40.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,333042.0,JHUJHUNU,RAJASTHAN,2026-02-07T22:35:06.000+05:30,2.0,2026-02-07T22:34:55.000+05:30,2026-02-09,NaN,2026-02-12T20:00:37.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T20:33:40.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,4640.0,0.0,3400.0,ROI,False,NaN,2026-02-18T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_JHUNJHUNU,2026-02-18,NaN,SPS,41.0,23.0,3400.0,26.0,SATELLITEHUB_JHUNJHUNU,SATELLITEHUB_JHUNJHUNU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480184,9GPUWN8KZ9WJFKJ2,NaN,UNCP0000308607,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-01-28T22:30:00.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,110085.0,NEW DELHI,DELHI,2026-01-22T12:51:53.000+05:30,1.0,2026-01-22T12:51:47.000+05:30,2026-01-22,2026-01-22T20:04:44.000+05:30,NaN,2026-01-27T08:36:13.000+05:30,2026-01-28T10:12:53.000+05:30,2026-01-28T22:30:00.000+05:30,Attempted,NaN,2.0,Customer Not Responding,Customer Not Responding,NaN,Customer Not Responding,NaN,NaN,NaN,3000.0,0.0,8000.0,METRO,False,NaN,2026-01-27T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_SAMAYPURDEPO,2026-01-27,2026-01-22,SPS,39.0,13.0,8000.0,26.0,SATELLITEHUB_SAMAYPURDEPO,SATELLITEHUB_SAMAYPURDEPO,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,4.0
480185,QCRWUID3QI246XZ2,NaN,UNCP0000308715,FSD_LARGE,UNC,GATE MECHANICAL,GATE MECHANICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,L,True,2026-01-26T18:42:47.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,560063.0,BANGALORE,KARNATAKA,2026-01-23T16:20:55.000+05:30,1.0,2026-01-23T16:20:47.000+05:30,2026-01-24,2026-01-24T21:12:38.000+05:30,NaN,2026-01-26T08:06:33.000+05:30,2026-01-26T08:06:33.000+05:30,2026-01-26T18:42:47.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,0.0,5090.0,LOCAL,False,NaN,2026-01-26T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_YEL,2026-01-26,2026-01-24,SPS,19.0,16.0,5090.0,25.0,SATELLITEHUB_YEL,SATELLITEHUB_YEL,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,4.0
480186,HMJ0IK5033JBLQE0,NaN,UNCP0000308804,FSD_LARGE,UNC,GATE DSAI,GATE DSAI,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,RTO,RTO,PP,N,True,2026-03-19T16:52:45.000+05:30,ShipmentRtoCompleted,560062.0,Bengaluru,KARNATAKA,400027.0,MUMBAI,MAHARASHTRA,2026-01-27T16:34:22.000+05:30,2.0,2026-01-27T16:34:10.000+05:30,2026-01-28,2026-01-28T21:31:13.000+05:30,2026-02-02T22:19:59.000+05:30,2026-02-02T22:35:05.000+05:30,2026-02-02T22:35:05.000+05:30,NaN,Attempted,2026-03-11T22:27:45.000+05:30,1.0,HeavyLoad,HeavyLoad,SatelliteHub_RRD,HeavyLoad,Shipment Delayed,NaN,ManpowerIssue,3000.0,0.0,1530.0,METRO,True,NaN,2026-02-01T03:15:00+0530,Pickuphub_FKBGR2,NaN,2026-02-01,2026-01-28,SPS,20.0,4.0,1530.0,25.0,SatelliteHub_RRD,Pickuphub_MpHub_FKBGR2,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,4.0
480187,G9S1EO8V6RJUC3JD,NaN,UNCP0000309219,FSD_LARGE,UNC,BANK NOTES,BANK NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-06T17:31:36.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,482002.0,JABALPUR,MADHYA PRADESH,2026-01-30T15:46:09.000+05:30,4.0,2026-01-30T15:46:04.000+05:30,2026-02-02,2026-02-02T20:25:42.000+05:30,2026-02-06T06:44:08.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T17:31:36.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,4130.0,ROI,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JLR,2026-02-07,2026-02-02,SPS,19.0,13.0,4130.0,25.0,SatelliteHub_JLR,SatelliteHub_JLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,5.0
480188,64B1EZX31KGO5GB1,NaN,UNCP0000309258,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-07T21:40:56.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,410506.0,PUNE,MAHARASHTRA,2026-01-30T15:46:01.000+05:30,3.0,2026-01-30T15:45:56.000+05:30,2026-02-03,2026-02-03T04:12:16.000+05:30,2026-02-07T06:55:08.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T21:40:56.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,8000.0,METRO,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_PCMC,2026-02-07,2026-02-03,SPS,39.0,13.0,8000.0,26.0,Satellitehub_PCMC,Satellitehub_PCMC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,5.0

In [13]:
d9.dispatch_date.isnull().sum()

np.int64(1391)

In [14]:
d9.dispatch_date.value_counts()

dispatch_date
2026-04-16T00:00:00.000+05:30    459
2026-05-06T00:00:00.000+05:30    408
2026-05-03T00:00:00.000+05:30    400
2026-04-01T13:52:12.000+05:30    241
2026-03-23T15:37:13.000+05:30    225
                                ...
2026-01-03T09:20:59.000+05:30      1
2026-02-02T11:00:44.000+05:30      1
2026-01-16T10:53:27.000+05:30      1
2026-01-30T15:45:57.000+05:30      1
2026-01-05T15:26:07.000+05:30      1
Name: count, Length: 498779, dtype: int64

In [15]:
#d9['dispatch_date'] = pd.to_datetime(d9['dispatch_date'].format="%Y-%m-%d")).dt.date
#d9['dispatch_month'] = pd.to_datetime(d9['dispatch_date'], format="%Y-%m-%d").dt.month
#d9['dispatch_month'] = d9['dispatch_date'].apply(lambda x: pd.to_datetime(x).strftime('%Y-%m-%d')).apply(lambda x: pd.to_datetime(x, format="%Y-%m-%d").month)
#d9['dispatch_month'] = d9['dispatch_date'].apply(lambda x: pd.to_datetime(x).strftime('%Y-%m-%d') if not pd.isnull(x) else pd.NaT).apply(lambda x: pd.to_datetime(x, format="%Y-%m-%d").month)

In [16]:
#d9["dispatch_month"] =  pd.to_datetime(d9["dispatch_date"],format="%Y-%m-%d %H:%M:%S").dt.month
#d9["dispatch_month"] = pd.to_datetime(d9["dispatch_date"],format="%Y-%m-%d").dt.month
d9["dispatch_month"] = pd.to_datetime(d9["dispatch_date"], format='mixed').dt.month
#d9["created_month"] = pd.to_datetime(d9["created_at"], format="%Y-%m-%d %H:%M:%S", errors='coerce').dt.month
#d9["ph_in_month"] = pd.to_datetime(d9["ph_in_time"], format="%Y-%m-%d %H:%M:%S", errors='coerce').dt.month

#d9["created_month"] =  pd.to_datetime(d9["created_at"],format="%Y-%m-%d %H:%M:%S").dt.month
#d9["ph_in_month"] =  pd.to_datetime(d9["ph_in_time"],format="%Y-%m-%d %H:%M:%S").dt.month
#d9

In [17]:
d9.dispatch_month.value_counts()

dispatch_month
4.0     258821
3.0     234833
2.0     202867
1.0     187436
5.0      30067
11.0         1
Name: count, dtype: int64

In [18]:
d91=d9[~d9['current_status'].isin(['PickupCancelled','OutForPickupEvent','PickupRescheduledEvent'])]
d91

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,dispatch_month
0,TFC001511752,NaN,AMAP0000000097,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-05-06T00:00:08.000+05:30,ShipmentUndeliveredAttempted,110086.0,Delhi,DELHI,682030.0,ERNAKULAM,KERALA,2026-04-28T08:19:25.000+05:30,1.0,2026-04-28T08:19:20.000+05:30,2026-04-28,2026-04-28T13:59:25.000+05:30,2026-05-04T06:24:00.000+05:30,2026-05-05T11:23:57.000+05:30,2026-05-05T11:23:57.000+05:30,NaN,Attempted,NaN,1.0,RequestForReschedule,RequestForReschedule,NaN,RequestForReschedule,NaN,NaN,NaN,6738.3,0.0,19000.0,ROI,False,NaN,2026-05-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_KOC,2026-05-05,2026-04-28,SPS,130.0,30.0,19000.0,30.0,SATELLITEHUB_KOC,SATELLITEHUB_KOC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,4.0
1,885596,NaN,ARLP0000001325,FSD_LARGE,ARL,SINGER COOKMATE 5L,885596,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-13T20:06:13.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,282001.0,AGRA,UTTAR PRADESH,2026-02-07T22:35:35.000+05:30,2.0,2026-02-07T22:34:58.000+05:30,2026-02-09,NaN,2026-02-13T02:01:56.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T20:06:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-15T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_AGR1,2026-02-15,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_AGR1,SATELLITEHUB_AGR1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
2,885835,NaN,ARLP0000001328,FSD_LARGE,ARL,SINGER COOKMATE 5L,885835,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-19T17:43:18.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,147105.0,PATIALA,PUNJAB,2026-02-07T22:35:26.000+05:30,5.0,2026-02-07T22:34:58.000+05:30,2026-02-12,NaN,2026-02-18T10:09:16.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T17:43:18.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_Sangrur,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_Sangrur,SATELLITEHUB_Sangrur,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
3,907611,NaN,ARLP0000001553,FSD_LARGE,ARL,SINGER COOKMATE 5L,907611,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-24T18:56:35.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,323601.0,KESHORAIPATAN,RAJASTHAN,2026-02-07T22:35:04.000+05:30,5.0,2026-02-07T22:34:52.000+05:30,2026-02-12,NaN,2026-02-19T06:09:01.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T18:56:35.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T00:00:00+0530,Pickuphub_FKMIB,SATELLITEHUB_KOTA,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_KOTA,SATELLITEHUB_KOTA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
4,882107,NaN,ARLP0000001631,FSD_LARGE,ARL,SINGER LEO 3L WH,882107,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-16T20:33:40.000+05:30,ShipmentDelivered,401107.0,thane,MAHARASHTRA,333042.0,JHUJHUNU,RAJASTHAN,2026-02-07T22:35:06.000+05:30,2.0,2026-02-07T22:34:55.000+05:30,2026-02-09,NaN,2026-02-12T20:00:37.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T20:33:40.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,4640.0,0.0,3400.0,ROI,False,NaN,2026-02-18T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_JHUNJHUNU,2026-02-18,NaN,SPS,41.0,23.0,3400.0,26.0,SATELLITEHUB_JHUNJHUNU,SATELLITEHUB_JHUNJHUNU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480184,9GPUWN8KZ9WJFKJ2,NaN,UNCP0000308607,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-01-28T22:30:00.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,110085.0,NEW DELHI,DELHI,2026-01-22T12:51:53.000+05:30,1.0,2026-01-22T12:51:47.000+05:30,2026-01-22,2026-01-22T20:04:44.000+05:30,NaN,2026-01-27T08:36:13.000+05:30,2026-01-28T10:12:53.000+05:30,2026-01-28T22:30:00.000+05:30,Attempted,NaN,2.0,Customer Not Responding,Customer Not Responding,NaN,Customer Not Responding,NaN,NaN,NaN,3000.0,0.0,8000.0,METRO,False,NaN,2026-01-27T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_SAMAYPURDEPO,2026-01-27,2026-01-22,SPS,39.0,13.0,8000.0,26.0,SATELLITEHUB_SAMAYPURDEPO,SATELLITEHUB_SAMAYPURDEPO,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0
480185,QCRWUID3QI246XZ2,NaN,UNCP0000308715,FSD_LARGE,UNC,GATE MECHANICAL,GATE MECHANICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,L,True,2026-01-26T18:42:47.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,560063.0,BANGALORE,KARNATAKA,2026-01-23T16:20:55.000+05:30,1.0,2026-01-23T16:20:47.000+05:30,2026-01-24,2026-01-24T21:12:38.000+05:30,NaN,2026-01-26T08:06:33.000+05:30,2026-01-26T08:06:33.000+05:30,2026-01-26T18:42:47.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,0.0,5090.0,LOCAL,False,NaN,2026-01-26T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_YEL,2026-01-26,2026-01-24,SPS,19.0,16.0,5090.0,25.0,SATELLITEHUB_YEL,SATELLITEHUB_YEL,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0
480186,HMJ0IK5033JBLQE0,NaN,UNCP0000308804,FSD_LARGE,UNC,GATE DSAI,GATE DSAI,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,RTO,RTO,PP,N,True,2026-03-19T16:52:45.000+05:30,ShipmentRtoCompleted,560062.0,Bengaluru,KARNATAKA,400027.0,MUMBAI,MAHARASHTRA,2026-01-27T16:34:22.000+05:30,2.0,2026-01-27T16:34:10.000+05:30,2026-01-28,2026-01-28T21:31:13.000+05:30,2026-02-02T22:19:59.000+05:30,2026-02-02T22:35:05.000+05:30,2026-02-02T22:35:05.000+05:30,NaN,Attempted,2026-03-11T22:27:45.000+05:30,1.0,HeavyLoad,HeavyLoad,SatelliteHub_RRD,HeavyLoad,Shipment Delayed,NaN,ManpowerIssue,3000.0,0.0,1530.0,METRO,True,NaN,2026-02-01T03:15:00+0530,Pickuphub_FKBGR2,NaN,2026-02-01,2026-01-28,SPS,20.0,4.0,1530.0,25.0,SatelliteHub_RRD,Pickuphub_MpHub_FKBGR2,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,1.0
480187,G9S1EO8V6RJUC3JD,NaN,UNCP0000309219,FSD_LARGE,UNC,BANK NOTES,BANK NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-06T17:31:36.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,482002.0,JABALPUR,MADHYA PRADESH,2026-01-30T15:46:09.000+05:30,4.0,2026-01-30T15:46:04.000+05:30,2026-02-02,2026-02-02T20:25:42.000+05:30,2026-02-06T06:44:08.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T17:31:36.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,4130.0,ROI,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JLR,2026-02-07,2026-02-02,SPS,19.0,13.0,4130.0,25.0,SatelliteHub_JLR,SatelliteHub_JLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0
480188,64B1EZX31KGO5GB1,NaN,UNCP0000309258,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-07T21:40:56.000+05:30,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,410506.0,PUNE,MAHARASHTRA,2026-01-30T15:46:01.000+05:30,3.0,2026-01-30T15:45:56.000+05:30,2026-02-03,2026-02-03T04:12:16.000+05:30,2026-02-07T06:55:08.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T21:40:56.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,8000.0,METRO,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_PCMC,2026-02-07,2026-02-03,SPS,39.0,13.0,8000.0,26.0,Satellitehub_PCMC,Satellitehub_PCMC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0

In [19]:
#d91['created_at'] = pd.to_datetime(d91['created_at'],format='%Y-%m-%d %H:%M:%S').dt.date
#d91['ph_in_time'] = pd.to_datetime(d91['ph_in_time'],format='%Y-%m-%d %H:%M:%S').dt.date
d91['created_at'] = pd.to_datetime(d91['created_at'],format='mixed').dt.date
d91['ph_in_time'] = pd.to_datetime(d91['ph_in_time'],format='mixed').dt.date

In [20]:
d91['PH_IN_date']=d91['ph_in_time']
#d91['PH_IN_date'] = d91['PH_IN_date'].apply(lambda x: pd.to_datetime(x, format="%Y-%m-%d").date() if isinstance(x, str) else pd.NaT)
d91['PH_IN_date'] = pd.to_datetime(d91['PH_IN_date'],format='mixed').dt.date
d91['last_updated_at'] = pd.to_datetime(d91['last_updated_at'],format='mixed').dt.date
d91.last_updated_at.value_counts()

last_updated_at
2026-05-05    33890
2026-05-04    15583
2026-02-03    13667
2026-04-11    11216
2026-03-18    10601
              ...
2026-02-01     2839
2026-01-06     1700
2026-01-05      634
2026-01-04       25
2026-01-03        1
Name: count, Length: 124, dtype: int64

In [21]:
d91['FDP_status']=np.where((d91['current_status'] == 'ShipmentDelivered') & (d91['ekl_shipment_type'] == 'Forward'),'delivered',
                    np.where((d91['current_status'] == 'ShipmentRtoCompleted') & (d91['ekl_shipment_type'] == 'RTO'), 'Returned_to_seller','Open'))

d91.FDP_status.value_counts()

FDP_status
delivered             769121
Open                   86648
Returned_to_seller     59647
Name: count, dtype: int64

In [22]:
d91['FDP_status'] = np.where((d91['FDP_status'] == "Open") & (d91['ekl_shipment_type'] == 'RTO'),"Open-RTO", d91.FDP_status)
d91.FDP_status.value_counts()

FDP_status
delivered             769121
Open                   80107
Returned_to_seller     59647
Open-RTO                6541
Name: count, dtype: int64

In [23]:
d91['end_date'] = d91['last_updated_at']

In [24]:
d91['PH_IN_date'] = pd.to_datetime(d91['PH_IN_date'], format='%Y-%m-%d %H:%M:%S')
d91['end_date'] = pd.to_datetime(d91['end_date'], format='%Y-%m-%d %H:%M:%S')
d91['ageing'] = (d91['end_date'] - d91['PH_IN_date']).dt.days

In [25]:
d91.ageing.value_counts()

ageing
 4.0     156970
 3.0     148444
 5.0     129917
 2.0     107171
 6.0      92388
          ...
 79.0         2
 88.0         1
 72.0         1
-4.0          1
 78.0         1
Name: count, Length: 87, dtype: int64

In [26]:
m1=d91[d91['FDP_status'].isin(['Open','Open-RTO'])]
m1

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,dispatch_month,PH_IN_date,FDP_status,end_date,ageing
0,TFC001511752,NaN,AMAP0000000097,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-05-06,ShipmentUndeliveredAttempted,110086.0,Delhi,DELHI,682030.0,ERNAKULAM,KERALA,2026-04-28,1.0,2026-04-28T08:19:20.000+05:30,2026-04-28,2026-04-28,2026-05-04T06:24:00.000+05:30,2026-05-05T11:23:57.000+05:30,2026-05-05T11:23:57.000+05:30,NaN,Attempted,NaN,1.0,RequestForReschedule,RequestForReschedule,NaN,RequestForReschedule,NaN,NaN,NaN,6738.3,0.0,19000.0,ROI,False,NaN,2026-05-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_KOC,2026-05-05,2026-04-28,SPS,130.0,30.0,19000.0,30.0,SATELLITEHUB_KOC,SATELLITEHUB_KOC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,4.0,2026-04-28,Open,2026-05-06,8.0
8,ORD-SO-689141,NaN,AWPC0000088038,FSD_LARGE,AWP,UPL SAAF 1KG,CPB5B11AN79CF17A00A60,ext_sps,AWP,AWP : Gurugram WH,AWP_115d5b145766f4614e8e6d0b8d979af0,Forward,SHIPMENT,COD,N,True,2026-05-04,InScanAtHub,122413.0,Gurugram,HARYANA,743710.0,ALIPORE,WEST BENGAL,2026-05-04,1.0,2026-05-04T10:55:50.000+05:30,2026-05-04,2026-05-04,NaN,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5964.0,4180.0,11200.0,ROI,False,NaN,2026-05-09T03:15:00+0530,PICKUPHUB_BLPFM,CentralHub_L_KAL1,2026-05-09,2026-05-04,SPS,43.0,31.0,11200.0,34.0,NaN,Satellitehub_NTHP,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2026-05-04,Open,2026-05-04,0.0
9,ORD-SO-687566,NaN,AWPC0000088132,FSD_LARGE,AWP,EXCEL MERA 71 100G,CPB9C96AD26BO50A00A14,ext_sps,AWP,AWP : Patna WH,AWP_06690e9940963d92d58bcb3a6563d29c,Forward,SHIPMENT,COD,Z,True,2026-05-05,InscannedAtDH,803201.0,Patna,BIHAR,841210.0,SARAN,BIHAR,2026-05-03,1.0,2026-05-03T11:58:28.000+05:30,2026-05-03,2026-05-03,2026-05-05T11:42:29.000+05:30,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9453.0,6617.0,14520.0,ZONAL,False,NaN,2026-05-07T03:15:00+0530,PickupHub_PAT,SatelliteHub_SWN,2026-05-07,2026-05-03,SPS,67.0,27.0,14520.0,30.0,NaN,SatelliteHub_SWN,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2026-05-03,Open,2026-05-05,2.0
20,ORD-SO-685710,AWPN0001088299,AWPC0001088299,FSD_LARGE,AWP,KHUBLAL AGRO COBRA 1KG,SO-685710,ext_mps,AWP,AWP : Gurugram WH,AWP_4ebbda9a31417b3e1b2895faa0e5c27d,Forward,SHIPMENT,COD,N,True,2026-05-05,PrimaryInscan,122413.0,Gurugram,HARYANA,852138.0,SAHARSA,BIHAR,2026-05-01,1.0,2026-05-01T14:26:05.000+05:30,2026-05-01,2026-05-01,2026-05-05T05:23:10.000+05:30,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3220.0,2220.0,26000.0,ROI,False,AWPN0001088299,2026-05-07T12:11:28+0530,PICKUPHUB_BLPFM,Satellitehub_SPL2,2026-05-07,2026-05-01,MPS,64.0,39.0,26000.0,14.0,NaN,Satellitehub_SPL2,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2026-05-01,Open,2026-05-05,4.0
21,ORD-SO-683545,AWPN0001088477,AWPC0001088473,FSD_LARGE,AWP,ATUL SALIX 500G,SO-683545,ext_mps,AWP,AWP : Naveen Kumar,AWP_07244bb3805e9199e4db17a298d96c62,Forward,SHIPMENT,COD,Z,True,2026-05-03,PrimaryInscan,132001.0,Karnal,HARYANA,261501.0,SITAPUR,UTTAR PRADESH,2026-04-29,1.0,2026-04-29T22:19:01.000+05:30,2026-04-30,2026-04-30,2026-05-03T20:49:52.000+05:30,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17860.0,15860.0,11580.0,ZONAL,False,AWPN0001088477,2026-05-06T22:44:04+0530,PickupHub_KNL1,SATELLITEHUB_SITAPUR,2026-05-06,2026-04-30,MPS,45.0,33.0,11580.0,26.0,NaN,SATELLITEHUB_SITAPUR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2026-04-30,Open,2026-05-03,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479183,RXN5PXHJ46OEQ4BC,NaN,UNCP0000308891,FSD_LARGE,UNC,BANK NOTES,BANK NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,L,True,2026-01-30,ShipmentOutForDelivery,560062.0,Bengaluru,KARNATAKA,560037.0,BANGALORE,KARNATAKA,2026-01-27,2.0,2026-01-27T16:34:10.000+05:30,2026-01-28,2026-01-28,NaN,2026-01-30T08:15:46.000+05:30,2026-01-30T08:15:46.000+05:30,NaN,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,4130.0,LOCAL,False,NaN,2026-01-30T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_FKMHP1,2026-01-30,2026-01-28,SPS,19.0,13.0,4130.0,25.0,SATELLITEHUB_FKMHP1,SATELLITEHUB_FKMHP1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-01-28,Open,2026-01-30,2.0
479295,N1JOEKHQF96CQKYJ,NaN,UNCP0000308749,FSD_LARGE,UNC,Yoddha Team,Yoddha Team,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,L,True,2026-01-30,InScanAtHub,560062.0,Bengaluru,KARNATAKA,560035.0,BANGALORE,KARNATAKA,2026-01-23,7.0,2026-01-23T16:20:40.000+05:30,2026-01-29,2026-01-29,NaN,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,3480.0,LOCAL,False,NaN,2026-01-31T03:15:00+0530,Pickuphub_FKBGR2,CentralHub_MPL1,2026-01-31,2026-01-29,SPS,30.0,8.0,3480.0,21.0,NaN,SATELLITEHUB_FKSJPR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-01-29,Open,2026-01-30,1.0
479480,NJ3KBHEW33BRISS2,NaN,UNCP0000309129,FSD_LARGE,UNC,NEET UG ENG 4.0 FULL KITS,NEET UG ENG 4.0 FULL KITS,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,Z,True,2026-01-30,InScanAtHub,560062.0,Bengaluru,KARNATAKA,575001.0,MANGALORE,KARNATAKA,2026-01-28,3.0,2026-01-28T17:18:24.000+05:30,2026-01-29,2026-01-29,NaN,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,6640.0,ZONAL,False,NaN,2026-01-31T03:15:00+0530,Pickuphub_FKBGR2,CentralHub_MPL1,2026-01-31,2026-01-29,SPS,20.0,19.0,6640.0,26.0,NaN,SATELLITEHUB_FKMLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-01-29,Open,2026-01-30,1.0
480126,9KYIIXQ9F3F917UM,NaN,UNCP0000308829,FSD_LARGE,UNC,GATE - CS & IT FULL KIT,GATE - CS & IT FULL KIT,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,Z,True,2026-01-30,InScanAtHub,560062.0,Bengaluru,KARNATAKA,641035.0,COIMBATORE,TAMIL NADU,2026-01-27,2.0,2026-01-27T16:34:10.000+05:30,2026-01-28,2026-01-28,NaN,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,3740.0,ZONAL,False,NaN,2026-01-31T03:15:00+0530,Pickuphub_FKBGR2,CentralHub_L_CJB3,2026-01-31,2026-01-28,SPS,19.0,13.0,3740.0,25.0,NaN,SATELLITEHUB_FKCJB,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-01-28,Open,2026-01-30,2.0
480176,YGEKKY4ZUHJ5Q7E7,NaN,UNCP0000308976,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,L,True,2026-01-30,InScanAtHub,560062.0,Bengaluru,KARNATAKA,560074.0,BANGALORE,KARNATAKA,2026-01-27,4.0,2026-01-27T16:34:10.000+05:30,2026-01-29,2026-01-29,NaN,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,8000.0,LOCAL,False,NaN,2026-01-31T03:15:00+0530,Pickuphub_FKBGR2,CentralHub_MPL1,2026-01-31,2026-01-29,SPS,39.0,13.0,8000.0,26.0,NaN,SatelliteHub_YWP1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-01-29,Open,2026-01-30,1.0

In [27]:
#os.chdir(r"C:\Users\attlakumar.vc\Desktop\Python Data\Large Check File")
m1.to_csv("large_mt_06_May_1.csv",index=False)

In [28]:
#os.chdir(r"C:\Users\mohammadali1.vc\Desktop\Python data\Large Check File")
mt1=pd.read_csv("Multitrack 06-05-2026.csv")
mt1 = pd.DataFrame({col.replace(' ', '_'): mt1[col] for col in mt1.columns})
mt1

C:\Users\mohammadali1.vc\AppData\Local\Temp\ipykernel_10132\3111211474.py:2: DtypeWarning: Columns (0: Shipment Tier Type, 1: Type, 2: Latest Status, 3: Delivery Hub, 4: Current Location, 5: Latest Update Time, 6: First Receive Hub, 7: First Receive Time, 8: Hub Notes, 9: Cs Notes, 10: Bag Id, 11: BagStatus, 12: Customer Promise Date, 13: Logistics Promise Date, 14: First Assigned Hub Name, 15: Last Receive DateTime, 16: Order Id) have mixed types. Specify dtype option on import or set low_memory=False.
  mt1=pd.read_csv("Multitrack 06-05-2026.csv")

,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor
0,AMAP0000000097,NORMAL_FORWARD,REGULAR,NaN,PP,6738.3,682030.0,Undelivered_Request_For_Reschedule,SATELLITEHUB_KOC,SATELLITEHUB_KOC,05-05-2026 23:55,CENTRALHUB_RPBAGHFM,28-04-2026 21:03,NaN,DELIVERY_DATE_CHANGED: 06-May-2026,1.0,NaN,NaN,06-05-2026 23:59,05-05-2026 03:15,NaN,NaN,SATELLITEHUB_KOC,04-05-2026 06:17,TFC001511752,NaN,NaN,NaN,NaN
1,AWPC0000088038,NORMAL_FORWARD,REGULAR,NaN,COD,5964.0,743710.0,Expected,Satellitehub_NTHP,CentralHub_L_KOL5,05-05-2026 05:56,CENTRALHUB_BLPFM,04-05-2026 20:10,NaN,NaN,0.0,NaN,NaN,09-05-2026 23:59,09-05-2026 03:15,NaN,NaN,Satellitehub_NTHP,04-05-2026 23:35,ORD-SO-689141,NaN,NaN,NaN,NaN
2,AWPC0000088132,NORMAL_FORWARD,REGULAR,NaN,COD,9453.0,841210.0,Out_For_Delivery,SatelliteHub_SWN,SatelliteHub_SWN,05-06-2026 07:21,CentralHub_PAT1,04-05-2026 05:01,NaN,NaN,1.0,NaN,NaN,07-05-2026 23:59,07-05-2026 03:15,NaN,NaN,SatelliteHub_SWN,05-05-2026 11:35,ORD-SO-687566,NaN,NaN,NaN,NaN
3,AWPC0001088299,NORMAL_FORWARD,REGULAR,NaN,COD,3220.0,852138.0,Undelivered_Not_Attended,Satellitehub_SPL2,Satellitehub_SPL2,05-05-2026 05:16,CENTRALHUB_BLPFM,01-05-2026 17:38,NaN,NaN,0.0,NaN,NaN,07-05-2026 23:59,07-05-2026 12:11,NaN,NaN,Satellitehub_SPL2,05-05-2026 05:16,ORD-SO-685710,NaN,NaN,NaN,NaN
4,AWPC0001088473,NORMAL_FORWARD,REGULAR,NaN,COD,17860.0,261501.0,Undelivered_Not_Attended,SATELLITEHUB_SITAPUR,SATELLITEHUB_SITAPUR,05-03-2026 20:42,CentralHub_KNL1,30-04-2026 17:18,NaN,NaN,0.0,NaN,NaN,06-05-2026 23:59,06-05-2026 22:44,NaN,NaN,SATELLITEHUB_SITAPUR,03-05-2026 20:42,ORD-SO-683545,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86643,UNCP0000308891,Shipment not found in CL systems!!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86644,UNCP0000308749,Shipment not found in CL systems!!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86645,UNCP0000309129,Shipment not found in CL systems!!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86646,UNCP0000308829,Shipment not found in CL systems!!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86647,UNCP0000308976,Shipment not found in CL systems!!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
merge2 = pd.merge(left=d91,right=mt1,left_on='tracking_id',right_on='Tracking_Id',how='left')
merge2

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor
0,TFC001511752,NaN,AMAP0000000097,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-05-06,ShipmentUndeliveredAttempted,110086.0,Delhi,DELHI,682030.0,ERNAKULAM,KERALA,2026-04-28,1.0,2026-04-28T08:19:20.000+05:30,2026-04-28,2026-04-28,2026-05-04T06:24:00.000+05:30,2026-05-05T11:23:57.000+05:30,2026-05-05T11:23:57.000+05:30,NaN,Attempted,NaN,1.0,RequestForReschedule,RequestForReschedule,NaN,RequestForReschedule,NaN,NaN,NaN,6738.3,0.0,19000.0,ROI,False,NaN,2026-05-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_KOC,2026-05-05,2026-04-28,SPS,130.0,30.0,19000.0,30.0,SATELLITEHUB_KOC,SATELLITEHUB_KOC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,4.0,2026-04-28,Open,2026-05-06,8.0,AMAP0000000097,NORMAL_FORWARD,REGULAR,NaN,PP,6738.3,682030.0,Undelivered_Request_For_Reschedule,SATELLITEHUB_KOC,SATELLITEHUB_KOC,05-05-2026 23:55,CENTRALHUB_RPBAGHFM,28-04-2026 21:03,NaN,DELIVERY_DATE_CHANGED: 06-May-2026,1.0,NaN,NaN,06-05-2026 23:59,05-05-2026 03:15,NaN,NaN,SATELLITEHUB_KOC,04-05-2026 06:17,TFC001511752,NaN,NaN,NaN,NaN
1,885596,NaN,ARLP0000001325,FSD_LARGE,ARL,SINGER COOKMATE 5L,885596,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-13,ShipmentDelivered,401107.0,thane,MAHARASHTRA,282001.0,AGRA,UTTAR PRADESH,2026-02-07,2.0,2026-02-07T22:34:58.000+05:30,2026-02-09,NaT,2026-02-13T02:01:56.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T20:06:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-15T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_AGR1,2026-02-15,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_AGR1,SATELLITEHUB_AGR1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,885835,NaN,ARLP0000001328,FSD_LARGE,ARL,SINGER COOKMATE 5L,885835,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-19,ShipmentDelivered,401107.0,thane,MAHARASHTRA,147105.0,PATIALA,PUNJAB,2026-02-07,5.0,2026-02-07T22:34:58.000+05:30,2026-02-12,NaT,2026-02-18T10:09:16.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T17:43:18.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_Sangrur,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_Sangrur,SATELLITEHUB_Sangrur,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,907611,NaN,ARLP0000001553,FSD_LARGE,ARL,SINGER COOKMATE 5L,907611,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-24,ShipmentDelivered,401107.0,thane,MAHARASHTRA,323601.0,KESHORAIPATAN,RAJASTHAN,2026-02-07,5.0,2026-02-07T22:34:52.000+05:30,2026-02-12,NaT,2026-02-19T06:09:01.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T18:56:35.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T00:00:00+0530,Pickuphub_FKMIB,SATELLITEHUB_KOTA,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_KOTA,SATELLITEHUB_KOTA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,882107,NaN,ARLP0000001631,FSD_LARGE,ARL,SINGER LEO 3L WH,882107,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-16,ShipmentDelivered,401107.0,thane,MAHARASHTRA,333042.0,JHUJHUNU,RAJASTHAN,2026-02-07,2.0,2026-02-07T22:34:55.000+05:30,2026-02-09,NaT,2026-02-12T20:00:37.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T20:33:40.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,4640.0,0.0,3400.0,ROI,False,NaN,2026-02-18T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_JHUNJHUNU,2026-02-18,NaN,SPS,41.0,23.0,3400.0,26.0,SATELLITEHUB_JHUNJHUNU,SATELLITEHUB_JHUNJHUNU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915411,9GPUWN8KZ9WJFKJ2,NaN,UNCP0000308607,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-01-28,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,110085.0,NEW DELHI,DELHI,2026-01-22,1.0,2026-01-22T12:51:47.000+05:30,2026-01-22,2026-01-22,NaN,2026-01-27T08:36:13.000+05:30,2026-01-28T10:12:53.000+05:30,2026-01-28T22:30:00.000+05:30,Attempted,NaN,2.0,Customer Not Responding,Customer Not Responding,NaN,Customer Not Responding,NaN,NaN,NaN,3000.0,0.0,8000.0,METRO,False,NaN,2026-01-27T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_SAMAYPURDEPO,2026-01-27,2026-01-22,SPS,39.0,13.0,8000.0,26.0,SATELLITEHUB_SAMAYPURDEPO,SATELLITEHUB_SAMAYPURDEPO,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-01-22,delivered,2026-01-28,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
915412,QCRWUID3QI246XZ2,NaN,UNCP0000308715,FSD_LARGE,UNC,GATE MECHANICAL,GATE MECHANICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,L,True,2026-01-26,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,560063.0,BANGALORE,KARNATAKA,2026-01-23,1.0,2026-01-23T16:20:47.000+05:30,2026-01-24,2026-01-24,NaN,2026-01-26T08:06:33.000+05:30,2026-01-26T08:06:33.000+05:30,2026-01-26T18:42:47.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,0.0,5090.0,LOCAL,False,NaN,2026-01-26T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_YEL,2026-01-26,2026-01-24,SPS,19.0,16.0,5090.0,25.0,SATELLITEHUB_YEL,SATELLITEHUB_YEL,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-01-24,delivered,2026-01-26,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
915413,HMJ0IK5033JBLQE0,NaN,UNCP0000308804,FSD_LARGE,UNC,GATE DSAI,GATE DSAI,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,RTO,RTO,PP,N,True,2026-03-19,ShipmentRtoCompleted,560062.0,Bengaluru,KARNATAKA,400027.0,MUMBAI,MAHARASHTRA,2026-01-27,2.0,2026-01-27T16:34:10.000+05:30,2026-01-28,2026-01-28,2026-02-02T22:19:59.000+05:30,2026-02-02T22:35:05.000+05:30,2026-02-02T22:35:05.000+05:30,NaN,Attempted,2026-03-11T22:27:45.000+05:30,1.0,HeavyLoad,HeavyLoad,SatelliteHub_RRD,HeavyLoad,Shipment Delayed,NaN,ManpowerIssue,3000.0,0.0,1530.0,METRO,True,NaN,2026-02-01T03:15:00+0530,Pickuphub_FKBGR2,NaN,2026-02-01,2026-01-28,SPS,20.0,4.0,1530.0,25.0,SatelliteHub_RRD,Pickuphub_MpHub_FKBGR2,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,1.0,2026-01-28,Returned_to_seller,2026-03-19,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
915414,G9S1EO8V6RJUC3JD,NaN,UNCP0000309219,FSD_LARGE,UNC,BANK NOTES,BANK NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-06,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,482002.0,JABALPUR,MADHYA PRADESH,2026-01-30,4.0,2026-01-30T15:46:04.000+05:30,2026-02-02,2026-02-02,2026-02-06T06:44:08.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T17:31:36.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,4130.0,ROI,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JLR,2026-02-07,2026-02-02,SPS,19.0,13.0,4130.0,25.0,SatelliteHub_JLR,SatelliteHub_JLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-02-02,delivered,2026-02-06,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
915415,64B1EZX31KGO5GB1,NaN,UNCP0000309258,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-07,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,410506.0,PUNE,MAHARASHTRA,2026-01-30,3.0,2026-01-30T15:45:56.000+05:30,2026-02-03,2026-02-03,2026-02-07T06:55:08.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T21:40:56.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,8000.0,METRO,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_PCMC,2026-02-07,2026-02-03,SPS,39.0,13.0,8000.0,26.0,Satellitehub_PCMC,Satellitehub_PCMC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-02-03,delivered,2026-02-07,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
print(merge2['Current_Location'].isnull().sum())

859505

In [31]:
merge2['Latest_Update_Time'] = pd.to_datetime(merge2['Latest_Update_Time']).dt.date
merge2['end_date'] = pd.to_datetime(merge2['end_date']).dt.date
merge2['end_date']=np.where((merge2['Shipment_Type'].isin(['NORMAL_FORWARD'])),merge2.Latest_Update_Time,
                            np.where((merge2['Shipment_Type'].isin(['Shipment not found in CL systems!!'])),merge2.last_updated_at,merge2.end_date))

In [32]:
conditions = [
    (merge2['Latest_Status'] == 'Delivered') & (merge2['Cs_Notes'] == 'Marked_As_RTO'),
(merge2['Latest_Status'] == 'Delivered'),
(merge2['Latest_Status'] == 'Delivery_Update'),    
(merge2['Latest_Status'] == 'returned_to_seller'),
(merge2['Latest_Status'] == 'Rejected_By_Seller'),
(merge2['Latest_Status'] == 'Lost'),
(merge2['Shipment_Type']=='Shipment not found in CL systems!!')]
choices = ["Returned_to_seller","delivered","delivered","returned_to_seller","rejected_by_seller","lost","closed<45"]
merge2['ERP_Status'] = np.select(conditions,choices, default="Open")
merge2.ERP_Status.value_counts()

ERP_Status
Open                  875814
closed<45              30737
delivered               8163
rejected_by_seller       653
lost                      27
Returned_to_seller        22
Name: count, dtype: int64

In [33]:
merge2['Final_Status'] = np.where((merge2['FDP_status'] == "Open"),merge2.ERP_Status, merge2.FDP_status)
merge2['Final_Status'] = np.where((merge2['ERP_Status'] == "lost"), "Lost", merge2['Final_Status'])
merge2['Final_Status'] = np.where((merge2['ERP_Status'] == "Returned_to_seller"), "Returned_to_seller", merge2['Final_Status'])
merge2['Final_Status'] = np.where((merge2['ERP_Status'] == "delivered"), "delivered", merge2['Final_Status'])
merge2.Final_Status.value_counts()

Final_Status
delivered             777284
Returned_to_seller     59669
Open                   41063
closed<45              30711
Open-RTO                6512
rejected_by_seller       150
Lost                      27
Name: count, dtype: int64

In [34]:
merge2['Final_Status'] = np.where((merge2['Final_Status'] == "Open") & (merge2['Cs_Notes'] == 'Marked_As_RTO'),"Open-RTO", merge2.Final_Status)
merge2.Final_Status.value_counts()

Final_Status
delivered             777284
Returned_to_seller     59669
Open                   40909
closed<45              30711
Open-RTO                6666
rejected_by_seller       150
Lost                      27
Name: count, dtype: int64

In [35]:
merge2.loc[merge2['Final_Status'].isin(['Open','Open-RTO']),'end_date'] = '2026-05-06'
merge2

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor,ERP_Status,Final_Status
0,TFC001511752,NaN,AMAP0000000097,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-05-06,ShipmentUndeliveredAttempted,110086.0,Delhi,DELHI,682030.0,ERNAKULAM,KERALA,2026-04-28,1.0,2026-04-28T08:19:20.000+05:30,2026-04-28,2026-04-28,2026-05-04T06:24:00.000+05:30,2026-05-05T11:23:57.000+05:30,2026-05-05T11:23:57.000+05:30,NaN,Attempted,NaN,1.0,RequestForReschedule,RequestForReschedule,NaN,RequestForReschedule,NaN,NaN,NaN,6738.3,0.0,19000.0,ROI,False,NaN,2026-05-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_KOC,2026-05-05,2026-04-28,SPS,130.0,30.0,19000.0,30.0,SATELLITEHUB_KOC,SATELLITEHUB_KOC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,4.0,2026-04-28,Open,2026-05-06,8.0,AMAP0000000097,NORMAL_FORWARD,REGULAR,NaN,PP,6738.3,682030.0,Undelivered_Request_For_Reschedule,SATELLITEHUB_KOC,SATELLITEHUB_KOC,2026-05-05,CENTRALHUB_RPBAGHFM,28-04-2026 21:03,NaN,DELIVERY_DATE_CHANGED: 06-May-2026,1.0,NaN,NaN,06-05-2026 23:59,05-05-2026 03:15,NaN,NaN,SATELLITEHUB_KOC,04-05-2026 06:17,TFC001511752,NaN,NaN,NaN,NaN,Open,Open
1,885596,NaN,ARLP0000001325,FSD_LARGE,ARL,SINGER COOKMATE 5L,885596,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-13,ShipmentDelivered,401107.0,thane,MAHARASHTRA,282001.0,AGRA,UTTAR PRADESH,2026-02-07,2.0,2026-02-07T22:34:58.000+05:30,2026-02-09,NaT,2026-02-13T02:01:56.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T20:06:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-15T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_AGR1,2026-02-15,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_AGR1,SATELLITEHUB_AGR1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered
2,885835,NaN,ARLP0000001328,FSD_LARGE,ARL,SINGER COOKMATE 5L,885835,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-19,ShipmentDelivered,401107.0,thane,MAHARASHTRA,147105.0,PATIALA,PUNJAB,2026-02-07,5.0,2026-02-07T22:34:58.000+05:30,2026-02-12,NaT,2026-02-18T10:09:16.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T17:43:18.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_Sangrur,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_Sangrur,SATELLITEHUB_Sangrur,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered
3,907611,NaN,ARLP0000001553,FSD_LARGE,ARL,SINGER COOKMATE 5L,907611,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-24,ShipmentDelivered,401107.0,thane,MAHARASHTRA,323601.0,KESHORAIPATAN,RAJASTHAN,2026-02-07,5.0,2026-02-07T22:34:52.000+05:30,2026-02-12,NaT,2026-02-19T06:09:01.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T18:56:35.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T00:00:00+0530,Pickuphub_FKMIB,SATELLITEHUB_KOTA,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_KOTA,SATELLITEHUB_KOTA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered
4,882107,NaN,ARLP0000001631,FSD_LARGE,ARL,SINGER LEO 3L WH,882107,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-16,ShipmentDelivered,401107.0,thane,MAHARASHTRA,333042.0,JHUJHUNU,RAJASTHAN,2026-02-07,2.0,2026-02-07T22:34:55.000+05:30,2026-02-09,NaT,2026-02-12T20:00:37.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T20:33:40.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,4640.0,0.0,3400.0,ROI,False,NaN,2026-02-18T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_JHUNJHUNU,2026-02-18,NaN,SPS,41.0,23.0,3400.0,26.0,SATELLITEHUB_JHUNJHUNU,SATELLITEHUB_JHUNJHUNU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915411,9GPUWN8KZ9WJFKJ2,NaN,UNCP0000308607,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-01-28,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,110085.0,NEW DELHI,DELHI,2026-01-22,1.0,2026-01-22T12:51:47.000+05:30,2026-01-22,2026-01-22,NaN,2026-01-27T08:36:13.000+05:30,2026-01-28T10:12:53.000+05:30,2026-01-28T22:30:00.000+05:30,Attempted,NaN,2.0,Customer Not Responding,Customer Not Responding,NaN,Customer Not Responding,NaN,NaN,NaN,3000.0,0.0,8000.0,METRO,False,NaN,2026-01-27T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_SAMAYPURDEPO,2026-01-27,2026-01-22,SPS,39.0,13.0,8000.0,26.0,SATELLITEHUB_SAMAYPURDEPO,SATELLITEHUB_SAMAYPURDEPO,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-01-22,delivered,2026-01-28,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered
915412,QCRWUID3QI246XZ2,NaN,UNCP0000308715,FSD_LARGE,UNC,GATE MECHANICAL,GATE MECHANICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,L,True,2026-01-26,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,560063.0,BANGALORE,KARNATAKA,2026-01-23,1.0,2026-01-23T16:20:47.000+05:30,2026-01-24,2026-01-24,NaN,2026-01-26T08:06:33.000+05:30,2026-01-26T08:06:33.000+05:30,2026-01-26T18:42:47.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,0.0,5090.0,LOCAL,False,NaN,2026-01-26T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_YEL,2026-01-26,2026-01-24,SPS,19.0,16.0,5090.0,25.0,SATELLITEHUB_YEL,SATELLITEHUB_YEL,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-01-24,delivered,2026-01-26,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered
915413,HMJ0IK5033JBLQE0,NaN,UNCP0000308804,FSD_LARGE,UNC,GATE DSAI,GATE DSAI,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,RTO,RTO,PP,N,True,2026-03-19,ShipmentRtoCompleted,560062.0,Bengaluru,KARNATAKA,400027.0,MUMBAI,MAHARASHTRA,2026-01-27,2.0,2026-01-27T16:34:10.000+05:30,2026-01-28,2026-01-28,2026-02-02T22:19:59.000+05:30,2026-02-02T22:35:05.000+05:30,2026-02-02T22:35:05.000+05:30,NaN,Attempted,2026-03-11T22:27:45.000+05:30,1.0,HeavyLoad,HeavyLoad,SatelliteHub_RRD,HeavyLoad,Shipment Delayed,NaN,ManpowerIssue,3000.0,0.0,1530.0,METRO,True,NaN,2026-02-01T03:15:00+0530,Pickuphub_FKBGR2,NaN,2026-02-01,2026-01-28,SPS,20.0,4.0,1530.0,25.0,SatelliteHub_RRD,Pickuphub_MpHub_FKBGR2,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,1.0,2026-01-28,Returned_to_seller,2026-03-19,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,Returned_to_seller
915414,G9S1EO8V6RJUC3JD,NaN,UNCP0000309219,FSD_LARGE,UNC,BANK NOTES,BANK NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-06,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,482002.0,JABALPUR,MADHYA PRADESH,2026-01-30,4.0,2026-01-30T15:46:04.000+05:30,2026-02-02,2026-02-02,2026-02-06T06:44:08.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T17:31:36.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,4130.0,ROI,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JLR,2026-02-07,2026-02-02,SPS,19.0,13.0,4130.0,25.0,SatelliteHub_JLR,SatelliteHub_JLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-02-02,delivered,2026-02-06,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered
915415,64B1EZX31KGO5GB1,NaN,UNCP0000309258,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-07,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,410506.0,PUNE,MAHARASHTRA,2026-01-30,3.0,2026-01-30T15:45:56.000+05:30,2026-02-03,2026-02-03,2026-02-07T06:55:08.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T21:40:56.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,8000.0,METRO,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_PCMC,2026-02-07,2026-02-03,SPS,39.0,13.0,8000.0,26.0,Satellitehub_PCMC,Satellitehub_PCMC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-02-03,delivered,2026-02-07,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered

In [36]:
#os.chdir(r"C:\Users\mohammadali1.vc\Desktop\Python data\Large Check File")
disputes=pd.read_csv("Dispute_Check.csv")
disputes1 = disputes.rename(columns={'AWB (TID) Number': 'AWB_TID_number'})
#disputes1 = disputes[['Timestamp','AWB_TID_number','Issue_Category','Proof','Email_Address','Case_type','Reason_for_Re-opening_the_case',
#                     'Seller_Name','Shipment_Type','Remarks/_Proof_Link','Client','Aging','Ageing_Bucket','Status','Reason','Acknowledgement_to_client_(Mail_Subject)',
#                    'Mail_Acknowledge_Date','Closed_By','Relabeling_Done','Ekart_Flyer','Cello_Taping_(Y/N)','Cello_Taping_(Body/_Mouth)',
#                    'Smartcheck_Remark','Product_Received','Description',
#                    'DH-PH_Mapping','PH_or_DH']]
disputes1

C:\Users\mohammadali1.vc\AppData\Local\Temp\ipykernel_10132\4060656932.py:2: DtypeWarning: Columns (0: PH_or_DH) have mixed types. Specify dtype option on import or set low_memory=False.
  disputes=pd.read_csv("Dispute_Check.csv")

,Unnamed: 0,Timestamp,AWB_TID_number,Issue_Category,Status,Reason,PH_or_DH,Seller_type,Payment_Mode
0,0,2025-01-01,SOLC0000044625,Wrong Product,dispute not accepted,Beyond On TAT,NaN,SOL,COD
1,3,2025-01-01,SOLN9900002638,Partial Product Received,dispute not accepted,MPS Shipment,NaN,SOL,NaN
2,4,2025-01-01,SOLC0000045141,Wrong Product,dispute not accepted,Beyond On TAT,NaN,SOL,COD
3,6,2025-01-01,SOLC0000039522,Partial Product Received,dispute not accepted,Intacted Condition,NaN,SOL,COD
4,7,2025-01-01,SOLN9900011022,Partial Product Received,dispute not accepted,MPS Shipment,NaN,SOL,NaN
...,...,...,...,...,...,...,...,...,...
683243,1806425,2026-02-19,SOLC9970056800,RTO POD,open,NaN,NaN,SOL,COD
683244,1806426,2026-02-19,SOLC9970056802,RTO POD,open,NaN,NaN,SOL,COD
683245,1806427,2026-02-19,SOLC9970056347,RTO POD,open,NaN,NaN,SOL,COD
683246,1806428,2026-02-19,FCLC0000538354,RTO POD,open,NaN,NaN,FCL,COD
683247,1806429,2026-02-20,LOIP0000463558,RTO POD,open,NaN,NaN,LOI,Prepaid

In [37]:
mg1=merge2.merge(disputes1,left_on='tracking_id',right_on='AWB_TID_number',how='left')
mg1

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor,ERP_Status,Final_Status,Unnamed: 0,Timestamp,AWB_TID_number,Issue_Category,Status,Reason,PH_or_DH,Seller_type,Payment_Mode
0,TFC001511752,NaN,AMAP0000000097,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-05-06,ShipmentUndeliveredAttempted,110086.0,Delhi,DELHI,682030.0,ERNAKULAM,KERALA,2026-04-28,1.0,2026-04-28T08:19:20.000+05:30,2026-04-28,2026-04-28,2026-05-04T06:24:00.000+05:30,2026-05-05T11:23:57.000+05:30,2026-05-05T11:23:57.000+05:30,NaN,Attempted,NaN,1.0,RequestForReschedule,RequestForReschedule,NaN,RequestForReschedule,NaN,NaN,NaN,6738.3,0.0,19000.0,ROI,False,NaN,2026-05-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_KOC,2026-05-05,2026-04-28,SPS,130.0,30.0,19000.0,30.0,SATELLITEHUB_KOC,SATELLITEHUB_KOC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,4.0,2026-04-28,Open,2026-05-06,8.0,AMAP0000000097,NORMAL_FORWARD,REGULAR,NaN,PP,6738.3,682030.0,Undelivered_Request_For_Reschedule,SATELLITEHUB_KOC,SATELLITEHUB_KOC,2026-05-05,CENTRALHUB_RPBAGHFM,28-04-2026 21:03,NaN,DELIVERY_DATE_CHANGED: 06-May-2026,1.0,NaN,NaN,06-05-2026 23:59,05-05-2026 03:15,NaN,NaN,SATELLITEHUB_KOC,04-05-2026 06:17,TFC001511752,NaN,NaN,NaN,NaN,Open,Open,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,885596,NaN,ARLP0000001325,FSD_LARGE,ARL,SINGER COOKMATE 5L,885596,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-13,ShipmentDelivered,401107.0,thane,MAHARASHTRA,282001.0,AGRA,UTTAR PRADESH,2026-02-07,2.0,2026-02-07T22:34:58.000+05:30,2026-02-09,NaT,2026-02-13T02:01:56.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T20:06:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-15T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_AGR1,2026-02-15,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_AGR1,SATELLITEHUB_AGR1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,885835,NaN,ARLP0000001328,FSD_LARGE,ARL,SINGER COOKMATE 5L,885835,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-19,ShipmentDelivered,401107.0,thane,MAHARASHTRA,147105.0,PATIALA,PUNJAB,2026-02-07,5.0,2026-02-07T22:34:58.000+05:30,2026-02-12,NaT,2026-02-18T10:09:16.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T17:43:18.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_Sangrur,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_Sangrur,SATELLITEHUB_Sangrur,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,907611,NaN,ARLP0000001553,FSD_LARGE,ARL,SINGER COOKMATE 5L,907611,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-24,ShipmentDelivered,401107.0,thane,MAHARASHTRA,323601.0,KESHORAIPATAN,RAJASTHAN,2026-02-07,5.0,2026-02-07T22:34:52.000+05:30,2026-02-12,NaT,2026-02-19T06:09:01.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T18:56:35.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T00:00:00+0530,Pickuphub_FKMIB,SATELLITEHUB_KOTA,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_KOTA,SATELLITEHUB_KOTA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,882107,NaN,ARLP0000001631,FSD_LARGE,ARL,SINGER LEO 3L WH,882107,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-16,ShipmentDelivered,401107.0,thane,MAHARASHTRA,333042.0,JHUJHUNU,RAJASTHAN,2026-02-07,2.0,2026-02-07T22:34:55.000+05:30,2026-02-09,NaT,2026-02-12T20:00:37.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T20:33:40.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,4640.0,0.0,3400.0,ROI,False,NaN,2026-02-18T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_JHUNJHUNU,2026-02-18,NaN,SPS,41.0,23.0,3400.0,26.0,SATELLITEHUB_JHUNJHUNU,SATELLITEHUB_JHUNJHUNU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915411,9GPUWN8KZ9WJFKJ2,NaN,UNCP0000308607,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-01-28,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,110085.0,NEW DELHI,DELHI,2026-01-22,1.0,2026-01-22T12:51:47.000+05:30,2026-01-22,2026-01-22,NaN,2026-01-27T08:36:13.000+05:30,2026-01-28T10:12:53.000+05:30,2026-01-28T22:30:00.000+05:30,Attempted,NaN,2.0,Customer Not Responding,Customer Not Responding,NaN,Customer Not Responding,NaN,NaN,NaN,3000.0,0.0,8000.0,METRO,False,NaN,2026-01-27T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_SAMAYPURDEPO,2026-01-27,2026-01-22,SPS,39.0,13.0,8000.0,26.0,SATELLITEHUB_SAMAYPURDEPO,SATELLITEHUB_SAMAYPURDEPO,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-01-22,delivered,2026-01-28,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
915412,QCRWUID3QI246XZ2,NaN,UNCP0000308715,FSD_LARGE,UNC,GATE MECHANICAL,GATE MECHANICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,L,True,2026-01-26,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,560063.0,BANGALORE,KARNATAKA,2026-01-23,1.0,2026-01-23T16:20:47.000+05:30,2026-01-24,2026-01-24,NaN,2026-01-26T08:06:33.000+05:30,2026-01-26T08:06:33.000+05:30,2026-01-26T18:42:47.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,0.0,5090.0,LOCAL,False,NaN,2026-01-26T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_YEL,2026-01-26,2026-01-24,SPS,19.0,16.0,5090.0,25.0,SATELLITEHUB_YEL,SATELLITEHUB_YEL,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-01-24,delivered,2026-01-26,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
915413,HMJ0IK5033JBLQE0,NaN,UNCP0000308804,FSD_LARGE,UNC,GATE DSAI,GATE DSAI,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,RTO,RTO,PP,N,True,2026-03-19,ShipmentRtoCompleted,560062.0,Bengaluru,KARNATAKA,400027.0,MUMBAI,MAHARASHTRA,2026-01-27,2.0,2026-01-27T16:34:10.000+05:30,2026-01-28,2026-01-28,2026-02-02T22:19:59.000+05:30,2026-02-02T22:35:05.000+05:30,2026-02-02T22:35:05.000+05:30,NaN,Attempted,2026-03-11T22:27:45.000+05:30,1.0,HeavyLoad,HeavyLoad,SatelliteHub_RRD,HeavyLoad,Shipment Delayed,NaN,ManpowerIssue,3000.0,0.0,1530.0,METRO,True,NaN,2026-02-01T03:15:00+0530,Pickuphub_FKBGR2,NaN,2026-02-01,2026-01-28,SPS,20.0,4.0,1530.0,25.0,SatelliteHub_RRD,Pickuphub_MpHub_FKBGR2,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,1.0,2026-01-28,Returned_to_seller,2026-03-19,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,Returned_to_seller,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
915414,G9S1EO8V6RJUC3JD,NaN,UNCP0000309219,FSD_LARGE,UNC,BANK NOTES,BANK NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-06,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,482002.0,JABALPUR,MADHYA PRADESH,2026-01-30,4.0,2026-01-30T15:46:04.000+05:30,2026-02-02,2026-02-02,2026-02-06T06:44:08.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T17:31:36.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,4130.0,ROI,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JLR,2026-02-07,2026-02-02,SPS,19.0,13.0,4130.0,25.0,SatelliteHub_JLR,SatelliteHub_JLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-02-02,delivered,2026-02-06,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
915415,64B1EZX31KGO5GB1,NaN,UNCP0000309258,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-07,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,410506.0,PUNE,MAHARASHTRA,2026-01-30,3.0,2026-01-30T15:45:56.000+05:30,2026-02-03,2026-02-03,2026-02-07T06:55:08.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T21:40:56.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,8000.0,METRO,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_PCMC,2026-02-07,2026-02-03,SPS,39.0,13.0,8000.0,26.0,Satellitehub_PCMC,Satellitehub_PCMC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-02-03,delivered,2026-02-07,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
mg1.Final_Status.value_counts()

Final_Status
delivered             777284
Returned_to_seller     59669
Open                   40909
closed<45              30711
Open-RTO                6666
rejected_by_seller       150
Lost                      27
Name: count, dtype: int64

In [39]:
mg1['Final_Status'] = mg1['Final_Status'].replace({'closed<45': 'delivered'})
mg1.Final_Status.value_counts()

Final_Status
delivered             807995
Returned_to_seller     59669
Open                   40909
Open-RTO                6666
rejected_by_seller       150
Lost                      27
Name: count, dtype: int64

In [40]:
os.chdir(r"C:\Users\mohammadali1.vc\Desktop\Python data\Large Check File")
v1=pd.read_excel("Rev 16May.xlsx")

In [41]:
drf=mg1.merge(v1,left_on='merchant_code',right_on='Customer Code',how='left')
p1=drf['shipment_value_1'].isnull().sum()
print(p1)

752234

In [42]:
drf['shipment_value_1']=drf['shipment_value_1'].fillna(630)
drf['shipment_value_1'].isnull().sum()

np.int64(0)

In [43]:
drf

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor,ERP_Status,Final_Status,Unnamed: 0,Timestamp,AWB_TID_number,Issue_Category,Status,Reason,PH_or_DH,Seller_type,Payment_Mode,Customer Code,shipment_value_1
0,TFC001511752,NaN,AMAP0000000097,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-05-06,ShipmentUndeliveredAttempted,110086.0,Delhi,DELHI,682030.0,ERNAKULAM,KERALA,2026-04-28,1.0,2026-04-28T08:19:20.000+05:30,2026-04-28,2026-04-28,2026-05-04T06:24:00.000+05:30,2026-05-05T11:23:57.000+05:30,2026-05-05T11:23:57.000+05:30,NaN,Attempted,NaN,1.0,RequestForReschedule,RequestForReschedule,NaN,RequestForReschedule,NaN,NaN,NaN,6738.3,0.0,19000.0,ROI,False,NaN,2026-05-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_KOC,2026-05-05,2026-04-28,SPS,130.0,30.0,19000.0,30.0,SATELLITEHUB_KOC,SATELLITEHUB_KOC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,4.0,2026-04-28,Open,2026-05-06,8.0,AMAP0000000097,NORMAL_FORWARD,REGULAR,NaN,PP,6738.3,682030.0,Undelivered_Request_For_Reschedule,SATELLITEHUB_KOC,SATELLITEHUB_KOC,2026-05-05,CENTRALHUB_RPBAGHFM,28-04-2026 21:03,NaN,DELIVERY_DATE_CHANGED: 06-May-2026,1.0,NaN,NaN,06-05-2026 23:59,05-05-2026 03:15,NaN,NaN,SATELLITEHUB_KOC,04-05-2026 06:17,TFC001511752,NaN,NaN,NaN,NaN,Open,Open,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0
1,885596,NaN,ARLP0000001325,FSD_LARGE,ARL,SINGER COOKMATE 5L,885596,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-13,ShipmentDelivered,401107.0,thane,MAHARASHTRA,282001.0,AGRA,UTTAR PRADESH,2026-02-07,2.0,2026-02-07T22:34:58.000+05:30,2026-02-09,NaT,2026-02-13T02:01:56.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T20:06:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-15T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_AGR1,2026-02-15,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_AGR1,SATELLITEHUB_AGR1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0
2,885835,NaN,ARLP0000001328,FSD_LARGE,ARL,SINGER COOKMATE 5L,885835,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-19,ShipmentDelivered,401107.0,thane,MAHARASHTRA,147105.0,PATIALA,PUNJAB,2026-02-07,5.0,2026-02-07T22:34:58.000+05:30,2026-02-12,NaT,2026-02-18T10:09:16.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T17:43:18.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_Sangrur,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_Sangrur,SATELLITEHUB_Sangrur,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0
3,907611,NaN,ARLP0000001553,FSD_LARGE,ARL,SINGER COOKMATE 5L,907611,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-24,ShipmentDelivered,401107.0,thane,MAHARASHTRA,323601.0,KESHORAIPATAN,RAJASTHAN,2026-02-07,5.0,2026-02-07T22:34:52.000+05:30,2026-02-12,NaT,2026-02-19T06:09:01.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T18:56:35.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T00:00:00+0530,Pickuphub_FKMIB,SATELLITEHUB_KOTA,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_KOTA,SATELLITEHUB_KOTA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0
4,882107,NaN,ARLP0000001631,FSD_LARGE,ARL,SINGER LEO 3L WH,882107,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-16,ShipmentDelivered,401107.0,thane,MAHARASHTRA,333042.0,JHUJHUNU,RAJASTHAN,2026-02-07,2.0,2026-02-07T22:34:55.000+05:30,2026-02-09,NaT,2026-02-12T20:00:37.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T20:33:40.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,4640.0,0.0,3400.0,ROI,False,NaN,2026-02-18T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_JHUNJHUNU,2026-02-18,NaN,SPS,41.0,23.0,3400.0,26.0,SATELLITEHUB_JHUNJHUNU,SATELLITEHUB_JHUNJHUNU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915411,9GPUWN8KZ9WJFKJ2,NaN,UNCP0000308607,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-01-28,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,110085.0,NEW DELHI,DELHI,2026-01-22,1.0,2026-01-22T12:51:47.000+05:30,2026-01-22,2026-01-22,NaN,2026-01-27T08:36:13.000+05:30,2026-01-28T10:12:53.000+05:30,2026-01-28T22:30:00.000+05:30,Attempted,NaN,2.0,Customer Not Responding,Customer Not Responding,NaN,Customer Not Responding,NaN,NaN,NaN,3000.0,0.0,8000.0,METRO,False,NaN,2026-01-27T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_SAMAYPURDEPO,2026-01-27,2026-01-22,SPS,39.0,13.0,8000.0,26.0,SATELLITEHUB_SAMAYPURDEPO,SATELLITEHUB_SAMAYPURDEPO,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-01-22,delivered,2026-01-28,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0
915412,QCRWUID3QI246XZ2,NaN,UNCP0000308715,FSD_LARGE,UNC,GATE MECHANICAL,GATE MECHANICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,L,True,2026-01-26,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,560063.0,BANGALORE,KARNATAKA,2026-01-23,1.0,2026-01-23T16:20:47.000+05:30,2026-01-24,2026-01-24,NaN,2026-01-26T08:06:33.000+05:30,2026-01-26T08:06:33.000+05:30,2026-01-26T18:42:47.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,0.0,5090.0,LOCAL,False,NaN,2026-01-26T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_YEL,2026-01-26,2026-01-24,SPS,19.0,16.0,5090.0,25.0,SATELLITEHUB_YEL,SATELLITEHUB_YEL,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-01-24,delivered,2026-01-26,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0
915413,HMJ0IK5033JBLQE0,NaN,UNCP0000308804,FSD_LARGE,UNC,GATE DSAI,GATE DSAI,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,RTO,RTO,PP,N,True,2026-03-19,ShipmentRtoCompleted,560062.0,Bengaluru,KARNATAKA,400027.0,MUMBAI,MAHARASHTRA,2026-01-27,2.0,2026-01-27T16:34:10.000+05:30,2026-01-28,2026-01-28,2026-02-02T22:19:59.000+05:30,2026-02-02T22:35:05.000+05:30,2026-02-02T22:35:05.000+05:30,NaN,Attempted,2026-03-11T22:27:45.000+05:30,1.0,HeavyLoad,HeavyLoad,SatelliteHub_RRD,HeavyLoad,Shipment Delayed,NaN,ManpowerIssue,3000.0,0.0,1530.0,METRO,True,NaN,2026-02-01T03:15:00+0530,Pickuphub_FKBGR2,NaN,2026-02-01,2026-01-28,SPS,20.0,4.0,1530.0,25.0,SatelliteHub_RRD,Pickuphub_MpHub_FKBGR2,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,1.0,2026-01-28,Returned_to_seller,2026-03-19,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,Returned_to_seller,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0
915414,G9S1EO8V6RJUC3JD,NaN,UNCP0000309219,FSD_LARGE,UNC,BANK NOTES,BANK NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-06,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,482002.0,JABALPUR,MADHYA PRADESH,2026-01-30,4.0,2026-01-30T15:46:04.000+05:30,2026-02-02,2026-02-02,2026-02-06T06:44:08.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T17:31:36.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,4130.0,ROI,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JLR,2026-02-07,2026-02-02,SPS,19.0,13.0,4130.0,25.0,SatelliteHub_JLR,SatelliteHub_JLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-02-02,delivered,2026-02-06,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0
915415,64B1EZX31KGO5GB1,NaN,UNCP0000309258,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-07,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,410506.0,PUNE,MAHARASHTRA,2026-01-30,3.0,2026-01-30T15:45:56.000+05:30,2026-02-03,2026-02-03,2026-02-07T06:55:08.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T21:40:56.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,8000.0,METRO,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_PCMC,2026-02-07,2026-02-03,SPS,39.0,13.0,8000.0,26.0,Satellitehub_PCMC,Satellitehub_PCMC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-02-03,delivered,2026-02-07,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630.0

In [44]:
#drf=mg1.copy()

In [45]:
from datetime import datetime
drf['dispatch_date'] = pd.to_datetime(drf['dispatch_date']).dt.date

#drf['dispatch_date'] = drf['dispatch_date'].apply(lambda x: pd.to_datetime(x, format="%Y-%m-%d %H:%M:%S").date() if len(str(x)) > 10 else pd.to_datetime(x, format="%Y-%m-%d").date() if isinstance(x, str) else pd.NaT)
drf['todays_date']=datetime.today().strftime('%Y-%m-%d')
#drf['todays_date']="2023-11-17"

ageing_days=(pd.to_datetime(drf['todays_date']) - pd.to_datetime(drf['dispatch_date'])).dt.days
drf["ageing_1"]=ageing_days

In [46]:
def calculate_ageing_days(ageing):
    
    if ageing <= 45:
        return '<=45'
    elif ageing > 45:
        return '>45'
    else:
        return '0'

drf['Ageing_bucket'] = drf['ageing_1'].apply(calculate_ageing_days)

drf.Ageing_bucket.value_counts()

Ageing_bucket
>45     543348
<=45    370677
0         1391
Name: count, dtype: int64

In [47]:
drf=drf.drop(drf[drf['tracking_id']=="END_OF_FILE"].index)
drf.Ageing_bucket.value_counts()

Ageing_bucket
>45     543348
<=45    370677
0         1391
Name: count, dtype: int64

In [48]:
#drf['loss'] = np.where(
#    drf['Status'].isin(['dispute accepted', 'partial dispute accepted', 'open']),
#    'conditional_Loss',
#    np.where(
#        (drf['Final_Status'] == 'Returned_to_seller') & (drf['ageing'].between(45,60)),
#        'RTS>45_60',
#         np.where((drf['Final_Status']=='Returned_to_seller') & (drf['ageing']>60),'RTS>60',
#            np.where(
#                drf['Final_Status'].isin(['Lost']),
#                'Lost',
#                np.where(
#                    drf['Final_Status'] == 'Open',
#                   'Open',
#                    np.where(
#                        drf['Final_Status'] == 'Rejected_By_Seller',
#                        'Rejected_By_Seller',
#                        np.where(
#                            (drf['Ageing_bucket'] == '<=45') & (drf['Final_Status'] == 'Open-RTO'),
#                            '<=45_Open-RTO',
#                            np.where(
#                                (drf['Ageing_bucket'] == '>45') & (drf['Final_Status'] == 'Open-RTO'),
#                                '>45_open_RTO',
#                                'Null'))))))))

#drf.loss.value_counts()

In [49]:
drf['loss'] = np.where(
    drf['Status'].isin(['dispute accepted', 'partial dispute accepted', 'open']),
    'conditional_Loss',
    np.where(
        (drf['Final_Status'] == 'Returned_to_seller') & (drf['ageing'].between(45,60)),
        'RTS>45_60',
         np.where((drf['Final_Status']=='Returned_to_seller') & (drf['ageing']>60),'RTS>60',
            np.where(
                drf['Final_Status'].isin(['Lost']),
                'Lost',
                np.where(
                    drf['Final_Status'] == 'Open',
                    'Open',
                    np.where(
                        drf['Final_Status'] == 'Rejected_By_Seller',
                        'Rejected_By_Seller',
                        np.where(
                            (drf['ageing_1']<=45) & (drf['Final_Status'] == 'Open-RTO'),
                            '<=45_Open-RTO',
                            np.where(
                                (drf['ageing_1'].between(46,60)) & (drf['Final_Status'] == 'Open-RTO'),
                                '>45_60-open_RTO',
                            np.where((drf['ageing_1']>60) & (drf['Final_Status'] == 'Open-RTO'),'>60-open_RTO'
                                ,'Null')))))))))

drf.loss.value_counts()

loss
Null                867327
Open                 40909
<=45_Open-RTO         5794
>60-open_RTO           606
>45_60-open_RTO        263
conditional_Loss       260
RTS>45_60              195
RTS>60                  35
Lost                    27
Name: count, dtype: int64

In [50]:
drf['logistics_breach_bucket'] = np.where((drf['shipment_value'] > 5000),5000, drf.shipment_value)

In [51]:
conditions = {
    'COM': 2000,
    'CUH': 3000,
    'SOL': 7500,
    'SWE': 10000,
    'TEL': 3000
}
series = drf['merchant_code'].map(conditions).fillna(5000)
drf['logistics_breach_bucket'] = np.minimum(drf['shipment_value'], series)

In [52]:
q1=drf.pivot_table(index='loss',columns='dispatch_month',values='tracking_id',aggfunc='count')
q1.loc['Total'] = q1.sum()
q10=q1.drop(index='Null')
q10

dispatch_month        1.0       2.0       3.0       4.0      5.0   11.0
loss
<=45_Open-RTO          NaN       NaN     286.0    5366.0    142.0   NaN
>45_60-open_RTO        NaN       NaN     263.0       NaN      NaN   NaN
>60-open_RTO         240.0     280.0      86.0       NaN      NaN   NaN
Lost                   NaN       2.0       NaN      25.0      NaN   NaN
Open                 120.0     196.0     374.0   13890.0  26324.0   NaN
RTS>45_60             62.0      79.0      54.0       NaN      NaN   NaN
RTS>60                21.0      13.0       1.0       NaN      NaN   NaN
conditional_Loss     117.0     143.0       NaN       NaN      NaN   NaN
Total             187436.0  202867.0  234833.0  258821.0  30067.0   1.0

In [53]:
q2=drf.pivot_table(index='loss',columns='dispatch_month',values='logistics_breach_bucket',aggfunc='sum')
q20=q2.drop(index='Null')
q20

dispatch_month,1.0,2.0,3.0,4.0,5.0,11.0
loss,,,,,,
<=45_Open-RTO,NaN,NaN,914657.33,1.672922e+07,3.993449e+05,NaN
>45_60-open_RTO,NaN,NaN,870111.99,NaN,NaN,NaN
>60-open_RTO,849162.29,975637.64,308019.10,NaN,NaN,NaN
Lost,NaN,15000.00,NaN,1.250000e+05,NaN,NaN
Open,412885.07,738751.73,1230747.71,5.227416e+07,9.498485e+07,NaN
RTS>45_60,246081.37,289368.43,185094.63,NaN,NaN,NaN
RTS>60,81585.60,42521.33,4580.00,NaN,NaN,NaN
conditional_Loss,512878.92,386131.57,NaN,NaN,NaN,NaN

In [54]:
drf['shipment_value_1']=drf['shipment_value_1'].astype(int)

In [55]:
q9=drf.pivot_table(columns=['dispatch_month'],values='shipment_value_1',aggfunc='sum')
q9=q9.rename(index={"shipment_value_1" : "Total"})
q9

dispatch_month       1.0        2.0        3.0        4.0       5.0   11.0
Total           107632259  117850451  141878325  154146656  17805217   630

In [56]:
g5=pd.concat([q20,q9])

In [57]:
j1=pd.concat([q10,g5],axis=1)
j1

dispatch_month,1.0,2.0,3.0,4.0,5.0,11.0,1.0,2.0,3.0,4.0,5.0,11.0
<=45_Open-RTO,NaN,NaN,286.0,5366.0,142.0,NaN,NaN,NaN,9.146573e+05,1.672922e+07,3.993449e+05,NaN
>45_60-open_RTO,NaN,NaN,263.0,NaN,NaN,NaN,NaN,NaN,8.701120e+05,NaN,NaN,NaN
>60-open_RTO,240.0,280.0,86.0,NaN,NaN,NaN,8.491623e+05,9.756376e+05,3.080191e+05,NaN,NaN,NaN
Lost,NaN,2.0,NaN,25.0,NaN,NaN,NaN,1.500000e+04,NaN,1.250000e+05,NaN,NaN
Open,120.0,196.0,374.0,13890.0,26324.0,NaN,4.128851e+05,7.387517e+05,1.230748e+06,5.227416e+07,9.498485e+07,NaN
RTS>45_60,62.0,79.0,54.0,NaN,NaN,NaN,2.460814e+05,2.893684e+05,1.850946e+05,NaN,NaN,NaN
RTS>60,21.0,13.0,1.0,NaN,NaN,NaN,8.158560e+04,4.252133e+04,4.580000e+03,NaN,NaN,NaN
conditional_Loss,117.0,143.0,NaN,NaN,NaN,NaN,5.128789e+05,3.861316e+05,NaN,NaN,NaN,NaN
Total,187436.0,202867.0,234833.0,258821.0,30067.0,1.0,1.076323e+08,1.178505e+08,1.418783e+08,1.541467e+08,1.780522e+07,630.0

In [58]:
g1=drf[~drf['loss'].isin(['Null'])]
h1=g1.pivot_table(columns=['dispatch_month'],values='tracking_id',aggfunc='count',fill_value=0)
h1=h1.rename(index={"tracking_id" : "Total Loss"})
h1

dispatch_month  1.0  2.0   3.0    4.0    5.0
Total Loss      560  713  1064  19281  26466

In [59]:
h2=g1.pivot_table(columns=['dispatch_month'],values='logistics_breach_bucket',aggfunc='sum',fill_value=0)
h2=h2.rename(index={"logistics_breach_bucket" : "Total Loss"})

In [60]:
h10=pd.concat([h1,h2],axis=1)
h10

dispatch_month,1.0,2.0,3.0,4.0,5.0,1.0,2.0,3.0,4.0,5.0
Total Loss,560,713,1064,19281,26466,2102593.25,2447410.7,3513210.76,6.912839e+07,9.538419e+07

In [61]:
j1=j1.drop(columns={11})
j1

dispatch_month,1.0,2.0,3.0,4.0,5.0,1.0,2.0,3.0,4.0,5.0
<=45_Open-RTO,NaN,NaN,286.0,5366.0,142.0,NaN,NaN,9.146573e+05,1.672922e+07,3.993449e+05
>45_60-open_RTO,NaN,NaN,263.0,NaN,NaN,NaN,NaN,8.701120e+05,NaN,NaN
>60-open_RTO,240.0,280.0,86.0,NaN,NaN,8.491623e+05,9.756376e+05,3.080191e+05,NaN,NaN
Lost,NaN,2.0,NaN,25.0,NaN,NaN,1.500000e+04,NaN,1.250000e+05,NaN
Open,120.0,196.0,374.0,13890.0,26324.0,4.128851e+05,7.387517e+05,1.230748e+06,5.227416e+07,9.498485e+07
RTS>45_60,62.0,79.0,54.0,NaN,NaN,2.460814e+05,2.893684e+05,1.850946e+05,NaN,NaN
RTS>60,21.0,13.0,1.0,NaN,NaN,8.158560e+04,4.252133e+04,4.580000e+03,NaN,NaN
conditional_Loss,117.0,143.0,NaN,NaN,NaN,5.128789e+05,3.861316e+05,NaN,NaN,NaN
Total,187436.0,202867.0,234833.0,258821.0,30067.0,1.076323e+08,1.178505e+08,1.418783e+08,1.541467e+08,1.780522e+07

In [62]:
s1=pd.concat([j1,h10])
s1=s1.fillna(0)
s1

dispatch_month,1.0,2.0,3.0,4.0,5.0,1.0,2.0,3.0,4.0,5.0
<=45_Open-RTO,0.0,0.0,286.0,5366.0,142.0,0.000000e+00,0.000000e+00,9.146573e+05,1.672922e+07,3.993449e+05
>45_60-open_RTO,0.0,0.0,263.0,0.0,0.0,0.000000e+00,0.000000e+00,8.701120e+05,0.000000e+00,0.000000e+00
>60-open_RTO,240.0,280.0,86.0,0.0,0.0,8.491623e+05,9.756376e+05,3.080191e+05,0.000000e+00,0.000000e+00
Lost,0.0,2.0,0.0,25.0,0.0,0.000000e+00,1.500000e+04,0.000000e+00,1.250000e+05,0.000000e+00
Open,120.0,196.0,374.0,13890.0,26324.0,4.128851e+05,7.387517e+05,1.230748e+06,5.227416e+07,9.498485e+07
RTS>45_60,62.0,79.0,54.0,0.0,0.0,2.460814e+05,2.893684e+05,1.850946e+05,0.000000e+00,0.000000e+00
RTS>60,21.0,13.0,1.0,0.0,0.0,8.158560e+04,4.252133e+04,4.580000e+03,0.000000e+00,0.000000e+00
conditional_Loss,117.0,143.0,0.0,0.0,0.0,5.128789e+05,3.861316e+05,0.000000e+00,0.000000e+00,0.000000e+00
Total,187436.0,202867.0,234833.0,258821.0,30067.0,1.076323e+08,1.178505e+08,1.418783e+08,1.541467e+08,1.780522e+07
Total Loss,560.0,713.0,1064.0,19281.0,26466.0,2.102593e+06,2.447411e+06,3.513211e+06,6.912839e+07,9.538419e+07

In [63]:
j1 = j1[~j1.index.duplicated(keep='first')]
h10 = h10[~h10.index.duplicated(keep='first')]

s1 = pd.concat([j1, h10])

In [64]:
percentage_undelivereds = (h10 / j1.loc["Total"]) * 100
percentage_undelivereds =percentage_undelivereds.rename(index={"percentage_undelivereds" : "Lost shipment"})
percentage_undelivereds = percentage_undelivereds.map(lambda x: f"{x:.2f}%")
percentage_undelivereds

dispatch_month,1.0,2.0,3.0,4.0,5.0,1.0,2.0,3.0,4.0,5.0
Total Loss,0.30%,0.35%,0.45%,7.45%,88.02%,1.95%,2.08%,2.48%,44.85%,535.71%

In [65]:
s8=pd.concat([s1,percentage_undelivereds])
s8

dispatch_month,1.0,2.0,3.0,4.0,5.0,1.0,2.0,3.0,4.0,5.0
<=45_Open-RTO,NaN,NaN,286.0,5366.0,142.0,NaN,NaN,914657.33,16729222.8014,399344.86
>45_60-open_RTO,NaN,NaN,263.0,NaN,NaN,NaN,NaN,870111.99,NaN,NaN
>60-open_RTO,240.0,280.0,86.0,NaN,NaN,849162.29,975637.64,308019.1,NaN,NaN
Lost,NaN,2.0,NaN,25.0,NaN,NaN,15000.0,NaN,125000.0,NaN
Open,120.0,196.0,374.0,13890.0,26324.0,412885.07,738751.73,1230747.71,52274164.8406,94984845.8176
RTS>45_60,62.0,79.0,54.0,NaN,NaN,246081.37,289368.43,185094.63,NaN,NaN
RTS>60,21.0,13.0,1.0,NaN,NaN,81585.6,42521.33,4580.0,NaN,NaN
conditional_Loss,117.0,143.0,NaN,NaN,NaN,512878.92,386131.57,NaN,NaN,NaN
Total,187436.0,202867.0,234833.0,258821.0,30067.0,107632259.0,117850451.0,141878325.0,154146656.0,17805217.0
Total Loss,560.0,713.0,1064.0,19281.0,26466.0,2102593.25,2447410.7,3513210.76,69128387.642,95384190.6776
Total Loss,0.30%,0.35%,0.45%,7.45%,88.02%,1.95%,2.08%,2.48%,44.85%,535.71%

In [66]:
ageing_1=(pd.to_datetime(drf['todays_date']) - pd.to_datetime(drf['Latest_Update_Time'])).dt.days
drf["last_scan_ageing"]=ageing_1
drf['last_scan_ageing']=drf['last_scan_ageing'].fillna(-1)
def last_scan_ageing_bucket(last_scan_ageing):
    
    if last_scan_ageing < 0:
        return "ageing 0"
    elif last_scan_ageing >= 0 and last_scan_ageing <=2:
        return "ageing 0-2"
    elif last_scan_ageing >=3 and last_scan_ageing <=5:
        return "ageing 3-5"
    elif last_scan_ageing >=6 and last_scan_ageing <=10:
        return "ageing 6-10"
    elif last_scan_ageing >=11 and last_scan_ageing <=20:
        return "ageing 11-20"
    else:
        return "ageing >20"

drf['last_scan_ageing_bucket'] = drf['last_scan_ageing'].apply(last_scan_ageing_bucket)
t1=drf[drf['Final_Status'].isin(['Open','Open-RTO']) & ~drf['last_scan_ageing'].isin([-1,0,1,2])]
t1.to_csv("Eagleye_out_1.csv",index=False)
t1

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor,ERP_Status,Final_Status,Unnamed: 0,Timestamp,AWB_TID_number,Issue_Category,Status,Reason,PH_or_DH,Seller_type,Payment_Mode,Customer Code,shipment_value_1,todays_date,ageing_1,Ageing_bucket,loss,logistics_breach_bucket,last_scan_ageing,last_scan_ageing_bucket
16,ORD-SO-683545,AWPN0001088477,AWPC0001088473,FSD_LARGE,AWP,ATUL SALIX 500G,SO-683545,ext_mps,AWP,AWP : Naveen Kumar,AWP_07244bb3805e9199e4db17a298d96c62,Forward,SHIPMENT,COD,Z,True,2026-05-03,PrimaryInscan,132001.0,Karnal,HARYANA,261501.0,SITAPUR,UTTAR PRADESH,2026-04-29,1.0,2026-04-29,2026-04-30,2026-04-30,2026-05-03T20:49:52.000+05:30,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17860.00,15860.0,11580.0,ZONAL,False,AWPN0001088477,2026-05-06T22:44:04+0530,PickupHub_KNL1,SATELLITEHUB_SITAPUR,2026-05-06,2026-04-30,MPS,45.0,33.0,11580.0,26.0,NaN,SATELLITEHUB_SITAPUR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2026-04-30,Open,2026-05-06,3.0,AWPC0001088473,NORMAL_FORWARD,REGULAR,NaN,COD,17860.00,261501.0,Undelivered_Not_Attended,SATELLITEHUB_SITAPUR,SATELLITEHUB_SITAPUR,2026-05-03,CentralHub_KNL1,30-04-2026 17:18,NaN,NaN,0.0,NaN,NaN,06-05-2026 23:59,06-05-2026 22:44,NaN,NaN,SATELLITEHUB_SITAPUR,03-05-2026 20:42,ORD-SO-683545,NaN,NaN,NaN,NaN,Open,Open,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,7.0,<=45,Open,5000.00,3.0,ageing 3-5
124,EXPRESS647,ESAN0000045207,ESAP0000045205,FSD_LARGE,ESA,Others,FREGILE ITEM,ext_mps,ESA,ESA : PRADEEP ODISHA,ESA_a0d3ed2da04cf2d206d7aa76f16a6d9e,RTO,RTO,PP,N,True,2026-05-01,ReturnInScanAtHub,751024.0,Bhubaneshwar,ODISHA,226016.0,LUCKNOW,UTTAR PRADESH,2026-04-06,2.0,2026-04-06,2026-04-07,2026-04-07,2026-04-14T02:15:57.000+05:30,2026-04-14T08:39:53.000+05:30,2026-04-14T08:39:53.000+05:30,NaN,Attempted,NaN,1.0,OrderRejectedByCustomer,OrderRejectedByCustomer,NaN,OrderRejectedByCustomer,Rejected_by_Customer,ShipmentUndeliveredAttempted,ShipmentNotReady,30000.00,0.0,2000.0,ROI,False,ESAN0000045207,2026-04-17T04:06:21+0530,Pickuphub_MNHR,Pickuphub_MPhub_MNHR,2026-04-17,2026-04-07,MPS,10.0,10.0,2000.0,10.0,SATELLITEHUB_LKOGOMTI,Pickuphub_MPhub_MNHR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,4.0,2026-04-07,Open-RTO,2026-05-06,24.0,ESAP0000045205,NORMAL_FORWARD,ECONOMY,NaN,PP,30000.00,751024.0,Undelivered_Not_Attended,Pickuphub_MPhub_MNHR,Pickuphub_MPhub_MNHR,2026-05-01,CentralHub_MNHR,07-04-2026 22:35,NaN,Marked_As_RTO,1.0,NaN,NaN,14-04-2026 23:59,14-04-2026 04:15,NaN,NaN,SATELLITEHUB_LKOGOMTI,01-05-2026 14:32,EXPRESS647,NaN,NaN,NaN,NaN,Open,Open-RTO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,30.0,<=45,<=45_Open-RTO,5000.00,5.0,ageing 3-5
180,15420402KUN0D341F2,NaN,FCLP0000705477,FSD_LARGE,FCL,Babyhug Plug & Play Tricycle with Parental Pus...,20604785,ext_sps,FCL,FCL : KOLKATA-2,FCL_f91531434ac4afb1290636852eec6dee,RTO,RTO,PP,Z,True,2026-05-03,InScanAtHub,712306.0,Kolkata,WEST BENGAL,791110.0,NAHARLAGUN,ARUNACHAL PRADESH,2026-04-27,1.0,2026-04-27,2026-04-28,2026-04-28,NaN,NaN,NaN,NaN,Not_Attempted,2026-05-01T15:10:38.000+05:30,0.0,NaN,NaN,CentralHub_PBI,NaN,customer_cancellation,NaN,NaN,3395.00,0.0,7290.0,ZONAL,True,NaN,2026-05-04T03:15:00+0530,PickupHub_SINGUR,CentralHub_PBI,2026-05-04,2026-04-28,SPS,60.0,35.0,7290.0,23.0,NaN,Pickuphub_MPhub_SINGUR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2026-04-28,Open-RTO,2026-05-06,5.0,FCLP0000705477,NORMAL_FORWARD,ECONOMY,NaN,PP,3395.00,712306.0,Expected,Pickuphub_MPhub_SINGUR,CentralHub_L_KOL5,2026-05-03,CentralHub_SINGUR,28-04-2026 19:03,NaN,Marked_As_RTO,0.0,NaN,NaN,04-05-2026 23:59,04-05-2026 03:15,NaN,NaN,SatelliteHub_FKNHL,03-05-2026 01:54,15420402KUN0D341F2,NaN,NaN,NaN,NaN,Open,Open-RTO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,9.0,<=45,<=45_Open-RTO,3395.00,3.0,ageing 3-5
200,38435974RLB0A7B70E,NaN,FCLP0001128752,FSD_LARGE,FCL,Babyhug High Desiy Sof Foam Baby Maess Cue Aim...,14585543,ext_sps,FCL,FCL : PNQ,FCL_676559418aa2eebc76105727caeb971c,RTO,RTO,PP,Z,True,2026-03-18,InScanAtHub,410501.0,PUNE,MAHARASHTRA,431401.0,W26,MAHARASHTRA,2026-03-09,1.0,2026-03-09,2026-03-09,2026-03-09,2026-03-17T09:50:01.000+05:30,NaN,NaN,NaN,Not_Attempted,2026-03-17T13:41:15.000+05:30,0.0,NaN,NaN,SatelliteHub_PRB,NaN,customer_cancellation,NaN,NaN,3599.00,0.0,2400.0,ZONAL,True,NaN,2026-03-17T03:15:00+0530,Pickuphub_PUN,Pickuphub_MPhub_PUN,2026-03-17,2026-03-09,SPS,102.0,12.0,2400.0,58.0,NaN,Pickuphub_MPhub_PUN,dispatched_to_mh,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2026-03-09,Open-RTO,2026-05-06,9.0,FCLP0001128752,NORMAL_FORWARD,ECONOMY,NaN,PP,3599.00,410501.0,Out_For_Delivery,Pickuphub_MPhub_PUN,Pickuphub_MPhub_PUN,2026-03-18,CentralHub_PUN,09-03-2026 19:58,Updated from FM,Marked_As_RTO,1.0,NaN,NaN,17-03-2026 23:59,17-03-2026 03:15,NaN,NaN,SatelliteHub_PRB,18-03-2026 11:56,38435974RLB0A7B70E,NaN,NaN,NaN,NaN,Open,Open-RTO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,58.0,>45,>45_60-open_RTO,3599.00,49.0,ageing >20
254,3I93598826,NaN,HBLP0000298890,FSD_LARGE,HBL,NUTRITION,NUTRITION,ext_sps,HBL,HBL : HBL - CG,HBL_30910fa76c5a98f66ef1b4fa47b3858c,Forward,SHIPMENT,PP,Z,True,2026-05-02,InscannedAtDH,493111.0,RAIPUR,CHHATTISGARH,495115.0,LORMI,CHHATTISGARH,2026-04-30,1.0,2026-04-30,2026-04-30,2026-04-30,2026-05-02T05:26:53.000+05:30,NaN,NaN,NaN,Not_Attempted,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8518.12,0.0,10.0,ZONAL,False,NaN,2026-05-06T04:15:00+0530,PickupHub_FKRPR,Satellitehub_BIL1,2026-05-06,2026-04-30,SPS,33.0,22.0,10.0,22.0,NaN,Satellitehub_BIL1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2026-04-30,Open,2026-05-06,2.0,HBLP0000298890,NORMAL_FORWARD,REGULAR,NaN,PP,8518.12,495115.0,Undelivered_Not_Attended,Satellitehub_BIL1,Satellitehub_BIL1,2026-05-02,Centralhub_FKRPR,01-05-2026 05:11,NaN,NaN,0.0,NaN,NaN,06-05-2026 23:59,06-05-2026 04:15,NaN,NaN,Satellitehub_BIL1,02-05-2026 05:21,3I93598826,NaN,NaN,NaN,NaN,Open,Open,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,6.0,<=45,Open,5000.00,4.0,ageing 3-5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
904030,146665004,NaN,NAHC0000610887,FSD_LARGE,NAH,5 l 3 l 2 l 1.5 l Pessue Cooke Combo 4PC4,12616649,ext_sps,NAH,NAH : Blessings Unlimited Bangalore,NAH_fa283119375bbf0fc1e1f2edfef1b387,Forward,SHIPMENT,COD,N,True,2026-02-12,ShipmentUndeliveredAttempted,560091.0,BANGALORE,KARNATAKA,431105.0,AURANGABAD,MAHARASHTRA,2026-01-26,1.0,2026-01-26,2026-01-26,2026-01-26,NaN,2026-01-31T09:56:49.000+05:30,2026-02-12T10:42:47.000+05:30,NaN,Attempted,NaN,7.0,Customer Not Responding,Customer Not Responding,NaN,Customer Not Responding,NaN,NaN,NaN,2398.00,2398.0,4000.0,ROI,False,NaN,2026-02-02T03:15:00+0530,PickupHub_FKYWP,Satellitehub_WLJ,2026-02-02,2026-01-26,SPS,10.0,10.0,4000.0,10.0,Satellitehub_WLJ,Satellitehub_WLJ,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,1.0,2026-01-26,Open,2026-05-06,17.0,NAHC0000610887,NORMAL_FORWARD,REGULAR,NaN,COD,2398.00,431105.0,Undelivered_HeavyLoad,Satellitehub_WLJ,Satellitehub_WLJ,2026-05-01,CENTRALHUB_FKYWP,26-01-2026 19:15,Updated by CRON,DELIVERY_DATE_CHANGED: 13-Feb-2026,8.0,NaN,NaN,13-02-2026 23:59,02-02-2026 03:15,NaN,NaN,Satellitehub_WLJ,31-01-2026 07:36,146665004,NaN,NaN,NaN,NaN,Open,Open,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAH,116,2026-05-06,100.0,>45,Open,2398.00,5.0,ageing 3-5
904183,146292979,NaN,NAHC0000613678,FSD_LARGE,NAH,5 ltr 3 ltr 2 ltr 1.5 ltr Pressure Cooker C...,12616649,ext_sps,NAH,NAH : Blessings Unlimited Bangalore,NAH_fa283119375bbf0fc1e1f2edfef1b387,Forward,SHIPMENT,COD,Z,True,2026-03-30,ShipmentOutForDelivery,560091.0,BANGALORE,KARNATAKA,630610.0,MANAMADURAI,TAMIL NADU,2026-01-18,1.0,2026-01-18,2026-01-18,2026-01-18,NaN,2026-01-26T09:45:26.000+05:30,2026-03-30T07:26:19.000+05:30,NaN,Attempted,NaN,23.0,RequestForReschedule,Customer Not Responding,NaN,RequestForReschedule,NaN,NaN,NaN,2398.00,2398.0,4000.0,ZONAL,False,NaN,2026-01-25T03:15:00+0530,PickupHub_FKYWP,Satellitehub_SVGA,2026-01-25,2026-01-18,SPS,10.0,10.0,4000.0,10.0,Satellitehub_SVGA,Satellitehub_SVGA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,1.0,2026-01-18,Open,2026-05-06,71.0,NAHC0000613678,NORMAL_FORWARD,REGULAR,NaN,COD,2398.00,630610.0,Undelivered_No_Response,Satellitehub_SVGA,Satellitehub_SVGA,2026-04-15,CENTRALHUB_FKYWP,18-01-2026 18:31,NaN,DELIVERY_DATE_CHANGED: 20-Mar-2026,24.0,NaN,NaN,20-03-2026 23:59,25-01-2026 03:15,NaN,NaN,Satellitehub_SVGA,20-01-2026 19:58,146292979,NaN,NaN,NaN,NaN,Open,Open,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAH,116,2026-05-06,108.0,>45,Open,2398.00,21.0,ageing >20
905832,NYK-325333804-2349457-1,NKDN0000026339,NKDC0000026340,FSD_LARGE,NKD,Hair & Care Damage Repair Non-Sticky Hair Oil ...,89002827,ext_mps,NKD,NKD : Nykaa eB2B Warehouse Patna,NKD_ef2707b9c90671f302cc91d92780951a,RTO,RTO,COD,Z,True,2026-01-18,InScanAtHub,804451.0,Patna,BIHAR,845438.0,Bettiah,BIHAR,2026-01-12,1.0,2026-01-12,2026-01-12,2026-01-12,NaN,2026-01-16T09:46:10.000+05:30,2026-01-16T09:46:10.000+05:30,NaN,Attempted,NaN,1.0,OrderRejectedByCustomer,OrderRejectedByCustomer,NaN,OrderRejectedByCustomer,Rejected_by_Customer,NaN,NaN,27596.04,24924.0,15000.0,ZONAL,False,NKDN0000026339,NaN,PickupHub_PAT,CentralHub_L_PAT3,NaN,2026-01-12,MPS,50.0,24.0,15000.0,28.0,Satellitehub_BET1,Pickuphub_MPhub_PAT,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,1.0,2026-01-12,Open-RTO,2026-05-06,6.0,NKDC0000026340,NORMAL_FORWARD,ECONOMY,NaN,COD,27596.04,804451.0,Undelivered_Not_Attended,Pickuphub_MPhub_PAT,CentralHub_L_PAT3,2026-01-18,CentralHub_PAT1,13-01-2026 08:23,NaN,Marked_As_RTO,1.0,NaN,NaN,16-01-2026 23:59,16-01-2026 03:15,NaN,NaN,Satellitehub_BET1,18-01-2026 20:44,NYK-325333804-2349457-1,NaN,NaN,NaN,NaN,Open,Open-RTO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,114.0,>45,>60-open_RTO,5000.00,108.0,ageing >20
906424,NYK-323909591-4666532-1,NaN,NKDC0000024967,FSD_LARGE,NKD,Fair & Handsome Brightening Cream for Men Inst...,FAIRH00000024,ext_sps,NykaaLarge,Nykaa eB2B Warehouse Patna,NKD_ef2707b9c90671f302cc91d92780951a,RTO,RTO,COD,Z,True,2026-01-06,ShipmentRtoConfirmed,804451.0,Patna,BIHAR,841237.0,Siwan,BIHAR,2026-01-03,1.0,2026-01-03,2026-01-04,2026-01-04,2026-01-06T07:43:09.000+05:30,2026-01-06T08:13:47.000+05:30,2026-01-06T08:13:47.000+05:30,NaN,Attempted,2026-01-06T19:30:09.000+05:30,1.0,OrderRejectedByCustomer,OrderRejectedByCustomer,SatelliteHub_FKSWN,OrderRejectedByCustomer,Shipment Delayed,ShipmentUndeliveredAttempted,NaN,2252.94,2103.0,3.0,ZONAL,False,NaN,2026-01-08T03:15:00+0530,PickupHub_PAT,SatelliteHub_FKSWN,2026-01-08,2026-01-04,SPS,30.0,20.0,3.0,25.0,SatelliteHub_FKSWN,SatelliteHub_FKSWN,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,False,1.0,2026-01-04,Open-RTO,2026-05-06,2.0,NKDC0000024967,NORMAL_FORWARD,ECONOMY,NaN,COD,2252.94,804451.0,Expected,Pickuphub_MPhub_PAT,CentralHub_L_PAT3,2026-01-07,CentralHub_PAT1,05-01-2026 07:28,NaN,Marked_As_RTO,1.0,NaN,NaN,08-01-2026 23:59,08-01-2026 03:15,NaN,NaN,SatelliteHub_FKSWN,06-01-2026 07:36,NYK-323909591-4666532-1,NaN,NaN,NaN,NaN,Open,Open-RTO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,123.0,>45,>60-open_RTO,2252.94,119.0,ageing >20
907776,NYK-323910907-4997781-1,NaN,NKDC0000025022,FSD_LARGE,NKD,Tresemme Keratin Smooth With Kertin & Argan Oi...,8901030655821,ext_sps,NykaaLarge,Nykaa eB2B Warehouse Patna,NKD_ef2707b9c90671f302cc91d92780951a,RTO,RTO,COD,Z,True,2026-01-31,ShipmentRtoConfirmed,804451.0,Patna,BIHAR,802219.0,Rohtas,BIHAR,2026-01-04,1.0,2026-01-04,2026-01-04,2026-01-04,2026-01-23T03:55:39.000+05:30,NaN,NaN,NaN,Not_Attempted,2026-01-31T05:56:04.000+05:30,0.0,NaN,NaN,Motherhub_DIC,NaN,NaN,NaN,NaN,2639.06,2628.0,3.0,ZONAL,False,NaN,2026-01-14T03:15:00+0530,PickupHub_PAT,Motherhub_DIC,2026-01-14,2026-01-04,SPS,30.0,20.0,3.0,25.0,NaN,SatelliteHub_FKSSM,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2026-01-04,Open-RTO,2026-05-06,27.0,NKDC0000025022,NORMAL_FORWARD,ECONOMY,NaN,COD,2639.06,804451.0,Undelivered_Not_Attended,Pickuphub_MPhub_PAT,CentralHub_L_PAT3,2026-04-20,CentralHub_PAT1,05-01-2026 07:29,NaN,Marked_As_RTO,0.0,EMPPAT-103004,REACHED,14-01-2026 23:59,14-01-2026 03:15,NaN,NaN,SatelliteHub_FKSSM,20-04-2026 13:17,NYK-323910907-4997781-1,NaN,NaN,NaN,NaN,Open,Open-RTO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,122.0,>45,>60-open_RTO,2639.06,16.0,ageing 11-20

In [67]:
t2=pd.read_csv("69fab686044bddb2f019c161.csv")
t2

,Facility,Department,Casper ID,Date,Time,Shipment/Bag ID,Seal ID,PTC Code,Device #
0,CentralHub_L_YKBX1,MH-INBOUND,4003746,03-05-2026,05:13 PM,EMLC0002119173,NaN,NaN,UNKNOWN
1,CentralHub_L_LKO3,OUTBOUND,ca.3495531,26-04-2026,01:15 AM,INWP0000123775,NaN,NaN,PC1PKKA9
2,CentralHub_L_MUMX,MH-OUTBOUND,2766287,10-03-2026,02:16 AM,FLOR0000029672,NaN,NaN,UNKNOWN
3,CentralHub_L_YKBX1,MH-INBOUND,4019089,02-05-2026,11:05 AM,AWPC0000089804,NaN,NaN,UNKNOWN
4,CentralHub_L_YKBX1,MH-INBOUND,4022777,02-05-2026,09:31 AM,SWLC1003015880,NaN,NaN,UNKNOWN
...,...,...,...,...,...,...,...,...,...
6583,CentralHub_MPL1,MH-OUTBOUND,3983020,25-04-2026,12:52 PM,INWR0000103535,NaN,NaN,UNKNOWN
6584,PICKUPHUB_JALANDHARFM,FM-RETURN,ankush.kumar4,25-04-2026,10:11 AM,MOHC2700075189,NaN,NaN,5S5LTD3
6585,CentralHub_L_MUMX,MH-OUTBOUND,2766287,20-04-2026,11:25 AM,NAHC0000616010,NaN,NaN,UNKNOWN
6586,Pickuphub_PUN Station1,FM-RETURN,adarshshendage.vc,09-03-2026,12:13 PM,FRIR0000015967,NaN,NaN,PC14S9WY
6587,Satellitehub_MCRFK,LM-PRC,maddaakhil.vc,05-05-2026,02:19 PM,INWP0000127993,NaN,NaN,PC0W69C8

In [68]:
drf1=drf.merge(t2[['Shipment/Bag ID','Date','Facility']],left_on='tracking_id',right_on='Shipment/Bag ID',how='left').drop_duplicates(subset='tracking_id')
drf1

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor,ERP_Status,Final_Status,Unnamed: 0,Timestamp,AWB_TID_number,Issue_Category,Status,Reason,PH_or_DH,Seller_type,Payment_Mode,Customer Code,shipment_value_1,todays_date,ageing_1,Ageing_bucket,loss,logistics_breach_bucket,last_scan_ageing,last_scan_ageing_bucket,Shipment/Bag ID,Date,Facility
0,TFC001511752,NaN,AMAP0000000097,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-05-06,ShipmentUndeliveredAttempted,110086.0,Delhi,DELHI,682030.0,ERNAKULAM,KERALA,2026-04-28,1.0,2026-04-28,2026-04-28,2026-04-28,2026-05-04T06:24:00.000+05:30,2026-05-05T11:23:57.000+05:30,2026-05-05T11:23:57.000+05:30,NaN,Attempted,NaN,1.0,RequestForReschedule,RequestForReschedule,NaN,RequestForReschedule,NaN,NaN,NaN,6738.3,0.0,19000.0,ROI,False,NaN,2026-05-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_KOC,2026-05-05,2026-04-28,SPS,130.0,30.0,19000.0,30.0,SATELLITEHUB_KOC,SATELLITEHUB_KOC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,4.0,2026-04-28,Open,2026-05-06,8.0,AMAP0000000097,NORMAL_FORWARD,REGULAR,NaN,PP,6738.3,682030.0,Undelivered_Request_For_Reschedule,SATELLITEHUB_KOC,SATELLITEHUB_KOC,2026-05-05,CENTRALHUB_RPBAGHFM,28-04-2026 21:03,NaN,DELIVERY_DATE_CHANGED: 06-May-2026,1.0,NaN,NaN,06-05-2026 23:59,05-05-2026 03:15,NaN,NaN,SATELLITEHUB_KOC,04-05-2026 06:17,TFC001511752,NaN,NaN,NaN,NaN,Open,Open,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,8.0,<=45,Open,5000.0,1.0,ageing 0-2,NaN,NaN,NaN
1,885596,NaN,ARLP0000001325,FSD_LARGE,ARL,SINGER COOKMATE 5L,885596,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-13,ShipmentDelivered,401107.0,thane,MAHARASHTRA,282001.0,AGRA,UTTAR PRADESH,2026-02-07,2.0,2026-02-07,2026-02-09,NaT,2026-02-13T02:01:56.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T20:06:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-15T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_AGR1,2026-02-15,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_AGR1,SATELLITEHUB_AGR1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,88.0,>45,Null,2834.0,-1.0,ageing 0,NaN,NaN,NaN
2,885835,NaN,ARLP0000001328,FSD_LARGE,ARL,SINGER COOKMATE 5L,885835,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-19,ShipmentDelivered,401107.0,thane,MAHARASHTRA,147105.0,PATIALA,PUNJAB,2026-02-07,5.0,2026-02-07,2026-02-12,NaT,2026-02-18T10:09:16.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T17:43:18.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_Sangrur,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_Sangrur,SATELLITEHUB_Sangrur,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,88.0,>45,Null,2834.0,-1.0,ageing 0,NaN,NaN,NaN
3,907611,NaN,ARLP0000001553,FSD_LARGE,ARL,SINGER COOKMATE 5L,907611,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-24,ShipmentDelivered,401107.0,thane,MAHARASHTRA,323601.0,KESHORAIPATAN,RAJASTHAN,2026-02-07,5.0,2026-02-07,2026-02-12,NaT,2026-02-19T06:09:01.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T18:56:35.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T00:00:00+0530,Pickuphub_FKMIB,SATELLITEHUB_KOTA,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_KOTA,SATELLITEHUB_KOTA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,88.0,>45,Null,2834.0,-1.0,ageing 0,NaN,NaN,NaN
4,882107,NaN,ARLP0000001631,FSD_LARGE,ARL,SINGER LEO 3L WH,882107,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-16,ShipmentDelivered,401107.0,thane,MAHARASHTRA,333042.0,JHUJHUNU,RAJASTHAN,2026-02-07,2.0,2026-02-07,2026-02-09,NaT,2026-02-12T20:00:37.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T20:33:40.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,4640.0,0.0,3400.0,ROI,False,NaN,2026-02-18T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_JHUNJHUNU,2026-02-18,NaN,SPS,41.0,23.0,3400.0,26.0,SATELLITEHUB_JHUNJHUNU,SATELLITEHUB_JHUNJHUNU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,88.0,>45,Null,4640.0,-1.0,ageing 0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915411,9GPUWN8KZ9WJFKJ2,NaN,UNCP0000308607,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-01-28,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,110085.0,NEW DELHI,DELHI,2026-01-22,1.0,2026-01-22,2026-01-22,2026-01-22,NaN,2026-01-27T08:36:13.000+05:30,2026-01-28T10:12:53.000+05:30,2026-01-28T22:30:00.000+05:30,Attempted,NaN,2.0,Customer Not Responding,Customer Not Responding,NaN,Customer Not Responding,NaN,NaN,NaN,3000.0,0.0,8000.0,METRO,False,NaN,2026-01-27T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_SAMAYPURDEPO,2026-01-27,2026-01-22,SPS,39.0,13.0,8000.0,26.0,SATELLITEHUB_SAMAYPURDEPO,SATELLITEHUB_SAMAYPURDEPO,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-01-22,delivered,2026-01-28,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,104.0,>45,Null,3000.0,-1.0,ageing 0,NaN,NaN,NaN
915412,QCRWUID3QI246XZ2,NaN,UNCP0000308715,FSD_LARGE,UNC,GATE MECHANICAL,GATE MECHANICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,L,True,2026-01-26,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,560063.0,BANGALORE,KARNATAKA,2026-01-23,1.0,2026-01-23,2026-01-24,2026-01-24,NaN,2026-01-26T08:06:33.000+05:30,2026-01-26T08:06:33.000+05:30,2026-01-26T18:42:47.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,0.0,5090.0,LOCAL,False,NaN,2026-01-26T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_YEL,2026-01-26,2026-01-24,SPS,19.0,16.0,5090.0,25.0,SATELLITEHUB_YEL,SATELLITEHUB_YEL,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-01-24,delivered,2026-01-26,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,103.0,>45,Null,3000.0,-1.0,ageing 0,NaN,NaN,NaN
915413,HMJ0IK5033JBLQE0,NaN,UNCP0000308804,FSD_LARGE,UNC,GATE DSAI,GATE DSAI,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,RTO,RTO,PP,N,True,2026-03-19,ShipmentRtoCompleted,560062.0,Bengaluru,KARNATAKA,400027.0,MUMBAI,MAHARASHTRA,2026-01-27,2.0,2026-01-27,2026-01-28,2026-01-28,2026-02-02T22:19:59.000+05:30,2026-02-02T22:35:05.000+05:30,2026-02-02T22:35:05.000+05:30,NaN,Attempted,2026-03-11T22:27:45.000+05:30,1.0,HeavyLoad,HeavyLoad,SatelliteHub_RRD,HeavyLoad,Shipment Delayed,NaN,ManpowerIssue,3000.0,0.0,1530.0,METRO,True,NaN,2026-02-01T03:15:00+0530,Pickuphub_FKBGR2,NaN,2026-02-01,2026-01-28,SPS,20.0,4.0,1530.0,25.0,SatelliteHub_RRD,Pickuphub_MpHub_FKBGR2,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,1.0,2026-01-28,Returned_to_seller,2026-03-19,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,Returned_to_seller,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,99.0,>45,RTS>45_60,3000.0,-1.0,ageing 0,NaN,NaN,NaN
915414,G9S1EO8V6RJUC3JD,NaN,UNCP0000309219,FSD_LARGE,UNC,BANK NOTES,BANK NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-06,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,482002.0,JABALPUR,MADHYA PRADESH,2026-01-30,4.0,2026-01-30,2026-02-02,2026-02-02,2026-02-06T06:44:08.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T17:31:36.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,4130.0,ROI,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JLR,2026-02-07,2026-02-02,SPS,19.0,13.0,4130.0,25.0,SatelliteHub_JLR,SatelliteHub_JLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-02-02,delivered,2026-02-06,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,96.0,>45,Null,3000.0,-1.0,ageing 0,NaN,NaN,NaN
915415,64B1EZX31KGO5GB1,NaN,UNCP0000309258,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-07,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,410506.0,PUNE,MAHARASHTRA,2026-01-30,3.0,2026-01-30,2026-02-03,2026-02-03,2026-02-07T06:55:08.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T21:40:56.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,8000.0,METRO,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_PCMC,2026-02-07,2026-02-03,SPS,39.0,13.0,8000.0,26.0,Satellitehub_PCMC,Satellitehub_PCMC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-02-03,delivered,2026-02-07,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,96.0,>45,Null,3000.0,-1.0,ageing 0,NaN,NaN,NaN

In [69]:
#drf1['Date']=pd.to_datetime(drf1['Date']).dt.date
drf1['Date'] = pd.to_datetime(drf1['Date'], format='%d-%m-%Y').dt.date
drf1['check2']=np.where((drf1['Date'] > drf1['Latest_Update_Time']),True,False)
drf1['Current_Location']=np.where((drf1['check2']==True),drf1.Facility,drf1.Current_Location)
#drf2['Merged_current_location']=drf2['Merged_current_location'].fillna(drf2['Current_Location'])
drf1

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor,ERP_Status,Final_Status,Unnamed: 0,Timestamp,AWB_TID_number,Issue_Category,Status,Reason,PH_or_DH,Seller_type,Payment_Mode,Customer Code,shipment_value_1,todays_date,ageing_1,Ageing_bucket,loss,logistics_breach_bucket,last_scan_ageing,last_scan_ageing_bucket,Shipment/Bag ID,Date,Facility,check2
0,TFC001511752,NaN,AMAP0000000097,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-05-06,ShipmentUndeliveredAttempted,110086.0,Delhi,DELHI,682030.0,ERNAKULAM,KERALA,2026-04-28,1.0,2026-04-28,2026-04-28,2026-04-28,2026-05-04T06:24:00.000+05:30,2026-05-05T11:23:57.000+05:30,2026-05-05T11:23:57.000+05:30,NaN,Attempted,NaN,1.0,RequestForReschedule,RequestForReschedule,NaN,RequestForReschedule,NaN,NaN,NaN,6738.3,0.0,19000.0,ROI,False,NaN,2026-05-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_KOC,2026-05-05,2026-04-28,SPS,130.0,30.0,19000.0,30.0,SATELLITEHUB_KOC,SATELLITEHUB_KOC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,4.0,2026-04-28,Open,2026-05-06,8.0,AMAP0000000097,NORMAL_FORWARD,REGULAR,NaN,PP,6738.3,682030.0,Undelivered_Request_For_Reschedule,SATELLITEHUB_KOC,SATELLITEHUB_KOC,2026-05-05,CENTRALHUB_RPBAGHFM,28-04-2026 21:03,NaN,DELIVERY_DATE_CHANGED: 06-May-2026,1.0,NaN,NaN,06-05-2026 23:59,05-05-2026 03:15,NaN,NaN,SATELLITEHUB_KOC,04-05-2026 06:17,TFC001511752,NaN,NaN,NaN,NaN,Open,Open,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,8.0,<=45,Open,5000.0,1.0,ageing 0-2,NaN,NaT,NaN,False
1,885596,NaN,ARLP0000001325,FSD_LARGE,ARL,SINGER COOKMATE 5L,885596,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-13,ShipmentDelivered,401107.0,thane,MAHARASHTRA,282001.0,AGRA,UTTAR PRADESH,2026-02-07,2.0,2026-02-07,2026-02-09,NaT,2026-02-13T02:01:56.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T20:06:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-15T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_AGR1,2026-02-15,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_AGR1,SATELLITEHUB_AGR1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,88.0,>45,Null,2834.0,-1.0,ageing 0,NaN,NaT,NaN,False
2,885835,NaN,ARLP0000001328,FSD_LARGE,ARL,SINGER COOKMATE 5L,885835,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-19,ShipmentDelivered,401107.0,thane,MAHARASHTRA,147105.0,PATIALA,PUNJAB,2026-02-07,5.0,2026-02-07,2026-02-12,NaT,2026-02-18T10:09:16.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T17:43:18.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_Sangrur,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_Sangrur,SATELLITEHUB_Sangrur,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,88.0,>45,Null,2834.0,-1.0,ageing 0,NaN,NaT,NaN,False
3,907611,NaN,ARLP0000001553,FSD_LARGE,ARL,SINGER COOKMATE 5L,907611,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-24,ShipmentDelivered,401107.0,thane,MAHARASHTRA,323601.0,KESHORAIPATAN,RAJASTHAN,2026-02-07,5.0,2026-02-07,2026-02-12,NaT,2026-02-19T06:09:01.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T18:56:35.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T00:00:00+0530,Pickuphub_FKMIB,SATELLITEHUB_KOTA,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_KOTA,SATELLITEHUB_KOTA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,88.0,>45,Null,2834.0,-1.0,ageing 0,NaN,NaT,NaN,False
4,882107,NaN,ARLP0000001631,FSD_LARGE,ARL,SINGER LEO 3L WH,882107,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-16,ShipmentDelivered,401107.0,thane,MAHARASHTRA,333042.0,JHUJHUNU,RAJASTHAN,2026-02-07,2.0,2026-02-07,2026-02-09,NaT,2026-02-12T20:00:37.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T20:33:40.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,4640.0,0.0,3400.0,ROI,False,NaN,2026-02-18T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_JHUNJHUNU,2026-02-18,NaN,SPS,41.0,23.0,3400.0,26.0,SATELLITEHUB_JHUNJHUNU,SATELLITEHUB_JHUNJHUNU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,88.0,>45,Null,4640.0,-1.0,ageing 0,NaN,NaT,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915411,9GPUWN8KZ9WJFKJ2,NaN,UNCP0000308607,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-01-28,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,110085.0,NEW DELHI,DELHI,2026-01-22,1.0,2026-01-22,2026-01-22,2026-01-22,NaN,2026-01-27T08:36:13.000+05:30,2026-01-28T10:12:53.000+05:30,2026-01-28T22:30:00.000+05:30,Attempted,NaN,2.0,Customer Not Responding,Customer Not Responding,NaN,Customer Not Responding,NaN,NaN,NaN,3000.0,0.0,8000.0,METRO,False,NaN,2026-01-27T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_SAMAYPURDEPO,2026-01-27,2026-01-22,SPS,39.0,13.0,8000.0,26.0,SATELLITEHUB_SAMAYPURDEPO,SATELLITEHUB_SAMAYPURDEPO,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-01-22,delivered,2026-01-28,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,104.0,>45,Null,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False
915412,QCRWUID3QI246XZ2,NaN,UNCP0000308715,FSD_LARGE,UNC,GATE MECHANICAL,GATE MECHANICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,L,True,2026-01-26,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,560063.0,BANGALORE,KARNATAKA,2026-01-23,1.0,2026-01-23,2026-01-24,2026-01-24,NaN,2026-01-26T08:06:33.000+05:30,2026-01-26T08:06:33.000+05:30,2026-01-26T18:42:47.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,0.0,5090.0,LOCAL,False,NaN,2026-01-26T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_YEL,2026-01-26,2026-01-24,SPS,19.0,16.0,5090.0,25.0,SATELLITEHUB_YEL,SATELLITEHUB_YEL,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-01-24,delivered,2026-01-26,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,103.0,>45,Null,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False
915413,HMJ0IK5033JBLQE0,NaN,UNCP0000308804,FSD_LARGE,UNC,GATE DSAI,GATE DSAI,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,RTO,RTO,PP,N,True,2026-03-19,ShipmentRtoCompleted,560062.0,Bengaluru,KARNATAKA,400027.0,MUMBAI,MAHARASHTRA,2026-01-27,2.0,2026-01-27,2026-01-28,2026-01-28,2026-02-02T22:19:59.000+05:30,2026-02-02T22:35:05.000+05:30,2026-02-02T22:35:05.000+05:30,NaN,Attempted,2026-03-11T22:27:45.000+05:30,1.0,HeavyLoad,HeavyLoad,SatelliteHub_RRD,HeavyLoad,Shipment Delayed,NaN,ManpowerIssue,3000.0,0.0,1530.0,METRO,True,NaN,2026-02-01T03:15:00+0530,Pickuphub_FKBGR2,NaN,2026-02-01,2026-01-28,SPS,20.0,4.0,1530.0,25.0,SatelliteHub_RRD,Pickuphub_MpHub_FKBGR2,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,1.0,2026-01-28,Returned_to_seller,2026-03-19,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,Returned_to_seller,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,99.0,>45,RTS>45_60,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False
915414,G9S1EO8V6RJUC3JD,NaN,UNCP0000309219,FSD_LARGE,UNC,BANK NOTES,BANK NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-06,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,482002.0,JABALPUR,MADHYA PRADESH,2026-01-30,4.0,2026-01-30,2026-02-02,2026-02-02,2026-02-06T06:44:08.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T17:31:36.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,4130.0,ROI,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JLR,2026-02-07,2026-02-02,SPS,19.0,13.0,4130.0,25.0,SatelliteHub_JLR,SatelliteHub_JLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-02-02,delivered,2026-02-06,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,96.0,>45,Null,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False
915415,64B1EZX31KGO5GB1,NaN,UNCP0000309258,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-07,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,410506.0,PUNE,MAHARASHTRA,2026-01-30,3.0,2026-01-30,2026-02-03,2026-02-03,2026-02-07T06:55:08.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T21:40:56.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,8000.0,METRO,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_PCMC,2026-02-07,2026-02-03,SPS,39.0,13.0,8000.0,26.0,Satellitehub_PCMC,Satellitehub_PCMC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-02-03,delivered,2026-02-07,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,96.0,>45,Null,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False

In [70]:
map1=pd.read_excel("Large XD mapping_1.xlsx")
map1['Hub name']=map1['Hub name'].str.lower()
map1

drf1['Current_Location']=drf1['Current_Location'].str.lower()
drf2=drf1.merge(map1[['Hub name']],left_on='Current_Location',right_on='Hub name',how='left')
drf2

,order_id,global_tracking_id,tracking_id,vendor_code,merchant_code,product_title,product_id,product_category,client,seller_name,seller_id,ekl_shipment_type,type,payment_type,zone_movement_type,is_forward,last_updated_at,current_status,origin_pincode,origin_city,origin_state,dest_pincode,dest_city,dest_state,created_at,mp_no_of_pk_attempts,dispatch_date,ph_in_date_final,ph_in_time,dh_receive_time,first_ofd_time,last_ofd_time,delivered_time,attempt_status,rto_create_time,fsd_number_of_ofd_attempts,first_undelivery_status,last_undelivery_status,rto_marked_hub_location_name,undel_reason,rto_reason,rto_first_undelivery_status,unpick_reasons,shipment_value,amount_to_collect,seller_weight,ekart_lzn_flag,upstream_rto_flag,global_merchant_reference_id,shipped_lpd,Pickup_hub,Current_hubs,Shipped_LPD_date_key,PHin_date_key,mps_flag,seller_length,seller_height,seller_weight_1,seller_breadth,forward_dh,final_dh_rto_dh,fm_current_status,first_rvp_pickup_time,last_rvp_pickup_time,no_of_rvp_pickup_attemps,actual_rvp_pickup_time,rvp_reason,checks,ismandatory_list,fe_result_list,checks_failed,otp_generated,otp_validated,dispatch_month,PH_IN_date,FDP_status,end_date,ageing,Tracking_Id,Shipment_Type,Shipment_Tier_Type,Reverse_Shipment_Id,Type,Price,Delivery_Pincode,Latest_Status,Delivery_Hub,Current_Location,Latest_Update_Time,First_Receive_Hub,First_Receive_Time,Hub_Notes,Cs_Notes,No._of_Attempts,Bag_Id,BagStatus,Customer_Promise_Date,Logistics_Promise_Date,On_Hold_By_Ops_Reason,On_Hold_by_Ops_Date,First_Assigned_Hub_Name,Last_Receive_DateTime,Order_Id,Refund_Amount,Refund_Status,Reference_Number,Vendor,ERP_Status,Final_Status,Unnamed: 0,Timestamp,AWB_TID_number,Issue_Category,Status,Reason,PH_or_DH,Seller_type,Payment_Mode,Customer Code,shipment_value_1,todays_date,ageing_1,Ageing_bucket,loss,logistics_breach_bucket,last_scan_ageing,last_scan_ageing_bucket,Shipment/Bag ID,Date,Facility,check2,Hub name
0,TFC001511752,NaN,AMAP0000000097,FSD_LARGE,AMA,[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),[UY-BB-SNOOZE-JUMBO-2] \rYogi - Bean Bag Bed\r(1),ext_sps,AMA,AMA : Prem Nagar,AMA_0c0827efaa282c3e59ba2cfa6f5e92b3,Forward,SHIPMENT,PP,N,True,2026-05-06,ShipmentUndeliveredAttempted,110086.0,Delhi,DELHI,682030.0,ERNAKULAM,KERALA,2026-04-28,1.0,2026-04-28,2026-04-28,2026-04-28,2026-05-04T06:24:00.000+05:30,2026-05-05T11:23:57.000+05:30,2026-05-05T11:23:57.000+05:30,NaN,Attempted,NaN,1.0,RequestForReschedule,RequestForReschedule,NaN,RequestForReschedule,NaN,NaN,NaN,6738.3,0.0,19000.0,ROI,False,NaN,2026-05-05T03:15:00+0530,PICKUPHUB_RPBAGHFM,SATELLITEHUB_KOC,2026-05-05,2026-04-28,SPS,130.0,30.0,19000.0,30.0,SATELLITEHUB_KOC,SATELLITEHUB_KOC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,4.0,2026-04-28,Open,2026-05-06,8.0,AMAP0000000097,NORMAL_FORWARD,REGULAR,NaN,PP,6738.3,682030.0,Undelivered_Request_For_Reschedule,SATELLITEHUB_KOC,satellitehub_koc,2026-05-05,CENTRALHUB_RPBAGHFM,28-04-2026 21:03,NaN,DELIVERY_DATE_CHANGED: 06-May-2026,1.0,NaN,NaN,06-05-2026 23:59,05-05-2026 03:15,NaN,NaN,SATELLITEHUB_KOC,04-05-2026 06:17,TFC001511752,NaN,NaN,NaN,NaN,Open,Open,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,8.0,<=45,Open,5000.0,1.0,ageing 0-2,NaN,NaT,NaN,False,NaN
1,885596,NaN,ARLP0000001325,FSD_LARGE,ARL,SINGER COOKMATE 5L,885596,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-13,ShipmentDelivered,401107.0,thane,MAHARASHTRA,282001.0,AGRA,UTTAR PRADESH,2026-02-07,2.0,2026-02-07,2026-02-09,NaT,2026-02-13T02:01:56.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T08:48:04.000+05:30,2026-02-13T20:06:13.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-15T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_AGR1,2026-02-15,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_AGR1,SATELLITEHUB_AGR1,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,88.0,>45,Null,2834.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN
2,885835,NaN,ARLP0000001328,FSD_LARGE,ARL,SINGER COOKMATE 5L,885835,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-19,ShipmentDelivered,401107.0,thane,MAHARASHTRA,147105.0,PATIALA,PUNJAB,2026-02-07,5.0,2026-02-07,2026-02-12,NaT,2026-02-18T10:09:16.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T08:58:01.000+05:30,2026-02-19T17:43:18.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_Sangrur,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_Sangrur,SATELLITEHUB_Sangrur,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,88.0,>45,Null,2834.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN
3,907611,NaN,ARLP0000001553,FSD_LARGE,ARL,SINGER COOKMATE 5L,907611,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-24,ShipmentDelivered,401107.0,thane,MAHARASHTRA,323601.0,KESHORAIPATAN,RAJASTHAN,2026-02-07,5.0,2026-02-07,2026-02-12,NaT,2026-02-19T06:09:01.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T08:31:37.000+05:30,2026-02-24T18:56:35.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,HO_ShipmentNotReady,2834.0,0.0,2600.0,ROI,False,NaN,2026-02-23T00:00:00+0530,Pickuphub_FKMIB,SATELLITEHUB_KOTA,2026-02-23,NaN,SPS,45.0,20.0,2600.0,25.0,SATELLITEHUB_KOTA,SATELLITEHUB_KOTA,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,88.0,>45,Null,2834.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN
4,882107,NaN,ARLP0000001631,FSD_LARGE,ARL,SINGER LEO 3L WH,882107,ext_sps,ARL,ARL : ARL_TNE_01,ARL_c651159d56ba9d7d19709d4fe6f641b8,Forward,SHIPMENT,PP,N,True,2026-02-16,ShipmentDelivered,401107.0,thane,MAHARASHTRA,333042.0,JHUJHUNU,RAJASTHAN,2026-02-07,2.0,2026-02-07,2026-02-09,NaT,2026-02-12T20:00:37.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T06:50:15.000+05:30,2026-02-16T20:33:40.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,4640.0,0.0,3400.0,ROI,False,NaN,2026-02-18T03:15:00+0530,Pickuphub_FKMIB,SATELLITEHUB_JHUNJHUNU,2026-02-18,NaN,SPS,41.0,23.0,3400.0,26.0,SATELLITEHUB_JHUNJHUNU,SATELLITEHUB_JHUNJHUNU,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,2.0,NaT,delivered,2026-02-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,88.0,>45,Null,4640.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
942393,9GPUWN8KZ9WJFKJ2,NaN,UNCP0000308607,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-01-28,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,110085.0,NEW DELHI,DELHI,2026-01-22,1.0,2026-01-22,2026-01-22,2026-01-22,NaN,2026-01-27T08:36:13.000+05:30,2026-01-28T10:12:53.000+05:30,2026-01-28T22:30:00.000+05:30,Attempted,NaN,2.0,Customer Not Responding,Customer Not Responding,NaN,Customer Not Responding,NaN,NaN,NaN,3000.0,0.0,8000.0,METRO,False,NaN,2026-01-27T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_SAMAYPURDEPO,2026-01-27,2026-01-22,SPS,39.0,13.0,8000.0,26.0,SATELLITEHUB_SAMAYPURDEPO,SATELLITEHUB_SAMAYPURDEPO,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-01-22,delivered,2026-01-28,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,104.0,>45,Null,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN
942394,QCRWUID3QI246XZ2,NaN,UNCP0000308715,FSD_LARGE,UNC,GATE MECHANICAL,GATE MECHANICAL,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,L,True,2026-01-26,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,560063.0,BANGALORE,KARNATAKA,2026-01-23,1.0,2026-01-23,2026-01-24,2026-01-24,NaN,2026-01-26T08:06:33.000+05:30,2026-01-26T08:06:33.000+05:30,2026-01-26T18:42:47.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000.0,0.0,5090.0,LOCAL,False,NaN,2026-01-26T03:15:00+0530,Pickuphub_FKBGR2,SATELLITEHUB_YEL,2026-01-26,2026-01-24,SPS,19.0,16.0,5090.0,25.0,SATELLITEHUB_YEL,SATELLITEHUB_YEL,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-01-24,delivered,2026-01-26,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,103.0,>45,Null,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN
942395,HMJ0IK5033JBLQE0,NaN,UNCP0000308804,FSD_LARGE,UNC,GATE DSAI,GATE DSAI,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,RTO,RTO,PP,N,True,2026-03-19,ShipmentRtoCompleted,560062.0,Bengaluru,KARNATAKA,400027.0,MUMBAI,MAHARASHTRA,2026-01-27,2.0,2026-01-27,2026-01-28,2026-01-28,2026-02-02T22:19:59.000+05:30,2026-02-02T22:35:05.000+05:30,2026-02-02T22:35:05.000+05:30,NaN,Attempted,2026-03-11T22:27:45.000+05:30,1.0,HeavyLoad,HeavyLoad,SatelliteHub_RRD,HeavyLoad,Shipment Delayed,NaN,ManpowerIssue,3000.0,0.0,1530.0,METRO,True,NaN,2026-02-01T03:15:00+0530,Pickuphub_FKBGR2,NaN,2026-02-01,2026-01-28,SPS,20.0,4.0,1530.0,25.0,SatelliteHub_RRD,Pickuphub_MpHub_FKBGR2,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,False,1.0,2026-01-28,Returned_to_seller,2026-03-19,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,Returned_to_seller,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,99.0,>45,RTS>45_60,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN
942396,G9S1EO8V6RJUC3JD,NaN,UNCP0000309219,FSD_LARGE,UNC,BANK NOTES,BANK NOTES,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-06,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,482002.0,JABALPUR,MADHYA PRADESH,2026-01-30,4.0,2026-01-30,2026-02-02,2026-02-02,2026-02-06T06:44:08.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T07:17:12.000+05:30,2026-02-06T17:31:36.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,4130.0,ROI,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,SatelliteHub_JLR,2026-02-07,2026-02-02,SPS,19.0,13.0,4130.0,25.0,SatelliteHub_JLR,SatelliteHub_JLR,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-02-02,delivered,2026-02-06,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,96.0,>45,Null,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN
942397,64B1EZX31KGO5GB1,NaN,UNCP0000309258,FSD_LARGE,UNC,UPSC ENGLISH VERSION 3.0,UPSC ENGLISH VERSION 3.0,ext_sps,UNC,UNC : UNC_BNG_01,UNC_93a4c9bd6392c07cda81ea9b4048de15,Forward,SHIPMENT,PP,N,True,2026-02-07,ShipmentDelivered,560062.0,Bengaluru,KARNATAKA,410506.0,PUNE,MAHARASHTRA,2026-01-30,3.0,2026-01-30,2026-02-03,2026-02-03,2026-02-07T06:55:08.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T10:40:02.000+05:30,2026-02-07T21:40:56.000+05:30,Attempted,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,ManpowerIssue,3000.0,0.0,8000.0,METRO,False,NaN,2026-02-07T03:15:00+0530,Pickuphub_FKBGR2,Satellitehub_PCMC,2026-02-07,2026-02-03,SPS,39.0,13.0,8000.0,26.0,Satellitehub_PCMC,Satellitehub_PCMC,dispatched_to_ph,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.0,2026-02-03,delivered,2026-02-07,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Open,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,630,2026-05-06,96.0,>45,Null,3000.0,-1.0,ageing 0,NaN,NaT,NaN,False,NaN

In [71]:
drf2['Pickup_hub']=drf2['Pickup_hub'].str.lower()
drf2['Pickuphub_new'] = drf2['Pickup_hub'].str.split('_').str[-1].str.rstrip('0123456789')
drf2['Current_loc_new'] = drf2['Current_Location'].str.split('_').str[-1].str.rstrip('0123456789')

drf2['check']=drf2['Pickuphub_new']==drf2['Current_loc_new']

satellite_bulk_condition = drf2['Current_Location'].str.startswith(('satellitehub', 'bulkhub'))
check_condition = ~(drf2['Latest_Status'] == 'Expected') & (drf2['check'] == True)  
hub_name_condition = drf2['Hub name'].notnull()
expected = (drf2['Latest_Status'] == 'Expected') & (drf2['Current_Location'].str.startswith(('satellitehub', 'bulkhub')))
expected1 = (drf2['Latest_Status'] == 'Expected') & (drf2['check'] == True)
expected2 = (drf2['Latest_Status'] == 'Expected') & (drf2['Hub name'].notnull())

drf2['Asset'] =np.where(expected,'In Transit LM',
               np.where(expected1,'In Transit FM',
               np.where(expected2,'In Transit XD',
                np.where(satellite_bulk_condition, 'AT LM',
               np.where(check_condition, 'AT FM',
               np.where(hub_name_condition, 'AT XD','Nan'))))))

drf2.Asset.value_counts()

Asset
Nan              868980
In Transit XD     30701
AT XD             23359
AT LM             14386
AT FM              2111
In Transit LM      1846
In Transit FM      1015
Name: count, dtype: int64

In [72]:
os.chdir(r"C:\Users\mohammadali1.vc\Desktop\Python data\Large Check File")
s8.to_csv("large_sum_06_May Rev_1.csv")
drf2.to_csv("large_check_06_May Rev_1.csv",index=False)